### ISSUE TITLE
Can not Export CREATOR Field for IParcelable instance

### ISSUE THREAD

**Issue by fullmetaltac** [xamarin/xamarin-android#1149]
#### Sample link

https://github.com/xamarin/monodroid-samples/blob/f944f42001fa134915069fa7bbb9cb493bfd446d/ExportAttribute/ExportAttributeTest/MainActivity.cs#L55
https://github.com/xamarin/monodroid-samples/blob/f944f42001fa134915069fa7bbb9cb493bfd446d/android5.0/Topeka/Topeka/Models/Player.cs#L18

Verified on Monodroid v8.2.0.1

#### Issue description

Can not ExportField  CREATOR for IParcelable instance

#### Steps to reproduce the issue

1.  Open Topeka sample.
2. Input login info.
3. Tap Login button.

#### What's the expected result?

- User successfully login.

#### What's the actual result?

- Application crashes.

#### Steps to reproduce the issue

1.  Open ExportAttributeTest sample.
2. Tap button.

#### What's the expected result?

- Parcelable object handled properly.

#### What's the actual result?

- Application crashes.

#### Additional details / screenshot (Optional)
![image](https://user-images.githubusercontent.com/5435980/34485695-9f9fda4c-efd4-11e7-9e8b-5f00514d1027.png)

InitializeCreator method is not reachable via debugger.
[MSBuildOutput.log](https://github.com/xamarin/xamarin-android/files/1597918/MSBuildOutput.log)
[logCat.txt](https://github.com/xamarin/xamarin-android/files/1597919/logCat.txt)

**Comment by jonpryor** [comment]
This does *not* crash on d15-5/Xamarin.Android 8.1.

@fullmetaltac: Does this happen in the *Debug* configuration or when linking is disabled?

@radekdoulik: I suspect that this is a linker bug, and that `Player.InitializeCreator()` is being linked away, which would explain why [it can't be found](https://github.com/xamarin/xamarin-android/blob/d15-6/src/Mono.Android/Android.Runtime/JNIEnv.cs#L176).

Could this be related to PR #1059?

**Comment by fullmetaltac** [comment]
@jonpryor Should I close this duplicate?
https://github.com/xamarin/xamarin-android/issues/1149

**Comment by radekdoulik** [comment]
Looks like it is not Linker related. Happens in Debug configuration as well.

I will try to find out why it fails.

**Comment by radekdoulik** [comment]
@jonathanpeppers Looks like it might be related to https://github.com/xamarin/java.interop/commit/429dc2a68579c9a820f03a7f09f35da3db9cd54a

Do you know what might be wrong here? Looks like we might be looking for wrong signature?

**Comment by jonpryor** [comment]
@radekdoulik: @jonathanpeppers is OOF until ~march, so don't expect much from him. :-)

I also doubt that it's https://github.com/xamarin/java.interop/commit/429dc2a68579c9a820f03a7f09f35da3db9cd54a, as the bug is reported against *d15-6*, and the referenced Java.Interop commit should only be in d15-7/master, *not* d15-6. (At least *it better not be* in d15-6; I wanted it to get more testing!)

I don't see that commit in https://github.com/xamarin/Java.Interop/commits/d15-6.

@radekdoulik: Do you have any additional information to bring to the table?

**Comment by radekdoulik** [comment]
@jonpryor Indeed. Another candidate might be https://github.com/xamarin/java.interop/commit/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa

Trying to find out more about it.

**Comment by radekdoulik** [comment]
The above mentioned commit indeed caused the regression.

The signature for the `InitializeCreator` signature is now `()Ljava/lang/Object;` while it was `()Lmd59b7a7576784821ea63294fbca8600da1/Creator_1;` before.

**Comment by jonpryor** [comment]
@radekdoulik: I think I have a theory. Consider [`JavaNativeTypeManager.ToJniNameFromAttributes(TypeDefinition)`](https://github.com/xamarin/java.interop/commit/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa#diff-9e153905b02dbe50c0e0b874ba40bf3eR451). What happens if the `TypeDefinition` does *not* implement `IJniNameProviderAttribute`?

In particular, [`Creator<T>`](https://github.com/xamarin/monodroid-samples/blob/f944f42001fa134915069fa7bbb9cb493bfd446d/android5.0/Topeka/Topeka/Helpers/Creator.cs) does not implement `IJniNameProviderAttribute` -- nor should it.

If the `TypeDefinition` (`typeof(Creator<>)`) does *not* implement `IJniNameProviderAttribute`, then `JavaNativeTypeManager.ToJniNameFromAttributes(TypeDefinition)` will return `null`, which means `JavaNativeTypeManager.ToJniName(TypeDefinition)` will [return `java/lang/Object`](https://github.com/xamarin/java.interop/blob/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa/src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs#L430), which explains the new signature you're seeing for `InitializeCreator()`.

...which doesn't *actually* make sense; shouldn't the [`IJavaObject` check in `JavaNativeTypeManager.ToJniName(TypeDefinition, ExportKind)`](https://github.com/xamarin/java.interop/blob/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa/src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs#L444) catch `Creator<T>`? In which case we should be hitting [`ToJniName<T>()`](https://github.com/xamarin/java.interop/blob/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa/src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs#L523-L559), which should create the `md5.../Creator_1` name.

More digging is needed. :-(

**Comment by fullmetaltac** [comment]
Fix Verified. Issue in not reproduced.

**Comment by MP91** [comment]
Hi @all!
I am using Visual Studio for Mac and still have this error. I am on the latest stable release (16-3).
Is there anything I have to do?
