### ISSUE TITLE
Source File Path in PDB is not an absolute path

### ISSUE THREAD

**Issue by psmacchia** [xamarin/xamarin-android#1220]
A user of our product that analyzes assemblies PDBs and source code, send us a assembly+PDB that contain source file paths that are not absolute file paths, like:

the string extracted for such a path is for example:
"/Users/XXXXXX/Documents/XXXXXXXMobileEstate/Apps/PlatformDemoApp-Mvx/PlatformDemoApp-Mvx.Droid/Resources/Resource.designer.cs"

In all the .NET stack so far PDB files only contain valid absolute paths (prefixed with a drive letter or UNC format)

**Comment by jonpryor** [comment]
`/Users/XXXXXX/Documents/XXXXXXXMobileEstate/...` *is* an absolute path.

It's an absolute path from *macOS*.

There is thus no "drive letter" or "UNC format" to provide. Those constructs *do not exist* on macOS. (Or Linux, for that matter.)

Please update your program expectations so that you do not require Windows to use it.
