### ISSUE TITLE
Could not install package 'Xamarin.Android.Support.Compat 25.4.0.2'

### ISSUE THREAD

**Issue by Ashwakum** [xamarin/xamarin-android#1236]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Xamarin.Android.Support.Compat 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
How to use map in xamarin.forms.maps

How to solve this issue

**Comment by Redth** [comment]
Android Support library major version numbers should generally match your Xamarin.Android app's Target Framework (known as compileSdkVersion in grade) api level number.

So in your case, you are compiling (targeting framework) against v6.0 which is API Level *23*, which is why Android Support *25*.4.0.2 will not install.  You must change your project to compile against (target framework set to) API Level 25 or higher (so Android 7.1 or higher) in order to use this version of Android support libraries.
