### ISSUE TITLE
Unable to rebuild project with hybrid AOT enabled

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1240]
### Steps to Reproduce

1. Attempt to compile the Codegen test suite with AOT, LLVM, and Hybrid AOT (/p:AndroidAotMode=Hybrid) enabled.

### Expected Behavior
I'm able to compile and run any XA project with Hybrid AOT enabled.

### Actual Behavior
Notice multiple errors coming from the aot task informing that methods can not be compiled successfully:
>  [aot-compiler stderr] Unable to compile method 'bool System.Collections.Specialized.ListDictionary/NodeKeyValueCollection/NodeKeyValueEnumerator:MoveNext ()' due to: 'Invalid IL code in System.Collections.Specialized.ListDictionary/NodeKeyValueCollection/NodeKeyValueEnumerator:MoveNext (): IL_0000: ret        (TaskId:1362)

The build ultimately fails with `error XA3001: System.IO.IOException: Win32 IO returned ERROR_ALREADY_EXISTS.` during Xamarin.Android.Tasks.CilStrip.Execute.

### Version Information
https://gist.github.com/pjcollins/7d20f81013c7e00982c91340af2cf560

### Log File
http://xqa.blob.core.windows.net/gist/log-63b871d9098d441d80a2838bb9fa2860.txt

> VS bug [#947891](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/947891)

**Comment by jonpryor** [comment]
It *looks* like this error is happening *before* we IL-strip the assemblies, so it doesn't appear to be a build task ordering issue.

**Comment by vargaz** [comment]
Could you upload the tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release directory ?

**Comment by pjcollins** [comment]
@vargaz here's the intermediate output - https://microsoft-my.sharepoint.com/:u:/p/pecolli/EZcB-AYr2z5NlFocWnr_u1MBsJcXYNImuhgF8CSzqIsaVQ?e=ypELnj

I'll try to remember to include this in the report for such issues in the future.

**Comment by vargaz** [comment]
Are you sure that is the correct obj dir ? I get a mscorlib version mismatch error:

Corlib not in sync with this runtime: expected corlib version 1050800000, found 1050400003.
Loaded from: /Users/vargaz/Projects/xamarin-android-1240/jcwgen-obj/Release/android/assets/shrunk/mscorlib.dll

1050800000 is for mono 2.10, while 10504 is for an older version.

**Comment by vargaz** [comment]
The invalid IL messages all reference 'ret', which means the AOT compiler is ran on the IL stripped code. Also, the aot compiler command line references the 'shrunk' directory which seems to contain the IL stripped versions:

MONO_PATH="/Users/xamarinqa/myagent/_work/r3/a/monodroid/external/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/android/assets/shrunk" MONO_ENV_OPTIONS="" /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/cross-arm --llvm --aot=hybrid,outfile=/Users/xamarinqa/myagent/_work/r3/a/monodroid/external/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/aot/armeabi/libaot-Java.Interop.dll.so,asmwriter,mtriple=armv5-linux-gnueabi,tool-prefix=/Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-,ld-flags=/Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a;/Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/platforms/android-9/arch-arm/usr/lib/libc.so;/Users/xamarinqa/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/platforms/android-9/arch-arm/usr/lib/libm.so,llvm-path=/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin,temp-path=/Users/xamarinqa/myagent/_work/r3/a/monodroid/external/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/aot/armeabi/Java.Interop.dll /Users/xamarinqa/myagent/_work/r3/a/monodroid/external/xamarin-android/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/obj/Release/android/assets/shrunk/Java.Interop.dll (TaskId:1362)

**Comment by pjcollins** [comment]
@vargaz The local repro uploaded in the previous comment is from d15-5, the issue is reproducible both there and in d15-6. Should I upload another output dir built against d15-6 or master?

**Comment by vargaz** [comment]
Not needed any more, I think 
https://github.com/xamarin/xamarin-android/issues/1240#issuecomment-360824450
is the problem.

**Comment by jonpryor** [comment]
@vargaz: I don't understand *how* it's the problem. The `<CilStrip/>` task is executed on line 317911.

AOT compilation *ends* on line 317765 -- 146 lines *before* the IL strip.

*How* are we attempting to AOT *stripped* assemblies when we don't execute the task to strip assemblies until *after* AOT runs?

*A* plausible answer would be "the project is built multiple times, with the second build processing the stripped outputs of the first build." However, I see no evidence of that scenario in the log file.

**Comment by vargaz** [comment]
Does the 'shrunk' directory contain linker output files ? It could be a problem with the linker, i.e. it creates invalid il ?

**Comment by vargaz** [comment]
The input file contains stuff like this:

  .method public hidebysig static string 
          GetText(string msg) cil managed noinlining
  {
    // Code size       1 (0x1)
    .maxstack  8
    IL_0000:  ret
  } // end of method Locale::GetText

which is not valid IL.

**Comment by jonpryor** [comment]
> Does the 'shrunk' directory contain linker output files?

The `_RemoveRegisterAttribute` target copies the `obj/Release/android/assets` files into `obj/Release/android/assets/shrunk`, then updates the assemblies within `obj/Release/android/assets/shrunk`.

> It could be a problem with the linker, i.e. it creates invalid il ?

Possible, but what's *really* weird is that the linker doesn't appear to be running: the `LinkAssemblies` task isn't executed, and the `_LinkAssembliesShrink` target finishes in 1ms.

@radekdoulik: Do you know why the assemblies used as input to AOT would appear to be invalid?

**Comment by Belorus** [comment]
duplicate https://github.com/xamarin/xamarin-android/issues/1218

**Comment by pjcollins** [comment]
This is still reproducible using XA d15.8 - 8.3.99.12 (monodroid/de662f58d).

http://xqa.blob.core.windows.net/gist/log-8294c709d0bc4d099ae5273bb88bf162.txt

**Comment by jonpryor** [comment]
@radekdoulik: Please take another look at this.

**Comment by radekdoulik** [comment]
OK, I am now able to reproduce with master.

The steps are following:

* build in Release configuration without AOT
* build in Release configuration with hybrid AOT

It looks different to the original problem where aot-compiler reported errors.

In my case I don't see aot-compiler errors, only CilStrip problem at the end of the log mentioned in https://github.com/xamarin/xamarin-android/issues/1240#issuecomment-390742535

From my build log:
```
/Users/rodo/git/xa5/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2660,4): error XA3001: System.IO.IOException: Win32 IO returned ERROR_ALREADY_EXISTS. Path:  [/Users/rodo/git/xa5/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
/Users/rodo/git/xa5/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2660,4): error XA3001:   at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00102] in <7e59c4ad7b424f9eab0db1b78ec1804f>:0  [/Users/rodo/git/xa5/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
/Users/rodo/git/xa5/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2660,4): error XA3001:   at Xamarin.Android.Tasks.CilStrip.DoExecute () [0x000ca] in <71e70fc60389471c98c06e92be3df0b7>:0  [/Users/rodo/git/xa5/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
/Users/rodo/git/xa5/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2660,4): error XA3001:   at Xamarin.Android.Tasks.CilStrip.Execute () [0x00002] in <71e70fc60389471c98c06e92be3df0b7>:0  [/Users/rodo/git/xa5/tests/CodeGen-Binding/Xamarin.Android.JcwGen-Tests/Xamarin.Android.JcwGen-Tests.csproj]
Done executing task "CilStrip" -- FAILED. (TaskId:603)
```

**Comment by radekdoulik** [comment]
Better repro, with aot-compiler errors as well:

* build in Release configuration with hybrid AOT
* build in Release configuration with hybrid AOT again

Looks like build process error to me, where we try to AOT compile the already stripped assemblies in the second build. Linker doesn't even run as the output files are newer than input files.

@dellis1972 could you take a look at this please?

This is my command line to build the test with hybrid AOT
`./tools/scripts/xabuild /v:diag /p:AotAssemblies=True /p:AndroidAotMode=Hybrid /p:Configuration=Release /t:SignAndroidPackage tests/CodeGen-Binding/Xamarin.Android.Jcwn.Android.JcwGen-Tests.csproj`

**Comment by dellis1972** [comment]
ok I think there are a couple of problems here. The main on is that the `Aot` task is running when it really shouldn't be. No changes have been made. The logs reviled  the following on many of the binding projects.

```
 Input file "/var/folders/n_/vt_nzq1n04schx5yy2jgcgcw0000gn/T/MonoAndroid,Version=v9.0.AssemblyAttributes.cs" is newer than output file "obj/Release/Xamarin.Android.McwGen-Tests.pdb".
```

This then results is `CoreCompile` running on the main app, because the binding project assemblies have been updated. That is only part of the problem. I still need to look at `CilStrip` and see what is going on there.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
