### ISSUE TITLE
Can't override GetAutofillOptions in ArrayAdapter class.

### ISSUE THREAD

**Issue by fullmetaltac** [xamarin/xamarin-android#1250]
### Steps to Reproduce

1. Create some class, e.g. with name TestClass
2. Extend it from Android.Widget.ArrayAdapter
3. override GetAutofillOptions method

### Expected Behavior
Method can be overridden.

### Actual Behavior
Error: There is no suitable method for override

### Version Information
[VS_info.txt](https://github.com/xamarin/xamarin-android/files/1678126/VS_info.txt)

### Comment
I was converting this line of code:
https://github.com/googlesamples/android-AutofillFramework/blob/16625cf003034585cefc882a165e2f1fae58634e/Application/src/main/java/com/example/android/autofill/app/commoncases/CreditCardSpinnersActivity.java#L82

In Java Adapter interface has definition of this mehod
![image](https://user-images.githubusercontent.com/5435980/35572664-c8021bd4-05dd-11e8-8a87-c47564b7b765.png)

In .Net we had't such method definition
![image](https://user-images.githubusercontent.com/5435980/35572710-de80160e-05dd-11e8-994a-d04ad33edde1.png)

**Comment by atsushieno** [comment]
Can't you override GetAutofillOptionsFormatted() just like other CharSequence related method bindings? That's how Xamarin.Android expects developers to do the thing.

**Comment by jonpryor** [comment]
@pjcollins: Question: if you're within Visual Studio and you type `override GetAutof`, does the IDE suggest `GetAutofillOptionsFormatted()` in the autocomplete?

**Comment by fullmetaltac** [comment]
@jonpryor Yes. Visual studio suggest GetAutofillOptionsFormatted method.

**Comment by jonpryor** [comment]
@fullmetaltac: Here's the background: in Java, `java.lang.String` implements `java.lang.CharSequence`. In C#, `System.String` cannot implement `Java.Lang.ICharSequence`, at least not until C# supports extension interfaces.

Thus, given a Java method `void foo(CharSequence v)`, Java allows calling it as `foo("string")`.

We wanted C# to also allow using `Foo("string")`. In order to do that, we *could* have overloaded with `Foo(ICharSequence)` and `Foo(string)`, but that only works for parameters. Often -- as with `GetAutofillOptions()` -- it's the *return type* which changes.

To deal with this, our binding will rename the methods which use `ICharSequence` to have a `Formatted` suffix, and the "normal" method uses `string` types. Thus:

```csharp
partial class ArrayAdapter {
    public override ICharSequence[] GetAutofillOptionsFormatted();
    public new string[] GetAutofillOptions();
}
``` 

As such, this behabior is By Design, and when translating Java to C# in the future you should rely on the IDE code completion more. :-)

**Comment by fullmetaltac** [comment]
@jonpryor Thanks.
