### ISSUE TITLE
Unable to discover new string resource (or other xml defined resources) in Intellisense after building

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1287]
This issue appears to be a regression in d15-6, so I will be adding it to the 15.6 milestone. However, I am not sure if it is related to the managed resource parser changes that have been re-enabled there.

### Steps to Reproduce

1. Create a new Single-View Android App.
2. Add a new string entry in Resources -> values -> Strings.xml, such as:
```xml
<string name="test">test</string>
```
3. Open MainActivity.cs and confirm that you are unable to see Intellisense for `Resource.String.test`.
4. Select Build -> Build solution
5. Open MainActivity.cs and confirm that you are _still_ unable to see Intellisense for `Resource.String.test`.

### Expected Behavior
Newly added string and other xml resources can be discovered via Intellisense immediately after completing a build.

### Actual Behavior
Intellisense does not work for a new string resource after building.

### Version Information
VS 15.6 Preview 4:
https://gist.github.com/pjcollins/b8be35efd9b9eb0fb7e1355e74396fd2

### Log File
Diagnostic build output:
https://gist.github.com/pjcollins/292e2acf118eaced6de4124aedf15254

**Comment by dellis1972** [comment]
@pjcollins that log output looks like a normal build , not a design time build.

**Comment by pjcollins** [comment]
Sorry about that, here's the binlog for the DesignTimeBuild which occurred immediately after an explicit build:

[App21_Debug_AnyCPU_DesignTimeBuild_2018-02-08T14_45_39.4140376-05_00.zip](https://github.com/xamarin/xamarin-android/files/1708554/App21_Debug_AnyCPU_DesignTimeBuild_2018-02-08T14_45_39.4140376-05_00.zip)

**Comment by dellis1972** [comment]
@pjcollins looking at that log file there is no compile call and the `DesignTimeBuild` = `false` so I have no idea what is going on... I'll try and repo this issue locally on the latest 15.6 release

**Comment by tekxpertt** [comment]
In my AndroidManifest.xml there is the usual app name reference: @string/app_name This string is defined in main/res/values/strings.xml.
[https://babasupport.org/routers/zte-router-customer-service/657](https://babasupport.org/routers/zte-router-customer-service/657)

**Comment by pjcollins** [comment]
This also affects newly added elements in Layout files as well. For example, if you open a layout file in the designer and either add a new layout element via code or by dragging a widget on to the designer, intellisense seemingly _never_ kicks in until the entire solution is reloaded. This seems somewhat nasty.

Finally, new compilation issues will surface if you attempt to reference a resource that _does not_ exist. Not only will you receive an error for the element that does not exist, but new errors will be reported for the previously added and referenced resources which _do_ exist.

Here's a slightly modified version of the steps in the description which demonstrate this last point:

1) Create a new Single-View Android App.
2) Add a two new string entry in Resources -> values -> Strings.xml, such as:
```xml
<string name="test">test</string>
<string name="test2">test2</string>
```
3) Open MainActivity.cs and add the following lines to your OnCreate method:
```csharp
var res = Resource.String.test;
var res2 = Resource.String.test2;
```

4) Build your solution. This build should be successful, even though intellisense is reporting issues with the two lines shown above.
5) Modify the OnCreate method, to include the following
```csharp
var res3 = Resource.String.doesnotexist;
```
6) Attempt to build the solution again. Now three errors should be reported for `doesnotexist`, `test2`, and `test`. This is strange, as `test` and `test2` do exist, and did not cause build errors earlier (even if intellisense seemed to indicate otherwise).


----

Finally if I apply the following diff to my Xamarin.Android.Common.targets file, these issues go away in 15.6. This indicates to me that all of these negative behaviors are managed resource parser related.
+ <AndroidUseManagedDesignTimeResourceGenerator Condition=" '$(AndroidUseManagedDesignTimeResourceGenerator)' == '' " >False</AndroidUseManagedDesignTimeResourceGenerator>

**Comment by pjcollins** [comment]
Updating the milestone to 15.7, as this has now been disabled for 15.6.

**Comment by dellis1972** [comment]
Looks like we need to run a target ourselves to update the design time resource designer file before intellisense  will pick it up.

**Comment by jonpryor** [comment]
@dellis1972 wrote:

> Looks like we need to run a target ourselves to update the design time resource designer file before intellisense will pick it up.

How are we going to do *that*?! Create a `FileSystemWatcher` on everything in the project dir and execute the target on file changes? (Please don't do this.)

Or is this a sign that we should once again take a stab at fixing [Bug #5870](https://bugzilla.xamarin.com/show_bug.cgi?id=5870), have the IDE emit `%(AndroidResource.Generator)` metadata, and use the target specified in `%(AndroidResource.Generator)` *also* trigger a DesignTimeBuild update?

Related: https://mhut.ch/journal/2015/06/30/build_time_code_generation_msbuild  
Related: https://trello.com/c/W5Mgou72/4-resourcedesignercs  
Related: https://trello.com/c/ypQrdAQb/179-migration-to-automatic-resourcedesignercs-generation

**Comment by dellis1972** [comment]
Reviving the Generator branch should do the trick. I will rebase it
tomorrow and give it a test. The code I have should work out of the box
with VS, just not with VSForMac.

**Comment by dellis1972** [comment]
now that I think about it. Generator won't help us here because we need to run it for both a normal build and a design time build since we don't use the same file anymore... It will help us know when a file changed in the targets though.. I'll need to figure out what to do then

**Comment by dellis1972** [comment]
ok.. I change the following code 

`
<AndroidResource Include="Resources\values\styles.xml" />
`
to

`
<AndroidResource Include="Resources\values\styles.xml">
      <Generator>MSBuild:UpdateAndroidResources</Generator>
</AndroidResource>
`

And that fixes the design time build issue. What happens is we run `UpdateAndroidResources` when the file is modified. Because its not a `Build` and `$(DesignTimeBuild) == ''` we do a design time build since we end updating `_SetupDesignTimeBuildForCompile`. This then updates the designer in the designtime folder and we get correct intelligence.

Now the problem is I don't think the the `Generator`metadata is something we can add on the fly. I think in order for VS to use it, it has to be on the Item at project load. I am going to test this and see if I can just add it on the fly. If not then we are going to need to update ALL `AndroidResource` items to have this metadata. Related PR [1]

[1] https://github.com/xamarin/xamarin-android/pull/1327

**Comment by dellis1972** [comment]
@jonpryor wrote

> @dellis1972 wrote:

>> Looks like we need to run a target ourselves to update the design time resource designer file before intellisense will pick it up.


> How are we going to do that?! Create a FileSystemWatcher on everything in the project dir and execute the target on file changes? (Please don't do this.)

If we did the "running the target ourselves" thing. The IDE addin would need to deal with that, not sure if they have code to handle that already (@joj might know). It would need to monitor `AndroidResources` and call `UpdateAndroidResources` on update. I believe the IDE used to do that a while back. 

At the moment its looking like any fix is either going to be pain because we need IDE support to either add the `Generator` metadata or add a file monitor. What ever I do I can't get the DTB to run. After chats with the roslyn project system team they recommend  using Generator metadata as its they way UWP/xaml based apps work. But then again they don't have to worry about VSForMac support while we do. 

Note I also tried adding the `AndroidResource` items to `CustomAdditionalCompileInputs` which is an input to the `<CoreCompile/>` target [1]. The hope was it would detect the updated android resource and trigger a Design Time Build. But that didn't work either.


[1] https://referencesource.microsoft.com/#MSBuildFiles/C/ProgramFiles(x86)/MSBuild/14.0/bin_/amd64/Microsoft.CSharp.Core.targets,15

**Comment by pjcollins** [comment]
I'm no longer able to reproduce any of the negative behavior described in the initial report or in the fourth comment. Adding the verified tag against d15-7 (XA 8.3.0.11)

**Comment by Codwy** [comment]
1. Is it possible to make Intellisense update without building the application, because when I add a string and try to access it, Intellisense  hilight it in red  as not found, I believe is not practical nor productive to build each time.

2. When I remove or rename a string resource which was accessed in the code before, Intellisense  won't highlight it in red as not found, and of course the build will fail and report it after as not found.

Should I open a new issue or this one will be reopened ?
