### ISSUE TITLE
How to Exclude default material icons from Xamarin.Android Apk?

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#1288]
I unzipped my apk and in res folder there many sub folders as shown below and each folder has icons which are not part of my project as shown in the 2nd image. At least they arent in my source code. I dont know where they are coming from. Probably Xamarin.Android includes them as default material icons. But I am using my own svg icons as embedded resources in my PCL project and I dont need those pngs to be part of my apk. They just bloat and increase size of my apk (even though probably 1-2mb max.)

How can I exclude or remove those? I am already using full linking and proguard in my xamarin.android project.

![image](https://user-images.githubusercontent.com/10422347/36021825-535fbf8c-0d87-11e8-81a7-151d4399740c.png)

![image](https://user-images.githubusercontent.com/10422347/36021837-57d134f6-0d87-11e8-9716-bde7faf0cfdb.png)

**Comment by JonDouglas** [comment]
These resources come from referencing a library such as `Android Support Libraries` or `Google Play Services` in your project. They are included in your project when resources are merged at build time.

You can read up on the [concept of resource merging](https://developer.android.com/studio/write/add-resources.html#resource_merging) to understand why your final APK includes these items. Since this is not an issue with the source code of Xamarin.Android, I would recommend that you read over our [support options](https://developer.xamarin.com/guides/cross-platform/troubleshooting/support-options/#Summary_of_Support_Options) to best suit your follow-up questions. In this case, I would recommend opening up a [Stack Overflow question.](https://stackoverflow.com/questions/ask?tags=xamarin)

**Comment by EmilAlipiev** [comment]
@JonDouglas  thank you for your response. I had already created [SO question](https://stackoverflow.com/questions/48684270/how-to-exclude-default-material-icons-from-xamarin-android-apk) but since nobody didnt answer. i wasnt sure if it is bug or not.

**Comment by EmilAlipiev** [comment]
@JonDouglas  quick quesion please. I tried to use keep.xaml in xamarin android project but whatever I tried, it doesnt seem to work. Is it not implemented yet?

**Comment by JonDouglas** [comment]
@EmilAlipiev I do not believe we support advanced build merging like a `keep.xml` file in MSBuild, specifically the `tools:discard`. It would be in your best interest to create a new issue outlining the use-case. For best practices on filing an issue, please see the following documentation: 

https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests
