### ISSUE TITLE
Recent .vsix files produced by OSS PR builds are missing files

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1401]
Recent .vsix files are missing a `$ReferenceAssemblies` directory entirely.

### Steps to Reproduce

1. Download and unzip (or install) a PR build vsix (e.g. https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/2672/Azure/ ).

### Version Information
PR #1356 / 8.3.99.43_HEAD_3a60f76

### Log File
vsix content, missing ref assemblies:
https://gist.github.com/pjcollins/3def2556837fc42cb9690ab444c40405

**Comment by jonpryor** [comment]
Hypothesis: the problem is [this line](https://github.com/xamarin/xamarin-android/commit/328286b7136a5a020701143b943594357e94f7ef#diff-de17f877458ffd93904b41b14d99ea95R64):

```xml
<ReferenceAssemblies Remove="$(LibDir)xbuild-frameworks\%(_SymLinks.Identity)\**\*.*" />
```

If `$(LibDir)\xbuild-frameworks\.__sys_links.txt` doesn't exist -- which is the case when building with `xbuild` -- then `@(_SymLinks)` will be *empty*, in which case this is interpolated as the *empty string*, which means all `@(ReferenceAssembly)` entries are *removed*.

Which is what we observe.
