### ISSUE TITLE
Encountering crash due to a SIGILL in System.Numerics.Tests.GenericVectorTests.LessThanOrEqualInt64 when running on an x86 Android device 

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#1448]
I'm encountering a SIGILL when running the new XUnit tests added to XA in 15.7 on an x86 device. I can not reproduce this crash when I run on an x86 emulator however. I am seeing this crash after building and deploying the suite in multiple project configurations (Debug, Release + AOT + LLVM).

### Steps to Reproduce

1.  Download prebuilt .apk file, and run it on an x86 device:
> adb install 15-7-aotllvm-Xamarin.Android.Bcl_Tests-Signed.apk
> adb shell am instrument -w Xamarin.Android.Bcl_Tests/xamarin.android.bcltests.XUnitInstrumentation

### Details
Link to .apk file - https://microsoft-my.sharepoint.com/:u:/p/pecolli/EYrN-tuwhJFJmkrnwj5vAgIBzEQFPGZkCUcmSkNMJUYMUg?e=LBt3gv
Link to obj output - https://microsoft-my.sharepoint.com/:u:/p/pecolli/EXGoMM2LZURMhg8mPY8IUyoBgDudDiDsjXrLA86zaPjHSQ?e=3YL4a8

### Version Information
Windows 10 w/ VS 15.7
Xamarin.Android SDK 8.3.0.5 (HEAD/1a8ed5388)

### Log File
Dell Venue 8 3830 v4.4.2 (x86) - http://xqa.blob.core.windows.net/gist/log-d7615b087eff4a3ebdbec837e357ad1d.txt

**Comment by grendello** [comment]
I don't think this bug is a blocker for the upcoming release:

**Problem area:** AOT/JIT code generator. The issue appears to be an invalid operand used in a machine operation (`ILL_ILLOPN`) which suggest invalid machine code being generated by JIT and AOT (based on OP the issue manifests itself in both full-JIT and AOT modes)

**Regression status:** unlikely. The problems are merely surfaced by addition of the new tests, thus it is reasonable to assume the underlying issue was present in previous releases as well

**Severity:** high. Code generators should output valid code for the target machine.

**Impact:** moderate. Following from *regression status* above, the issue most likely existed before and affected only applications which

  * Use System.Numerics
  * Run on x86 devices

x86 devices aren't very common in Android world and thus the impact area remains small. However, nature of the issue suggests a problem with the JIT/AOT code generator and thus the `moderate` impact assessment.

**Comment by pjcollins** [comment]
I'm going to remove the d15-7 milestone.

**Comment by pjcollins** [comment]
Looping in @vargaz on this AOT related issue as well.

**Comment by pjcollins** [comment]
I'm no longer able to reproduce this using d15-8.
