### ISSUE TITLE
INSTALL_FAILED_INVALID_APK: Package couldn't be installed base.apk code is missing.

### ISSUE THREAD

**Issue by MohdTalhaAnsari** [xamarin/xamarin-android#1461]
### Steps to Reproduce

1. Go to android project properties.
2.  Select Android Options.
3. Set Linking SDK assemblies.  
4. Run on android.

### Version Information
Android Target Platform 8.1 
Minimum OS Version 4.4
Build Tool 27.0.3
Platform Tools 27.0.1
SDK Tools 25.2.5
Xamarin 4.9.0.749

### Log File
[Output-Build.txt](https://github.com/xamarin/xamarin-android/files/1838179/Output-Build.txt)

**Comment by dotMorten** [comment]
I'm hitting this too now

**Comment by ilkeSylmz** [comment]
I have the similar issue with Visual Studio 2019 16.4.2. It could be reproduced without performing step 2 and 3.

**Comment by gsgou** [comment]
I also experience this since last update to newest stable in VS for Mac:

=== Visual Studio Community 2019 for Mac ===
Version 8.5 (build 3183)
Package version: 608000123
=== Mono Framework MDK ===
Runtime:
	Mono 6.8.0.123 (2019-10/1d0d939dc30) (64-bit)
	Package version: 608000123
=== Roslyn (Language Service) ===
3.5.0-beta4-20125-04+1baa0b3063238ed752ad1f0368b1df6b6901373e
=== NuGet ===
Version: 5.4.0.6315
=== Xamarin.Android ===
Version: 10.2.0.100 (Visual Studio Community)
Commit: xamarin-android/d16-5/988c811
SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2
Build Information: 
Mono: c0c5c78
Java.Interop: xamarin/java.interop/d16-5@fc18c54
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b
=== Microsoft Mobile OpenJDK ===
Java SDK: /Users/giorgos/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
=== Android SDK Manager ===
Version: 16.5.0.39
Hash: 6fb4c79
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:25:56 UTC
=== Android Device Manager ===
Version: 16.5.0.71
Hash: 49194e8
Branch: remotes/origin/d16-5
Build date: 2020-02-20 23:26:18 UTC
=== Operating System ===
Mac OS X 10.15.3
Darwin 19.3.0 Darwin Kernel Version 19.3.0
    Thu Jan  9 20:58:23 PST 2020
    root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

**Comment by gsgou** [comment]
Could workaround it by **downgrading to**
**Xamarin.Android 10.1** 
https://aka.ms/xamarin-android-commercial-d16-4-macos
**Mono 6.6.0**
https://download.mono-project.com/archive/6.6.0/macos-10-universal/MonoFramework-MDK-6.6.0.macos10.xamarin.universal.pkg

**Comment by eli191** [comment]
I have the same issue after installing the newest VS for Mac. I am not able to resolve it for the moment.

**Comment by WouterStraver** [comment]
I'm having this issue aswel with the newest version for Mac.

**Comment by hyokosdeveloper** [comment]
same here.

**Comment by maxveldink** [comment]
I was seeing the same issue after upgrading to the latest VS for Mac.

For us, the solution was to go to Options on the Android project, then on the Android Build tab on the left, unselect Enable Multi-Dex and select d8 as our Dex Compiler.

We weren't targeting below API 21, and d8 appears to be the default compiler in Android Studio since 3.1, so I didn't see any downside altering these settings.

Hope that helps someone else. I am curious as to why the latest version caused this though.

**Comment by brendanzagaeski** [comment]
For anyone seeing this after the update to the new versions from this month, it sounds like a new different issue has appeared compared to the original problem reported back in 2018. If anyone is still seeing this issue on the latest version after a clean rebuild when using any combination of settings for **Enable Multi-Dex**, **Dex Compiler**, and **Code Shrinker** and could collect the diagnostic build output for the build that's giving the bad behavior and attach it on a [new issue](https://github.com/xamarin/xamarin-android/issues/new) so that the team can take a look, that would be perfect. Thanks in advance!

**Comment by camchis** [comment]
Disabling Multi-Dex and selecting d8 as the Dex Compiler fixed the issue for me too

**Comment by brendanzagaeski** [comment]
The recent appearance of this issue can now be tracked on https://github.com/xamarin/xamarin-android/issues/4478. Thanks vravindranath for submitting that! If anyone can collect their diagnostic build output and attach it on https://github.com/xamarin/xamarin-android/issues/4478 so the team can take a look, that would be perfect. Thanks!

**Comment by olegderecha** [comment]
Don't know what exactly causes the issue.
A had several schemes, all could be build and install all of them and once, one didn't want (after what actions - don't know). In all unknown situations I execute:
`npm run mac-reinstall`
where in `package.json` in `scripts` section:
`"mac-reinstall": "rm -rf -v package-lock.json ios/build ios/Podfile.lock android/.gradle android/build android/app/build node_modules && npm i && cd ios/ && rm -rf Pods/ && pod install && cd ../"`
You can try to leave only Android's part from the script.

**Comment by Loopiezlol** [comment]
`$ ./gradlew clean` did the trick for me

I think the build state got in broken state while I stopped a build process midway through
