### ISSUE TITLE
Support D8 for dex file compilation

### ISSUE THREAD

**Issue by cobey** [xamarin/xamarin-android#1469]
D8 is now suggested dex compiler for Android development, with enhanced speed and reduced file sizes. We should aim to support D8 as the dex compiler.

> VS bug [#660386](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/660386)

**Comment by atsushieno** [comment]
There is already a solution for d8. https://github.com/atsushieno/xamarin-android-d8-build

**Comment by cobey** [comment]
@jonpryor for context

We want this to be a default experience within Xamarin.Android. While the solution presented is a fine interim solution, we want the improvements that d8 offers as default for 15.8

**Comment by atsushieno** [comment]
I have added D8 support within xamarin-android itself so that users don't have to install my nuget package independently. Instead, `<AndroidEnableD8>true</AndroidEnableD8>` is required in the app `.csproj`.

I don't think enabling D8 by default at this stage is appropriate. What is doable instead is to add the property above in the default Android app project templates.

**Comment by atsushieno** [comment]
(I mean, added to https://github.com/xamarin/xamarin-android/pull/1489)

**Comment by JonDouglas** [comment]
@atsushieno When can we bump our templates to include the property by default? #1489 is still outstanding, so I would guess 15.9?

**Comment by JonDouglas** [comment]
Closing this issue in favor of https://github.com/xamarin/xamarin-android/issues/2040
