### ISSUE TITLE
Question: Provide release tarballs?

### ISSUE THREAD

**Issue by wjk** [xamarin/xamarin-android#1484]
I would like to be able to download a tarball of the OSS source that went into a specific point release of Xamarin.Android as documented on [releases.xamarin.com](https://releases.xamarin.com/). Xamarin.Mac uses git tags to accomplish this (but see also xamarin/xamarin-macios#3820). I am interested in building and reusing the MIT-licensed OSS code in this repository in one of my own products, but without a way to build (or download already built) binaries, I cannot do this.

**Comment by brendanzagaeski** [comment]
Cross-referencing note for the Xamarin.Android team: Unfortunately, it looks like the GitHub mechanism that automatically generates tarballs based on Git tags would not by itself provide useful tarballs for xamarin-android because the tarballs wouldn't have a way to restore the Git submodules. See <https://github.com/xamarin/xamarin-macios/issues/3820#issuecomment-377051261>.

**Comment by jonpryor** [comment]
> I would like to be able to download a tarball of the OSS source that went into a specific point release

An added complication here is that *we don't build everything from source*. Many of our dependencies come in via NuGet packages, e.g. [`src/Xamarin.Android.Build.Tasks` depends on *16* NuGet packages](https://github.com/xamarin/xamarin-android/blob/7800139cd6292c6ebe2c76ea656786508968784c/src/Xamarin.Android.Build.Tasks/packages.config), which are not built from source.

Thus, what should a "tarball of the OSS source" do with the above (and other!) dependencies? Include *their* source? (Would be wonderful, but there's no straightforward way to do this, afaik.) Include the binaries?

> I am interested in building and reusing the MIT-licensed OSS code in this repository in one of my own products, but without a way to build (or download already built) binaries, I cannot do this.

I don't understand what you're asking here.

We could -- should! -- use git tags to associate a xamarin-android commit with the commercial Xamarin.Android release it was used in. (For example, Xamarin.Android 8.2 released as part of [Visual Studio 15.6.3](https://releases.xamarin.com/service-release-15-6-3/) is commit 3d390c0. *I* can determine this, but *external* people can't, so we should *absolutely* tag our releases appropriately.)

Once a commit/tag is known, you can hit the appropriate Jenkins job -- in this case the [xamarin-android-d15-6](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d15-6/) job -- and find the build for the associated commit, in this case <https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d15-6/28/>. The [**Azure Artifacts**](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d15-6/28/Azure/) link contains binaries, which allows downloading an OSS-*only* `.zip` file of the build tree:

<https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d15-6/28/Azure/processDownloadRequest/xamarin-android/oss-xamarin.android_v8.2.0.25_Darwin-x86_64_HEAD_3d390c0.zip>

Documentation here is quite lacking, but is that otherwise satisfactory for "download[ing] already built" binaries?

We *do* provide [documentation on how to use those Jenkins build artifacts](https://github.com/xamarin/xamarin-android/blob/7800139cd6292c6ebe2c76ea656786508968784c/Documentation/workflow/JenkinsBuildArtifacts.md).

**Comment by wjk** [comment]
@jonpryor That's perfect; your directions for locating build tree artifacts given a commit was just what I was looking for. Thanks!
