### ISSUE TITLE
[Designer] Broken MSBuild logic

### ISSUE THREAD

**Issue by garuma** [xamarin/xamarin-android#1501]
The following two commits:
 - https://github.com/xamarin/xamarin-android/commit/e55d6557f6a273a21be3cf72893f12a86f1ec359
 - https://github.com/xamarin/xamarin-android/commit/e824170632e0b9115ee65d9dc07c41fa3b8907b6

Broke the designer target `GetExtraLibraryLocationsForDesigner` because the first redefines the path of the cache file `_AndroidResourcePathsCache` and the second prevents that path from ever being created.

> VS bug [#594873](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594873)

**Comment by dellis1972** [comment]
@garuma can you provide in on how you are calling these targets? (i.e which parameters you provide) I would like to replicate this environment in our tests so we don't break you again.

**Comment by garuma** [comment]
I was using MyDriving (https://github.com/Azure-Samples/MyDriving/tree/master/src/MobileApps) as a test-bed (see referenced commit in the issue) that has both type of library dependencies since it uses older support package nugets.

`GetExtraLibraryLocationsForDesigner` is only called with `DesignTime` set to true, I think this should also be affecting other design-time targets like managed resgen if that's easier to test.

**Comment by dellis1972** [comment]
@garuma just so you know, we had to redefine the cache files for the design time builds. Otherwise it caused all sorts of build problems. I think the designer is in this weird limbo, where you need a full build but you run in a design time mode... The problem is one of those commits fixes a VS hang.

Not sure how to fix this at the moment, both of the referenced commits are needed.. 
We might need to provide an additional parameter "DesignerBuild" or something so we can do the things the designer needs.

**Comment by garuma** [comment]
I don't see how the two areas the two commits change are needed at the same time though:
 - Either the cache file is different for design-time builds and it's built on-demand when it's actually needed (like in our case)
 - Or the cache generation is disabled in design-time builds and it tries to read the full-build cache file if available and doesn't do anything if it doesn't exist
