### ISSUE TITLE
Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by ronalsilva** [xamarin/xamarin-android#1554]
### Description
hi guys, I'm with one probleme, my project is with this error  "Could not create the Java Virtual Machine."

### Basic Information

- VS 17
- Windows 10
- Xamarin forms

![capturar](https://user-images.githubusercontent.com/9373434/38741898-70e202fc-3f11-11e8-8e5c-1ddaf28c078a.PNG)

**Comment by jonpryor** [comment]
Do you have JDK 9 installed? If so, please ensure 1.8 is installed and the IDE is configured to use it.

**Comment by ronalsilva** [comment]
I have JDK 8, have any difference ?

**Comment by jonathanpeppers** [comment]
@ronalsilva can you post a screenshot of your Java settings?

These should all have green checkmarks:

![image](https://user-images.githubusercontent.com/840039/41938045-963eaf52-7957-11e8-9b76-cb52d94d3720.png)

_NOTE: you only need the NDK if you plan to use AOT/LLVM/etc._

Closing for now, as I feel like your issue is related to your Java installation/Xamarin settings in VS. Feel free to reopen if you get more info and think it's a bug, thanks!
