### ISSUE TITLE
Sometimes (often) I get random build errors

### ISSUE THREAD

**Issue by mathiasnielsen** [xamarin/xamarin-android#1643]
### Steps to Reproduce

1. Simply building the project

### Expected Behavior

Show no errors.

### Actual Behavior

I mostly get errors such as 

- "No resource found that matches the given name:..."
- "The type or namespace name "Some namespace name" does not exist in the namespace 'Namespace such as Android"
- The "ResolveLibraryProjectImports" task failed unexpectedly.

I can manage to get it to work if I do stuff like; 

- clean solution
- rebuild solution
- delete 'bin' and 'obj'
- restarts visual studio
- run a "git clean -xdf" for removing untracked files for the working tree

... but not always does it do the trick for me.

I am currently working on a rather big project, and the build time varies from 2min to 6min - and since the build is mostly "not successfull", I try this 2-5 times, which is rather time consuming and boring.

### Version Information

Operating System
Mac OS X 10.13.1
Darwin 17.2.0 Darwin Kernel Version 17.2.0
    Fri Sep 29 18:27:05 PDT 2017
    root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

Visual Studio for MAC 7.4.3 (build 10)

Xamarin.Mac
Version: 4.2.1.29 (Visual Studio Enterprise)

Xamarin.iOS
Version: 11.9.1.24 (Visual Studio Enterprise)
Hash: f62de472
Branch: xcode9.3
Build date: 2018-03-29 19:30:53-0400

Xamarin.Android
Version: 8.2.0.16 (Visual Studio Enterprise)
Android SDK: /Users/Kirkegaard/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.0.3 (API level 15)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)
		8.0   (API level 26)
		8.1   (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 27.0.1
SDK Build Tools Version: 28.0.0 rc1

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

### Log File
N/A

**Comment by JonDouglas** [comment]
Although there are multiple areas involved in this issue, we have been working to improve these scenarios:

- Use Shared Runtime not deploying changes
- Incomplete Intellisense
- Resources not being found although exist locally
- `ResolveLibraryProjectImports` failing
- Delete `bin/obj` folders as a workaround

Though we would love for all of these problems to be fixed in a single release, we hope that you incrementally see improvements in each of these areas. If at anytime you run into a specific issue in these areas, please report a new issue. Thank you all for being patient while we work to improve Xamarin.Android.

**Comment by jonathanpeppers** [comment]
Closing for now, since we haven't heard back on this for a while. @mathiasnielsen feel free to comment/reopen if you are seeing similar problems in the latest stable right now (VS 15.9, Xamarin.Android 9.1), thanks!
