### ISSUE TITLE
SIGSEGV in Skia on specific device

### ISSUE THREAD

**Issue by luhenry** [xamarin/xamarin-android#1791]
### Steps to Reproduce

1. Download https://github.com/luhenry/CrashGPS/tree/newcrash and open solution file from `GPS.Kernel.Project.Xamarin`
2. Launch on dedicated device
3. Click on any of the button

### Expected Behavior

It doesn’t crash. The _equivalent_ Java app (available in `GPS.Kernel.Project.Java`) properly shows the components without crashing.

### Actual Behavior

It does crash.

### Version Information

It only crashes with a very specific device. It is being shipped to @jonpryor so he can take a look. It also crashes with latest XA stable and doesn’t seem to be version specific.

### Log File

The stacktrace appears to be in Skia, even if SkiaSharp is not in use.

 _coming soon_

**Comment by jonpryor** [comment]
The https://github.com/luhenry/CrashGPS/tree/jonp-check-pngs branch has some additional changes to simplify the test case.

The crash is within `libskia.so`, when processing an on-device `.9.png` resource which contains [`PLTE` (Palette)](https://www.w3.org/TR/PNG-Chunks.html#C.PLTE) and [`tRNS` (Transparency)](https://www.w3.org/TR/PNG-Chunks.html#C.tRNS) chunks.  For example, with the updated sample, launch the app and then tap the **Edit Text** button; the app will then crash:

```
backtrace:
    #00  pc 00000000  <unknown>
    #01  pc 0009f7bb  /system/lib/libskia.so (SkBitmapProcShader::shadeSpan(int, int, unsigned int*, int)+84)
    #02  pc 000a79d7  /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+406)
    #03  pc 000d1081  /system/lib/libskia.so
    #04  pc 000d1163  /system/lib/libskia.so (SkScan::FillIRect(SkIRect const&, SkRegion const*, SkBlitter*)+222)
    #05  pc 000d1229  /system/lib/libskia.so (SkScan::FillRect(SkRect const&, SkRegion const*, SkBlitter*)+136)
    #06  pc 000d1315  /system/lib/libskia.so (SkScan::FillRect(SkRect const&, SkRasterClip const&, SkBlitter*)+52)
    #07  pc 000b1cff  /system/lib/libskia.so (SkDraw::drawRect(SkRect const&, SkPaint const&) const+216)
    #08  pc 0009e09b  /system/lib/libskia.so (SkBitmapDevice::drawBitmapRect(SkDraw const&, SkBitmap const&, SkRect const*, SkRect const&, SkPaint const&, SkCanvas::Dra
lags)+590)
    #09  pc 000ac23f  /system/lib/libskia.so (SkCanvas::internalDrawBitmapRect(SkBitmap const&, SkRect const*, SkRect const&, SkPaint const*, SkCanvas::DrawBitmapRectFl

    #10  pc 0007ba21  /system/lib/libandroid_runtime.so (NinePatch_Draw(SkCanvas*, SkRect const&, SkBitmap const&, android::Res_png_9patch const&, SkPaint const*, SkReg

    #11  pc 0007b4b1  /system/lib/libandroid_runtime.so
    #12  pc 0002034c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
    #13  pc 00050fcf  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
    #14  pc 000297e0  /system/lib/libdvm.so
    #15  pc 00030c6c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
    #16  pc 0002e304  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
    #17  pc 00063715  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
    #18  pc 0006b61b  /system/lib/libdvm.so
    #19  pc 00052975  /system/lib/libdvm.so (dvmResolveNativeMethod(unsigned int const*, JValue*, Method const*, Thread*)+116)
    #20  pc 000297e0  /system/lib/libdvm.so
    #21  pc 00030c6c  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
    #22  pc 0002e304  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
    #23  pc 00063431  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
    #24  pc 0004cbb7  /system/lib/libdvm.so
    #25  pc 0004dfcb  /system/lib/libandroid_runtime.so
    #26  pc 0004ecf7  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*, bool)+358)
    #27  pc 00001063  /system/bin/app_process
    #28  pc 0000e4ab  /system/lib/libc.so (__libc_init+50)
    #29  pc 00000d80  /system/bin/app_process
```

The simplified sample works by using an [`<ImageView/>`](https://github.com/luhenry/CrashGPS/blob/jonp-check-pngs/GPS.Kernel.Project.Xamarin/KernelProject/KernelProject.Android/Resources/layout/activity_edittext.xml#L10-L14) which uses an image that comes from the Android support library.

*What* image it uses isn't as important as what *has been done* to the image; the `abc_list_selector_disabled_holo_dark.9.png` resource from the support library is a nine-patch file which must be processed at build time.  When processed by the normal Java toolchain, the resulting file does not contain the `PLTE` or `tRNS` chunks; when processed by the normal Xamarin.Android toolchain, the resulting file *does* contain the `PLTE` and `tRNS` chunks.  If you alter the app so that it instead uses Java toolchain outputs, the app does not crash.

Alternatively, if the Xamarin.Android build process is updated so that the `PLTE` and `tRNS` chunks aren't generated, the app does not crash.  This can be done by setting the `$(AndroidExplicitCrunch)` MSBuild property to True, or -- with Xamarin.Android 9.0 -- by using `aapt2` by setting `$(AndroidUseAapt2)`=True.

There's a "funny" thing about the `.9.png` processing, though: *Both* Xamarin.Android *and* Java use  `aapt`/`aapt2` for png-crunching.  The difference is that Java *always* separately crunches nine-patch files; that's optional under Xamarin.Android (default is for `$(AndroidExplicitCrunch)`=False) because we've had some stability issues when it is enabled by default.  By default, Xamarin.Android has the `aapt` tool perform png-crunching as part of normal processing, and in this context `aapt` emits the `PLTE` and `tRNS` sections.

Rephrased: in one codepath `aapt` emits `PLTE` and `tRNS` chunks; in another codepath, it doesn't.  *It's the same tool either way*, but it's output differs.  There appears to be an [Android SDK `aapt` tool bug](https://issuetracker.google.com/issues/36988953) for this issue, but -- as per experience with this bug -- the fix only appears to be used when using `aapt crunch` or `aapt singleCrunch`, and *not* `aapt package`.

*Ultimately*, though, I believe that this is a bug in the `libskia.so` which is on-device: the presence of `PLTE` and `tRNS` sections shouldn't cause it to break, yet it does, and we do not see this crash on any other devices.

This Skia crash looks like [Skia issue 3820](https://bugs.chromium.org/p/skia/issues/detail?id=3820#c9):

>     We also have one crash report that points to this bug.
>
>     Build fingerprint: 'lge/luv50ds_global_com/luv50ds:4.4.2/KOT49I/1448509221:user/release-keys'
>     pid: 6638, tid: 6895, name: HighPriority-Th  >>> com.snapchat.android <<<
>     signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000000
>         r0 5c739860  r1 5c738b28  r2 00000066  r3 5d7ccd80
>         r4 00000066  r5 00000066  r6 5d7ccd80  r7 5c739860
>         r8 00000000  r9 00000000  sl 000000fe  fp 4070954c
>         ip 00000000  sp 5c738b18  lr 405790f8  pc 00000000  cpsr 600b0010
>     
>     backtrace:
>         #00  pc 00000000  <unknown>
>         #01  pc 0009d0f4  /system/lib/libskia.so (SkBitmapProcShader::shadeSpan(int, int, unsigned int*, int)+160)
>         #02  pc 000ac694  /system/lib/libskia.so (SkARGB32_Shader_Blitter::blitRect(int, int, int, int)+504)
>         #03  pc 000fcf08  /system/lib/libskia.so (SkScan::FillIRect(SkIRect const&, SkRegion const*, SkBlitter*)+368)

That might be somewhat moot, though, as `SkBitmapProcShader::shadeSpan()` no longer exists in Skia; it was removed on [2014-April-23](https://skia.googlesource.com/skia/+/bc2f1dc85e458af7bdb87873e60207f9f7299e4a), "renamed" to `SkBitmapProcShader::BitmapProcShaderContext::shadeSpan()`, and the [`SkBitmapProcShader::BitmapProcShaderContext` type has *also* since been removed](https://skia.googlesource.com/skia/+/05a5647efed7fcbcc5bd1efa445a6a3ab445a6c3%5E%21/), which is a further indication of *just how old* the `libskia.so` on this device is.

Given that the sample app only fails on this particular dedicated device (with a `libskia.so` dating to 2015-Dec-11!), and no other API-19 devices have a similar crash, I believe that this is a device-specific Skia bug and that the Skia on this device should be fixed.  Xamarin.Android-side build system fixes are *workarounds*.
