### ISSUE TITLE
Unreliable build failures with non-obvious reason

### ISSUE THREAD

**Issue by atsushieno** [xamarin/xamarin-android#1795]
Today I keep suffered from unreliable build failures and it turns out it's all build scripts fault.

```
"/sources/xamarin-android/Xamarin.Android.sln" (default target) (1) ->
"/sources/xamarin-android/src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj" (default target) (33) ->
(_SetLatestTargetFrameworkVersion target) -> 
  /sources/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(665,2): error MSB4018: The "ResolveSdks" task failed unexpectedly. [/sources/xamarin-android/src/Xamarin.Android.NUnitLite/Xamarin.Android.NUnitLite.csproj]
```

This is all caused by unreliable Azure file hosting:

```
/sources/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.targets(75,5): warning : Unable to download URL `https://xamjenkinsartifact.azureedge.net/xamarin-android/xamarin-android/bin/Debug/bundle-v21-hce3edcfc-Debug-Linux-libzip=b95cf3f,llvm=bdb3a11,mono=6f9bef3.zip` to `/home/atsushi/android-archives/bundle-v21-hce3edcfc-Debug-Linux-libzip=b95cf3f,llvm=bdb3a11,mono=6f9bef3.zip`: 404 (Not Found) [/sources/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.csproj]
```

What to do here:

- Fix build scripts so that it immediately fails when downloads are not available.
  - Or make it somewhat optional by providing "continue on error" flag.
- Make downloads more trustable?

I also noticed that it should never try to download mono when its commit hash points to local changes. We need that when our changes involve changes to mono/mono and sending PRs in parallel.

Make them developer friendly.

**Comment by xtmq** [comment]
Good time, any update here? 
I am trying to build xamarin android on windows but can not find a revision with working bundle. Constantly have the next error:
>  warning : Unable to download URL `https://xamjenkinsartifact.azureedge.net/xamarin-android/xamarin-android/bin/Debug
/bundle-v21-he285ced0-Debug-Darwin-libzip=b95cf3f,llvm=bdb3a11,mono=e613a64.zip` to `C:\Users\evgeniy.stepanov\android-archives\bundle-v21-he285ced0-Debug-Darwin-libzip=b95cf3f,llvm=bdb3a11,mono=e613a64.zip`: Res
ponse status code does not indicate success: 404 (Not Found). [D:\Solutions\Xamarin\xamarin-android\build-tools\download-bundle\download-bundle.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.

**Comment by jpobst** [comment]
I think `xa-prep-tasks` has been replaced by `xaprepare`, so this issue is obsolete.

`build-tools/xa-prep-tasks/xa-prep-tasks.targets` no longer exists.
