### ISSUE TITLE
WCF Fault Exception Cannot Deserialize FaultDetail

### ISSUE THREAD

**Issue by ShadowNetCoder** [xamarin/xamarin-android#1811]
Hi,

I would like to know how the issue 59318 from Bugzilla is doing (https://bugzilla.xamarin.com/show_bug.cgi?id=59318).

I still have the issue with Visual Studio 2017 15.7.3 and Xamarin.Android v27.0.2.

Best Regards

**Comment by jonathanpeppers** [comment]
Hi @ShadowNetCoder,

Unfortunately, your issue is likely due to a gap in Mono's implementation of WCF...

So what I would try:
1. Create a reproduction project with desktop Mono (MacOS or Linux would likely be the easiest)
1. Stand up a public-facing WCF example service somewhere to show the problem (maybe one exists?)
1. Submit a bug to [mono itself](https://github.com/mono/mono/issues), and include your sample

Or, if at all possible:
1. Don't use WCF, use something more modern such as ASP.NET Web API or whatever they are calling it now...

Feel free to reopen this (sorry!) if you see something pointing toward an issue in Xamarin.Android. Since Xamarin.Android sits on top of Mono, there isn't a lot we can do sometimes for these types of problems.

**Comment by ShadowNetCoder** [comment]
Hi @jonathanpeppers ,

Thank you for your reply, I will process as you adviced.

Best Regards
