### ISSUE TITLE
Unable to get the path of an assembly with Xamarin.Android in release

### ISSUE THREAD

**Issue by TerceraFaseSoftware** [xamarin/xamarin-android#1966]
### Steps to Reproduce

1.  Generate a new Xamarin.Android Project 
2.  Compile and execute the app on release and try to get the location of the second assembly.

![image](https://user-images.githubusercontent.com/37209374/42766079-c6d7e0e4-8919-11e8-8b6f-2c24b3c7b610.png)

![image](https://user-images.githubusercontent.com/37209374/42765992-9231a852-8919-11e8-80ca-0edc7879a96f.png)

As you can see on the first picture, if we execute the program in debug mode, we can get the current path of the assembly without problems. But if we try to execute the same program in release, we only have the name of the assembly.

### Expected Behavior
Gets the current path of the aseembly

### Actual Behavior
Returns only the name of the assembly

### Log File

 Xamarin.Android

**Comment by allsorts46** [comment]
This is an old issue but I just struggled with the same thing and hope this might be useful to others, as the comment above about it being 'expected behaviour' didn't really explain why.

The reason this works in debug mode is not really because of debug mode at all, it's because of the 'fast deployment' option which is usually enabled in the debug configuration. It can be switched off, and then you'll find debug behaves the same as release.

When fast deployment is enabled, the build process actually copies all the assembly files directly to the device into a known location, and they'll be loaded from there at runtime. I didn't look into why this is done, and it doesn't seem to actually make deployment any faster for me, but I'm sure it was meant to aid debugging somehow.

Without this option though, the assemblies stored in the APK file and are not actually extracted onto the file system at runtime. So you can't get the path to the assembly files, because they don't exist.

I did discover that System.Environment.CommandLine appears to contain the path to the APK file, and you do have permission to access this file, and APK files are just zips... so you could possibly read them and extract the desired assemblies into files, then load from there... but at this point it'd be easier to just add the assemblies as embedded resources and extract them that way.

**Comment by jpobst** [comment]
Yes, this is correct:

> ...the assemblies stored in the APK file and are not actually extracted onto the file system at runtime. So you can't get the path to the assembly files, because they don't exist.
