### ISSUE TITLE
AutoCompleteTextView events not works if we use SetFoucusable method

### ISSUE THREAD

**Issue by varunbabus** [xamarin/xamarin-android#2002]
I am using AutocompleteTextView control in one of the Fragment. The user will be allowed to search and copy/paste/select all on long clicking the autocomplete. By default, it is not working. To support Copy/Paste/SelectAll we have added

**SetFocusable(ViewFocusability.Focusable)**

However, If I add the method, the other events like TextChanged and Touch are not working.

var txtSearch = view.FindViewById<AutoCompleteTextView(Resource.Id.txtTextSearch);
txtSearch.SetFocusable(ViewFocusability.Focusable);//Line A: Code used to enable Copy/Paste/SelectAll inside the control.
txtSearch.Touch += (s, e) =>
{
 //not fires if we add Line **SetFocusable(ViewFocusability.Focusable)**
};
txtSearch.TextChanged += async delegate (object sender, Android.Text.TextChangedEventArgs e)
{
 //not fires if we add Line **SetFocusable(ViewFocusability.Focusable)** 
};

Any help would be appreciated?

**Comment by JonDouglas** [comment]
The [issue tracker in this repository is the preferred channel for bug reports, feature requests, and pull requests](https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#using-the-issue-tracker). Since this issue is a question about how to implement `AutoCompleteTextView`, we invite you to post this on a platform such as [Stack Overflow](https://stackoverflow.com/questions/tagged/xamarin.android) or the [Xamarin Community Forums](https://forums.xamarin.com/categories/android) to get help.

If you suspect that this issue is a bug within the Xamarin.Android Framework, please follow our new issue template to provide a complete [Bug Report](https://github.com/xamarin/xamarin-android/wiki/Submitting-Bugs,-Feature-Requests,-and-Pull-Requests#bug-reports).

**Comment by jonathanpeppers** [comment]
@varunbabus I would follow @JonDouglas' suggestion to post elsewhere.

Closing for now. Feel free to reopen if you think there is a bug in Xamarin.Android here, thanks!
