### ISSUE TITLE
Generate Aapt2 .flata archives on Nuget Restore.

### ISSUE THREAD

**Issue by dellis1972** [xamarin/xamarin-android#2101]
To help speed up initial build times we should investigate generating the `aapt2` flata archives for support library components when the components are restored. 

We should also look again and ways we can cache these archives (with the appropriate aapt2 version) so that they can be reused across a number of projects.

**Comment by dellis1972** [comment]
Need to figure out which Nuget target to hook into for this to work.

**Comment by kzu** [comment]
One way would be to run a target after `Restore` target. However, that would make the restore itself slower and could be considered a regression.

Alternatively, we can have the IDEs invoke this *after* restore is complete, with the same caveats as the Xamarin.Build.Download: if the process hasn't finished by the time the Build runs, it will be done there and then. (causing a slow-ish build the first time).

Using the same nuget package location would ensure it's properly versioned (i.e. a `%userprofile%\.nuget\packages\xamarin.android.support.v4\27.0.2.1\obj\[BUILD_TOOLS_VERSION]`), so that if users clean the nuget cache, those go away too (with `nuget locals all -clear`).

**Comment by dellis1972** [comment]
I'm going to close this issue as its probably not going to help
