### ISSUE TITLE
XA0105 for System.Data.SQLite when using older TargetFrameworkVersion than latest.

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/xamarin-android#2112]
### Steps to Reproduce

1. File-> New Android Application
2. Set `TargetFrameworkVersion` = 8.1 (Should be current default in templates)
3. Add `System.Data.SQLite` as a reference
3. warning XA0105: The $(TargetFrameworkVersion) for Mono.Data.Sqlite.dll (v9.0) is greater than the $(TargetFrameworkVersion) for your project (v8.1). You need to increase the $(TargetFrameworkVersion) for your project.

### Expected Behavior

No warning

### Actual Behavior

Warning telling the user to update to v9.0

### Version Information

Visual Studio 2017 - 15.8.1

Xamarin.Android - 9.0.0.18

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
