### ISSUE TITLE
[Aapt2] `_CreateAapt2VersionCache` slow due to wildcard usage

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#2121]
### Steps to Reproduce

1. I built the `tests/Xamarin.Forms-Performance-Integration` app
2. Modify a XAML file, build the app again
3. `_CreateAapt2VersionCache` took 181ms, but the values were cached!

I think the problem is due to wildcard usage:
```xml
<ItemGroup>
	<_CompiledFlataArchive Include="$(IntermediateOutputPath)\**\*.flata"/>
	<_CompiledFlataStamp Include="$(IntermediateOutputPath)\**\compiled.stamp"/>
</ItemGroup>
```

Maybe these could be done without using `**`? we have a lot of files in here.

### Expected Behavior

`_CreateAapt2VersionCache` should take near 1ms when things are cached.

### Actual Behavior

`_CreateAapt2VersionCache` is taking ~181ms even when cached.

### Version Information

Was using master as of: https://github.com/xamarin/xamarin-android/commit/0a46788a93e10b6fb68afb12ba350635da2e642c

### Log File

[msbuild.zip](https://github.com/xamarin/xamarin-android/files/2337025/msbuild.zip)

**Comment by dellis1972** [comment]
We should only run the entire target if `Condition="'$(_Aapt2Version)' != '@(_Aapt2VersionCache)'" `. 
But we might need conditions on the ItemGroup entires too, since I believe even if a target is skipped the ItemGroups and Properties are evaluated.

We need the wildcards since we will need to recurse into subfolders like the `lp` ones.. that said. We might be able to optimise by looking at specific sub dirs. So we don't end up going through things like the `android` directory, or the `linksrc` ones

`$(IntermediateOutputPath)\lp\**\*.flata`
`$(IntermediateOutputPath)\*.flata`
