### ISSUE TITLE
AppCompat Resources not found In Xamarin Android

### ISSUE THREAD

**Issue by aixiaozi** [xamarin/xamarin-android#2188]
### Question
I'm trying to access `AppCompat`  resources which usually found under **android.support.v7.appcompat.R**, eg:

```
android.support.v7.appcompat.R.anim.abc_fade_in
```

But in `Xamarin.Android`, all could find under this name space was the `BuildConfig` class:

```
Android.Support.V7.AppCompat.BuildConfig.
```

Can anyone help me figure out how could I access those resources?

### Steps to Reproduce

1. Create a blank Xamarin.Android Project 
2. Install `Xamarin.Android.Support.v7.AppCompat` nuget package
3. Try use `Android.Support.V7.AppCompat` to access `AppCompat` resource.

### Expected Behavior

In Android Studio, we could find AppCompat resource like this:

![image](https://user-images.githubusercontent.com/18043540/45608475-a0715a00-ba85-11e8-8c03-f54df1f911e6.png)

![image](https://user-images.githubusercontent.com/18043540/45608479-aebf7600-ba85-11e8-8ed6-2ed308bf9a89.png)

### Actual Behavior

In VS, 

![image](https://user-images.githubusercontent.com/18043540/45608497-d31b5280-ba85-11e8-88fe-1a8645719771.png)

![image](https://user-images.githubusercontent.com/18043540/45608506-e2020500-ba85-11e8-8c60-8aa79d6d3213.png)

### Version Information

VS 2017 version: 15.8.4

Xamarin.Android.Support.v7.AppCompat version: 27.0.2.1

**Comment by aixiaozi** [comment]
I found it! We could find these AppCompat resources under `Resource` namespace, eg:

```
Resource.Animation.abc_fade_in

or

yourprojectname.Resource.Animation.abc_fade_in
```

Which in native android is:

```
android.support.v7.appcompat.R.anim.abc_fade_in
```

**Comment by JonDouglas** [comment]
Native Android development uses the concept of `R.java`. We expand upon this by naming it `Resource`. You can read more about this here: 

https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/android-resource-basics

You can learn more about the underlying item by looking up how `R.java` works, or how `Resource.Designer.cs` works:

https://stackoverflow.com/questions/40451758/can-someone-actually-explain-the-workings-of-resource-designer-cs

I am closing this issue since you found a resolution to your problem! Let us know if you have any questions.
