### ISSUE TITLE
Documentation about when to use JavaCast<>() versus when not to use

### ISSUE THREAD

**Issue by nbevans** [xamarin/xamarin-android#2241]
**This isn't a bug report necessarily - it is more a question and inviting discussion**

### Steps to Reproduce

1. Try to "C# cast" an `AlertDialog`'s `ListView`.`Adapter` to `IFilterable` (I'm sure the types involved here are somewhat superfluous specification to the _actual_ problem, but bear with me)
2. In `RELEASE` builds this throws an `InvalidCastException` but in `DEBUG` builds it works fine.
3. Replace the "C# cast" with a `.JavaCast<>()` instead and the problem goes away (i.e. works fine in both `DEBUG` and `RELEASE` builds)

### Expected Behavior
This should work consistently between `DEBUG` and `RELEASE` builds:

```
(IFilterable)dialog.ListView.Adapter
// should not throw InvalidCastException - not in an ideal world anyway
```

### Actual Behavior
The code must in newer releases of Xamarin.Android be tweaked as follows in order to work consistently between `DEBUG` and `RELEASE` builds:

```
dialog.ListView.Adapter.JavaCast<IFilterable>()
// works consistently between debug and release builds - good - but why?
```

---

Obviously, having worked with Xamarin since its inception, I am aware of the Xamarin Linker and the effects this can have between `DEBUG` and `RELEASE` builds. But usually linker issues manifest themselves differently, such as missing types, or reflection issues. I have never seen it manifest as a `InvalidCastException` before.

I also note that the "C# cast" style *was* working fine for a long time for us but only recently has stopped working - I am not actually sure _when_ i.e. what version of Xamarin.Android though.

I have known about `JavaCast<>()` for a long time - and have sometimes used it when it was apparent that it was the only way to make something work even in `DEBUG` builds. But I have never found any good documentation that describes when its usage is critical, versus when a normal C# cast might be safe to use.

**Comment by radekdoulik** [comment]
Could you try to set the linker mode to `None` in the release configuration to see whether it is linker issue?

Do you have Proguard enabled in your Release configuration?

**Comment by grendello** [comment]
@nbevans Some explanation (not enough) is provided in the Remarks section here https://developer.xamarin.com/api/member/Android.Runtime.Extensions.JavaCast%3CTResult%3E/

**Comment by nbevans** [comment]
I have read that several times over when debugging my issue, and whilst it vaguely seems to cover what I experienced - I still feel unsatisfied as though I don't yet fully understand the behaviour I saw? Especially considering it was working fine for a long time and then the C# cast stopped working and the JavaCast became mandatory.

I didn't try turning the Linker off on my RELEASE build.

I don't have Proguard enabled on any of my builds.

**Comment by jonpryor** [comment]
@nbevans: There *shouldn't* be such critical behavior between Debug and Release builds.  This strongly suggests a linker bug, which is why @radekdoulik requested that you try again with the linker disabled, to confirm-or-deny that hypothesis.

The *only* time you should need `.JavaCast<T>()` is when:

 1. The C# compiler requires a cast, *and*
 2. You have reason to believe that there is a "binding mismatch" between the runtime .NET type and the runtime Java type, and you're asserting that -- regardless of what the binding has -- the underlying Java instance implements the Java type.

For example, [`android.text.method.PasswordTransformationMethod `](https://developer.android.com/reference/android/text/method/PasswordTransformationMethod) implements [`android.text.TextWatcher `](https://developer.android.com/reference/android/text/TextWatcher), but [our binding of `Android.Text.Method.PasswordTransformationMethod` *removes* the `ITextWatcher`](https://github.com/xamarin/xamarin-android/blob/ca4283248ac7b28adbbf30f9216c815499883f05/src/Mono.Android/metadata#L455).  Consequently, this doesn't work:

```csharp
Android.Text.ITextWatcher watcher = new Android.Text.Method.PasswordTransformationMethod ();
// error CS0266: Cannot implicitly convert type 'Android.Text.Method.PasswordTransformationMethod' to 'Android.Text.ITextWatcher'. An explicit conversion exists (are you missing a cast?)
```

A C# cast will just result in an `InvalidCastException`.

However, we *know* that this type implements `ITextWatcher`, and can thus use `.JavaCast<ITextWatcher>()`:

```
// this works:
var watcher = new Android.Text.Method.PasswordTransformationMethod ()
	.JavaCast<Android.Text.ITextWatcher>();
```

The other historical place the need for `.JavaCast<T>()` was when `T` was a type located outside of `Mono.Android.dll`, as type mapping registrations may not have occurred, but that should no longer be needed.

**Comment by jonpryor** [comment]
Additionally, I wasn't able to reproduce the crash in Release builds in my (probably bad) test case:

```csharp
protected override void OnCreate(Bundle savedInstanceState)
{
	base.OnCreate(savedInstanceState);

	// Set our view from the "main" layout resource
	SetContentView(Resource.Layout.Main);

	try {
		var builder = new AlertDialog.Builder (this);
		builder.SetItems (new []{"foo", "bar"}, (o, e) => Console.WriteLine ($"# jonp: clicked! {e.Which}"));
		var dialog = builder.Create();
		var filter = (IFilterable) dialog.ListView.Adapter;
		Console.WriteLine ($"# jonp: success!");
	}
	catch (Exception e) {
		Console.WriteLine ($"# jonp: error: {e}");
	}

	// Get our button from the layout resource,
	// and attach an event to it
	Button button = FindViewById<Button>(Resource.Id.myButton);

	button.Click += delegate { button.Text = $"{count++} clicks!"; };
}
```

**Comment by jonathanpeppers** [comment]
@nbevans can we close this? Or is there still an issue here?

I think @jonpryor was looking for a simple project to reproduce the problem if that is possible?

**Comment by radekdoulik** [comment]
Please reopen if it is still an issue.
