### ISSUE TITLE
Event EditText.KeyPress not called on real devices

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [xamarin/xamarin-android#2243]
**### Steps to Reproduce**

1.  Clone sample issue: https://github.com/Goncharuk-Nikita/KeyPressIssue_NativeDroid (Basic Xamarin.Android Template with EditText)
2.  Put a breakpoint in the KeyPress event handler in MainActivity
![devenv_2018-10-01_09-57-49](https://user-images.githubusercontent.com/30652592/46274018-88f3a000-c560-11e8-8456-a4ec585dcda0.png)

3.  Run it on a real device, not on a simulator or emulator, because it works there.

**### Expected Behavior**

The KeyPress event should be invoked when I enter text using the Android keyboard and the program should stop at a breakpoint.

**### Actual Behavior**

The KeyPress event is not called on real devices, but it works on an emulator or simulator. On real devices, it reacts only to 2 buttons, close / submit

**### Version Information**

Microsoft Visual Studio Community 2017 
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026
Microsoft .NET Framework
Version 4.7.03062

Xamarin   4.11.0.756 (d15-8@b66ff7180)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.221 (a73ca07f7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.13 (373c313)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by grendello** [comment]
Hi @Goncharuk-Nikita! This appears to be an expected behavior. `EditText.KeyPress` is our wrapper [around this API](https://developer.android.com/reference/android/view/View.OnKeyListener#onKey(android.view.View,%20int,%20android.view.KeyEvent)) which specifies that:

    Called when a hardware key is dispatched to a view. This allows listeners to get a chance to respond before the target view.

So on device it will be received only if your input keyboard is a hardware one. Emulators have a "hardware" keyboard so that's why, most probably, you receive it there. To test this theory you might want to write an equivalent program in Java and check whether it behaves in the same way. If not, then there's a bug somewhere in XA code. Should that be the case, please reopen this issue, thanks for reporting!
