### ISSUE TITLE
Xamarin.Android does not support binding redirects

### ISSUE THREAD

**Issue by thisisthekap** [xamarin/xamarin-android#2291]
### Steps to Reproduce

1. Create new project with Visual Studio for Mac 7.6.9 (build 22)
2. Add `app.config` files to both the android and the ios project
3. Build both projects --> everything works fine
4. Make the XML in both app.config files invalid
5. Build both projects --> ios build fails, android build works fine (but should not)

A sample project to reproduce the issue can be found at [thisisthekap/AppConfigIgnoredByXamarinAndroid](https://github.com/thisisthekap/AppConfigIgnoredByXamarinAndroid)

This issue arises both for build using visual studio and for builds using `msbuild` on the bash.

_NOTE by @jonathanpeppers: the core issue here is wanting to put binding redirects in the `app.config` for `SkiaSharp`._

### Expected Behavior

`app.config` seems to be ignored by Xamarin.Android

### Actual Behavior

`app.config` should be used by Xamarin.Android

### Version Information

=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.9 (build 22)
Installation UUID: 6c0fc207-9de0-4094-807a-d55b8a672088
Runtime:
	Mono 5.12.0.309 (2018-02/39d89a335c8) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000309

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.4
	2.1.2
	2.1.1
SDK: /usr/local/share/dotnet/sdk/2.1.402/Sdks
SDK Versions:
	2.1.402
	2.1.302
	2.1.301
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/ckapplmueller/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 27.0.3

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 10.0 (14320.25)
Build 10A255

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.0.0.15 (Visual Studio Enterprise)
Hash: 84552a46
Branch: xcode10
Build date: 2018-09-17 21:54:33-0400

=== Build Information ===

Release ID: 706090022
Git revision: 0a0ba3c4593e9adb1c6ff6324e641036146af376
Build date: 2018-10-05 16:38:51+00
Build branch: release-7.6
Xamarin extensions: f7856b13f2c03a58e08381d3a5970bba18f5c7d7

=== Operating System ===

Mac OS X 10.14.0
Darwin 18.0.0 Darwin Kernel Version 18.0.0
    Wed Aug 22 20:13:40 PDT 2018
    root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

**Comment by jonathanpeppers** [comment]
@thisisthekap do you have an example of how the `.config` file is used at runtime?

Looking at the Xamarin.Android MSBuild targets, it looks like they just copy the files and don't do any validation at compile time (because they don't need to).

Are you getting a runtime exception on Android? Can you give details there?

**Comment by thisisthekap** [comment]
@jonathanpeppers

The app.config file seems to be ignored entirely on android. No error is thrown neither during compile- nor during runtime.

If I break the app.config file of the ios project, the build breaks accordingly.

For our case, app.config is used to give the compiler hints how to resolve dependency conflicts. Therefore, the file is (at least for iOS) definitely read and interpreted before the final binary is created.

**Comment by jonathanpeppers** [comment]
@thisisthekap what are the _contents_ of a working `app.config`? In what context is it used at runtime? I am trying to understand the use-case, and we would need to add a test case that makes sense.

Your example is a blank `app.config` with an XML error, so there isn't anything to _fix_? Thanks!

**Comment by thisisthekap** [comment]
@jonathanpepper I am trying to clarify the issue:

**The Use Case:**

We are using `app.config` to do binding redirects. See an example below:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
           <dependentAssembly>
                <assemblyIdentity name="SkiaSharp" publicKeyToken="0738eb9f132ed756" />
                <bindingRedirect oldVersion="1.59.0.0" newVersion="1.60.0.0" />
            </dependentAssembly>
       </assemblyBinding>
    </runtime>
</configuration>
```

**The Issue:**

We are not able to do the binding redirects for our Xamarin.Android project, because `app.config` is ignored by Xamarin.Android. The special character which is making the xml invalid is emphasizing, that no build error arises. If the same broken `app.config` file is used for out Xamarin.iOS, the build fails as expected.

I am happy to help if further clarification is required.

**Comment by jonathanpeppers** [comment]
> We are not able to do the binding redirects for our Xamarin.Android project

Aha! that sounds like a great title for this issue. (no worries, I can update it) The invalid XML thing is corollary.

So that does leave us in a conundrum:
- `app.config` is loaded from disk _at runtime_ by Windows (likely other platforms) to decide what assembly to load.
- We don't even package the `app.config` file in the APK, because APKs exist on disk _still compressed_. The `app.config` cannot be loaded from the file system... This is the same reason Xamarin.Android doesn't support the `Content` build action.
- Android APKs contain all their assemblies _inside_ the APK, so which ever assembly is there is the one that gets loaded. So depending on the assembly that is there, it either works or it doesn't.

So, first step, would be to check that you are getting the newer 1.60.0 version of SkiaSharp packaged in your APK.

Maybe you could also help us out and provide one of the following?
- A quick sample project? It sounds like there is a NuGet you are using that depends on SkiaSharp, but you want to update SkiaSharp.
- What is the output of your [Android device log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#android-debug-log-output), are you getting an error at runtime?

**Comment by thisisthekap** [comment]
@jonathanpeppers For clarification: We experience no runtime issues.

The point is, that we are getting build warnings, because nuget A requires nuget B in version 1.0, and nuget C requires nuget B in version 1.1. Everything works just fine if nuget B 1.1 is used for both A and C. But still the compiler keeps complaining.

We need to be able to specify the binding redirects in an explicit way, to make sure, that we keep being aware of warnings (including those which are arising because of new dependency resolution issues).

**Comment by thisisthekap** [comment]
@jonathanpeppers Imho it is a bug, that this is not working for Xamarin.Android and it is for Xamarin.iOS. I would not consider this an „enhancement“.

**Comment by SamuelDebruyn** [comment]
Agreed. I need to do a binding redirect for `System.Net.Http` but the `app.config` seems to be completely ignored. I keep getting the build warning telling me to do a binding redirect. According to the logs, this also increases build times.

**Comment by thisisthekap** [comment]
@jonathanpeppers As @SamuelDebruyn and I mentioned, this issue should be considered as bug. Do you have any update on this issue, or an ETA for a possible fix?

**Comment by jonathanpeppers** [comment]
@thisisthekap it would really help us if you could create a sample project showing how you are needing binding redirects to work in your app.

> Maybe you could also help us out and provide one of the following?
> * A quick sample project? It sounds like there is a NuGet you are using that depends on SkiaSharp, but you want to update SkiaSharp. (the sample you have doesn't have SkiSharp or binding redirects in it)

Your project above, basically just had invalid XML for the `app.config`. Can you update it to better show the problem? Thanks!

**Comment by fatfatson** [comment]
+1
need this function!
I'm now loading assembly at run time for some hot-update logic,
but also link that assembly static into the main project,
because I need it to prevent the system API code it called not to be linked away.
without the binding redirects, my dynamic downloaded assembly will be hidden the by the static one.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

Binding redirects are not supported by .NET "Core".
