### ISSUE TITLE
[_ManagedUpdateAndroidResgen] MSBuild target does not properly build incrementally

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#2413]
### Steps to Reproduce

1. Run a design-time build.
2. Future design-time builds seems to always run `_ManagedUpdateAndroidResgen`.

Seems be caused due to a few issues, such as:
```
Building target "_ManagedUpdateAndroidResgen" completely.
Input file "obj\Debug\designtime\resourcepaths.cache" does not exist.
```

It also seems one of the `Inputs` is picked up as `build.props` instead of `designtime\build.props`. It looks like this is happening because `$(_ManagedUpdateAndroidResgenInputs)` is set at evaluation time, and a target changes the MSBuild property from `build.props` to `designtime\build.props`.

### What should we do?

We should refactor and add tests to verify the `_ManagedUpdateAndroidResgen` target builds incrementally.

It will be a bit tricky to get right--which is why I haven't done it yet.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published on Windows that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.2.100.7

Fix included on Windows in Visual Studio 2019 version 16.6 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published on macOS that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.3.0.33.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.6 Preview 1 and higher. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.3.1.0.

Fix included on Windows in Visual Studio 2019 version 16.6. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
