### ISSUE TITLE
AndroidClientHandler does not observe cancellation token correctly in GetAsync()

### ISSUE THREAD

**Issue by Krumelur** [xamarin/xamarin-android#2459]
### Steps to Reproduce

1. Create an Android app
2. Switch HttpClient to use AndroidClientHandler
3. Use HttpClient' GetAsync(url, token) against any existing URL
4. Switch emulator to simulate extremely slow network condition
5. Cancel the token

### Expected Behavior
GetAsync() is passing the token to the underlying the message handler (in this case AndroiClientHandler) that should be observing it. Cancellation is expected to exit the GetAsync() method.

### Actual Behavior
Cancellation won't happen until the request has (successfully) completed.
Using the manage message handler instead will cancel and bail out of GetAsync().

### Version Information
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.6.11 (build 9)
Installation UUID: 8efdc097-fe14-485e-94e6-e5faa2cdbd23
Runtime:
	Mono 5.16.0.220 (2018-06/bb3ae37d71a) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000220

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.2
	2.1.1
	2.0.5
	2.0.3
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
SDK Versions:
	2.1.302
	2.1.301
	2.1.4
	2.0.3
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.16.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.3
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Xamarin.Android ===

Version: 9.0.0.20 (Visual Studio Enterprise)
Android SDK: /Users/rene/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 26.0.0

Java SDK: /usr
Unable to find a $JAVA_HOME at "/usr", continuing with system-provided Java...
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Apple Developer Tools ===

Xcode 10.1 (14460.46)
Build 10B61

=== Xamarin.Mac ===

Version: 5.0.0.0 (Visual Studio Enterprise)
Hash: b40230c0
Branch: 
Build date: 2018-09-27 11:41:37-0400

=== Xamarin.iOS ===

Version: 12.2.1.10 (Visual Studio Enterprise)
Hash: f2a05edd
Branch: d15-9
Build date: 2018-10-31 18:55:57-0400

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 706110009
Git revision: d7cd66f5e3acd3d46ba0b94a0c935378f828bde0
Build date: 2018-10-31 17:17:12+00
Build branch: release-7.6
Xamarin extensions: bc9b985bfcb480b04a208a6d4045adc443a07857

=== Operating System ===

Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Wed Oct 10 23:06:14 PDT 2018
    root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64

**Comment by jonathanpeppers** [comment]
@grendello when you have a chance to look, if you went through `AndroidClientHandler`, there are probably a few places the `CancellationToken` is not setup.

I saw places using `Task.Run`, which I think has an overload for `CancellationToken`: https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.run?view=netframework-4.7.2

**Comment by grendello** [comment]
@jonathanpeppers I know which pieces of code you have in mind, however there shouldn't be any need to pass the cancellation token to those instances because we cancel the request by means of registering a callback with the token itself to abort the connection (see [here](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L333-L336) and https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L411-L416) which then attempt to disconnec the **Java** connection [here](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L326). I'm afraid the disconnection request is ignored/not handled by the Java side.

**Comment by grendello** [comment]
@Krumelur As stated in the previous comment, I think the issue lies within the Java code. The BCL client handler is fully managed so it is fully under our control, with the Java code we can only do our best to let it know that we want to abort the connection (and we do). However, I'll try to reproduce the issue and see if I can find any way around the limitation. I can't promise any time frame except for "as soon as possible", though.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
