### ISSUE TITLE
Android.Telecom.InCallService SetAudioRoute(int route)

### ISSUE THREAD

**Issue by lfarthing** [xamarin/xamarin-android#2472]
This is in reference to #2437 which was marked as closed before having a discussion about it,  I have upgraded to Mono.Android v9.0 however the accepted parameter for VideoQuality is still incorrect. The generated enum doesn't match the values that are required for this method.

https://developer.android.com/reference/android/telecom/CallAudioState

If I wanted to set the audio route as Speaker I would need to pass in an enum that has a value of 8. The correct parameter would be the enum Android.Telecom.CallAudioRoute.

**Comment by jonathanpeppers** [comment]
I think this has likely been wrong since API 23 support was added: https://github.com/xamarin/xamarin-android/commit/85a816243824bd5876c629a287e537e2333d39b3

I can see a few methods we have "enumified":
```
> git grep setAudioRoute
build-tools/enumification-helpers/methodmap.ext.csv:23, android.telecom, InCallService, setAudioRoute, route, Android.Telecom.VideoQuality
build-tools/enumification-helpers/methodmap.ext.csv:26, android.telecom, Connection, setAudioRoute, route, Android.Telecom.CallAudioRoute
```

I think the proper binding would use `Android.Telecom.CallAudioRoute` enum instead of `Android.Telecom.VideoQuality`. We are already doing this for `Android.Telecom.Connection.SetAudioRoute`, so the methods should be the same.

However...

Since this API was shipped, we will have to _add_ an overload using `CallAudioRoute`, and deprecate the old one.

For now you could use workaround such as:
```csharp
//Not ideal
foo.SetAudioRoute ((VideoQuality)CallAudioRoute.Speaker);
```
