### ISSUE TITLE
Visual Studio Community 2019 Preview for Mac can not install xamarin.android 9.1.4.2

### ISSUE THREAD

**Issue by microspaze** [xamarin/xamarin-android#2527]
INFO [2018-12-13 11:40:57Z]: Updater starting download: xamarin.android-9.1.4-2.pkg
ERROR [2018-12-13 11:44:20Z]: Updater download failed: https://download.visualstudio.microsoft.com/download/pr/25eac220-19cc-47b0-b1df-5eaad831089a/873f44bc8311344cf362a9656eda3494/xamarin.android-9.1.4-2.pkg
System.Exception: Checksum mismatch for file '/Users/mark/Library/Caches/VisualStudio/8.0/TempDownload/xamarin.android-9.1.4-2.pkg'. Expected: 'e6f5110abb5c7855ee2bbab91f1c64c7'. Actual: 'e83196bf43d5c8c50eb2ef53be3b2d4e'

**Comment by brendanzagaeski** [comment]
Thanks for the report! This looks like it might have been due to an incomplete or interrupted download. I just ran the Visual Studio 2019 for Mac Preview updater locally and checked the md5sum of the the downloaded Xamarin.Android 9.1.4.2 package. The md5sum of my download matches the expected value in the error message you saw:

```sh
$ md5 /Users/macuser/Library/Caches/VisualStudio/8.0/TempDownload/xamarin.android-9.1.4-2.pkg
MD5 (/Users/macuser/Library/Caches/VisualStudio/8.0/TempDownload/xamarin.android-9.1.4-2.pkg) = e6f5110abb5c7855ee2bbab91f1c64c7
```

Since the checksum matched the expected value in my case, the updater installed the package successfully. If you haven't already resolved this, one idea would be to delete the original corrupted file and re-run the updater to re-download the file. One way to delete the file would be to run the following command in a Terminal.app command prompt:

```
rm /Users/mark/Library/Caches/VisualStudio/8.0/TempDownload/xamarin.android-9.1.4-2.pkg
```

If that does not resolve the issue, then if you get a chance to create a follow-up report via the **Help > Report a Problem**  menu item in the IDE for further investigation by the Visual Studio for Mac updater team, that would be perfect. Thanks in advance!
