### ISSUE TITLE
HttpClient bug on Android emulator

### ISSUE THREAD

**Issue by lander1337** [xamarin/xamarin-android#2569]
### Description
When I try to get SOAP message from service using HttpClient, xml that I read with HttpResponseMessage.Content.ReadAsStringAsync() sometimes(random) is broken, tags miss latters or '>' simbol. Was checking traffic with fiddler, service return valid xml, so the problem some where on HttpClient.    
 
### Steps to Reproduce
0. Use Android emulator
1. Create/use service that return xml.
2. Create app that using System.Net.Http.HttpClient for get info from service.
3. Make request to service, read string from response, and sometimes for some reason this "xml-string" would be broken.

### Expected Behavior
For example, service return:
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://free-web-services.com/soap">
<SOAP-ENV:Body>
        <ns1:addResponse>
            <sum>8</sum>
            <time>0.0002</time>
        </ns1:addResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```
So i expect same xml, when read it from response.

### Actual Behavior
Service return same xml as expected(check with fiddler), but when read it from response i get(sometimes):
```
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://free-web-services.com/soap">
    <SOAP-ENV:Body>
        <ns1:addResponse>
            <sum>8</sum>
            <time>0.0002</time>
        </ns1:addResponse>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope
```
There is no '>' in the end.

### Basic Information
This bug happends in ~30% of request, sometimes it get valid xml. In my example, missing letter is same every time - '>'. Xml's that i get from my service is large(length ~ 200k), it could be missed latter(should be <ComputerID></ComputerID>, i get <ComputerID></ComputeID>). Sorry for bad English. 

- Version with issue: 3.4.0.1008975
- IDE: VS Community 2017 15.9.1
- Platform Target Frameworks: 
  - Android(Emulator): 
    -Work as expected - Android 4.4
    -Bug reporoduce - Android 6.0, Android 7.1, Android 8.1 
- Affected Devices: Face this bug only on emulator(on my devices works properly)

**Comment by lander1337** [comment]
UPD: no matter what type of content inside  HttpResponseMessage.resp.Content, was try to get json, got same problem, missing simbols.

**Comment by EvoPulseGaming** [comment]
On an actual android phone, in release mode, I also have one of two things happen depending on how much I strip out of my project for a repro case to submit:
A: First put/post request will always fail, claiming that "server returned an invalid or unrecognized response. (Flat out lie, as packet capture shows no request was sent"
Any attempt after this will work.
B: Same as above, except as I stripped out more (barebones now) it may or may not happen on the first try, you have to close the app and try again to get the error.
C: As I was stripping it down, there were times I got "unable to send request" error, instead of the A error.

As far as I can tell, I was getting various errors depending on how I isolated the issue. With none of the errors actually making sense.

I'm downloading preview, as there are linker issues supposedly fixed in that

**Comment by EvoPulseGaming** [comment]
Preview fixed it. (so far)

**Comment by jpobst** [comment]
Reported as fixed and no further cases have been reported, closing.
