### ISSUE TITLE
Problems with updating Xamarin.Android.Support.Annotations 28.0.0

### ISSUE THREAD

**Issue by ChristianKleineidam** [xamarin/xamarin-android#2575]
After New Years are over I'm at the office again and started to update the packages of my Xamarin project, that I wrote over the last two months.

I got the error:

    Could not install package 'Xamarin.Android.Support.Annotations 28.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	

Should I do something different to accomodate the error or is it a bug that has to be fixed by xamarin-android?

**Comment by JonDouglas** [comment]
@ChristianKleineidam 

It seems like you are trying to install the Android Support Library into a .NET Framework project. Based on how NuGet Target Framework monikers work, the project you are installing into, must match that inside the NuGet package.

This specific package `Xamarin.Android.Support.Annotations 28.0.0` only has the following targets:

![monikers](https://user-images.githubusercontent.com/1288848/50600344-0be10b00-0e6e-11e9-8312-e47192f76f63.jpg)

Thus it can only be installed against a Xamarin.Android project that has a `TargetFrameworkVersion` of one of these versions of Android (6.0-9.0).

Can you double check that this happens when only using a single project and installing/updating the NuGet package? If you are doing it at the solution level, it will try to install to all projects in the solution.

**Comment by ChristianKleineidam** [comment]
I have an Xamarin Forms App, and at first I installed it to the Android project and the Forms project.
Now, I installed it only to the Android part.
During the installation, Visual Studio 2018 stoped working and after restarting it doesn't load my project anymore.

**Comment by irongut** [comment]
Looking at that error message I would first update Xamarin.Android.Support.v7.AppCompat from 28.0.0-preview8 to 28.0.0.

That may clear the error but if it does not then you need to install Xamarin.Android.Support.Collections 28.0.0 to your Android project only.

I don't see anything in the error message that says you need to install Xamarin.Android.Support.Annotations.

**Comment by jpobst** [comment]
The Android Support Libraries are deprecated and replaced with AndroidX, so I think this issue is likely obsolete.
