### ISSUE TITLE
[DevCom] deployment hangs onjava.exe -jar step

### ISSUE THREAD

**Issue by grendello** [xamarin/xamarin-android#2711]
Developer Community issue: https://developercommunity.visualstudio.com/content/problem/446584/deployment-hangs-onjavaexe-jar-step.html

Original post:

```
VS2017 hangs on java.exe -jar step. successfully deployed earlier today. nothing has been changed as far as the project(s) or packages. 
```

**Comment by dellis1972** [comment]
@jonathanpeppers did you get the logs for this issue? If so can you attach them here.

**Comment by jonathanpeppers** [comment]
Here is the log: [Build Diagnosic.txt](https://github.com/xamarin/xamarin-android/files/3018070/Build.Diagnosic.txt)

Seemed to hang on:
```
5>Detecting installed packages...
5>DEBUG RunShellCommand 9201119208edb38f am broadcast -a "mono.android.intent.action.PACKAGE_VERSIONS" -e "packages" "Mono.Android.DebugRuntime,Mono.Android.Platform.ApiLevel_27,com.btech.Clarity" -n "Mono.Android.DebugRuntime/com.xamarin.mono.android.PackageVersions"
```

He killed `google.app` on his device, and then it solved the problem. Seems to happen when his device restarts? It only happens rarely; he can't reproduce it.

His device is a `Samsung Android 6.0 G550T2`, I think [this one](https://deviceatlas.com/device-data/devices/samsung/sm-g550t2/14137685).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
