### ISSUE TITLE
Multidex not working

### ISSUE THREAD

**Issue by cheansiong** [xamarin/xamarin-android#2765]
### Steps to Reproduce

1. Multidex is enabled and it just not working suddenly.
2. Can simulate using the apk binary.
3. The apk contains the application class, but error shows that the application class cannot be found.

Note:
What have been done
- Upgrade Visual Studio
- Update Nuget Packages

[log.txt](https://github.com/xamarin/xamarin-android/files/2899458/log.txt)
![2](https://user-images.githubusercontent.com/11568375/53322770-52576100-3917-11e9-9ee2-5e20a92d5234.png)

### Expected Behavior
Application should launch successfully without any error in all version.

### Actual Behavior

```
Error below is thrown when launching apk in Android 4.4
02-25 07:29:27.826: E/AndroidRuntime(3376): FATAL EXCEPTION: main
02-25 07:29:27.826: E/AndroidRuntime(3376): Process: com.bigdutchman.farmbookpro.layer, PID: 3376
02-25 07:29:27.826: E/AndroidRuntime(3376): java.lang.RuntimeException: Unable to instantiate application fbp.mob.app.MyApp: java.lang.ClassNotFoundException: Didn't find class "fbp.mob.app.MyApp" on path: DexPathList[[zip file "/data/app/com.bigdutchman.farmbookpro.layer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.bigdutchman.farmbookpro.layer-1, /system/lib]]
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:516)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4317)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.ActivityThread.access$1500(ActivityThread.java:135)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.os.Looper.loop(Looper.java:136)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at dalvik.system.NativeStart.main(Native Method)
02-25 07:29:27.826: E/AndroidRuntime(3376): Caused by: java.lang.ClassNotFoundException: Didn't find class "fbp.mob.app.MyApp" on path: DexPathList[[zip file "/data/app/com.bigdutchman.farmbookpro.layer-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.bigdutchman.farmbookpro.layer-1, /system/lib]]
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.Instrumentation.newApplication(Instrumentation.java:975)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
02-25 07:29:27.826: E/AndroidRuntime(3376): 	... 11 more
02-25 07:29:28.596: E/EGL_emulation(1965): tid 1965: eglSurfaceAttrib(1199): error 0x3009 (EGL_BAD_MATCH)
```

**Comment by pjcollins** [comment]
Hello @cheansiong it looks like you may be running into a scenario where one or more of your applications class files required during startup are not included in your main .dex file. In order to address this, could you please try the following:

1) Download this template [multidex.keep file](https://github.com/xamarin/xamarin-android/files/2911334/multidex.keep.txt).
2) Rename it to `multidex.keep`, and include it in your main app project.
3) Set the build action of this file to `MultiDexMainDexList`. This should create an item group in your .csproj file along the lines of:
```xml
  <ItemGroup>
    <MultiDexMainDexList Include="multidex.keep" />
  </ItemGroup>
```
4) Finally, you'll need to add a line (or lines) to the bottom of the file which specify the classes which can't be found. You'll need to try to add an entry for the missing class listed above (e.g. `fbp/mob/app/MyApp.class`).

If these steps aren't working for you, we'll likely require more information and/or a project which reproduces the issue to help assist with the problem.

**Comment by cheansiong** [comment]
Hi @pjcollins ,

In the project mentioned, I have already perform
1. (Was) Enable Multidex in Project Setting.
2. (Update) Update the multidex.keep file to latest as reacommended.
3. (Was) Includes the multidex.keep file to MultiDexMainDexList.

Earlier, the Multidex.keep file content was as below.
_mono/MonoPackageManager.class
mono/MonoPackageManager_Resources.class
mono/MonoRuntimeProvider.class
mono/android/app/NotifyTimeZoneChanges.class
mono/android/app/ApplicationRegistration.class
fbp/mob/plugins/main/ui/LauncherActivity.class
fbp/mob/app/MyApp.class_

However, the problem still occurs, is providing an apk sufficient to find the problem? Do you have a private inbox that allows me to upload the apk?

**Comment by pjcollins** [comment]
If you would be able to send me an email with an .apk and the [binary build log](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2017#save-a-binary-log) used to create the .apk file we should be able to investigate further. We don't have a private upload location, but you could potentially host these on a file share service of your own (dropbox, etc)?

**Comment by softlion** [comment]
+1. Occurs only when aapt2 is enabled. And only with the nuget "XamSvg"for android, when the XamSvg ui view is used in an xml layout file.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
