### ISSUE TITLE
Improve error scenarios and messaging when hitting MAX_PATH limitations on Windows

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#2848]
https://developercommunity.visualstudio.com/content/problem/490525/objdebug81androidbinclasses-error-on-building-xama.html

### Steps to Reproduce

1. Create a new XF app in VS2017 or VS2019 with a long project name (e.g. `MyXamarinFormsProjectWithAVeryLongName`.
2. Attempt to build the Android project.
3. Attempt to clean/rebuild the Android project.

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2566,3): error MSB3231: Unable to remove directory “obj\Debug\81\android\bin\classes”. Could not find a part of the path ‘AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.class’.
```

We should try to reduce the length of paths we're generating in the `IntermediateOutput` directory where possible, and also attempt to provide a more actionable error message when we we do hit path length limitations on Windows.

**Comment by BretJohnson** [comment]
I ran into this issue as well and we were just discussing some of the options.

Prefixing the path with `??\?` so that the remove works is one option. That requires .NET Framework 4.7.2, but it looks like we can assume that now with MSBuild. We should test to ensure that there are no other max path build issues, once we get past the remove.

As another option, if the remove directory fails we could check the path length and if it's > MAX_PATH assume it's a max path problem and give a better error, suggesting to the user to either enable max path support in Windows 10 via the registry setting or move the project to a path that's not so long.

And, like Peter mentioned, shortening the length of our intermediate paths is a 3rd option.

But hopefully the first option does the complete job here.

**Comment by jonathanpeppers** [comment]
So some comments here, expanding on the conversation on [Slack](https://xamarinhq.slack.com/archives/C03CEGRUW/p1565389914033700) is we have a discrepancy of path length between:
* `obj\Debug\android\src` - where we generate `.java` source code from C#
* `obj\Debug\android\bin\classes` - where `javac` compiles `.class` files *into*

If you have a project on the edge, where `android\src` does *not* have a long path, but `android\bin\classes` *does*, we get the issue here:

```
error MSB3231: Unable to remove directory "obj\Debug\90\android\bin\classes". Could not find a part of the path 'AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.class'.
```
`javac` was able to create this file that is over `MAX_PATH`, and unfortunately, .NET is throwing a `DirectoryNotFoundException` here...

## Some experiments

On .NET 4.7.2 and Windows 10 build 1903 , on a machine *without* long paths enabled.

### 1. Delete a directory

```csharp
var dir = @"C:\src\xamarin-android\bin\TestDebug\temp\OnTheEdgeNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN\obj\Debug\android\bin\classes";
if (Directory.Exists (dir))
    Directory.Delete(dir, recursive: true);
```
Throws:
```
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.class'.'
```

### 2. Create a long path file from .NET

> Prefixing the path with `??\?` so that the remove works is one option.

I think @BretJohnson  meant, `\\?\`:

```csharp
File.WriteAllText(
    path: @"\\?\" + Path.Combine(Path.GetTempPath(), "foo".PadRight(250, 'N')),
    contents: "foo");
```

This works, as does `File.Exists()`, `File.Delete()`, etc.

## What we can do

We can't rely on users having the registrey key set, and they may not be using the latest Windows 10.

PR so far: https://github.com/xamarin/xamarin-android/compare/master...jonathanpeppers:max_path_ugh

* We can use `\\?\` and `Directory.Delete()`, that fixes the directory removal issue.
* I do not think it is feasible to go through our entire codebase prefixing `\\?\`, but we can fix this one bad case of #deletebinobj.

There may also be other cases it is beneficial.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix to improve the behavior of this scenario. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

(The fix is not relevant for macOS.)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(The fix is not relevant for macOS.)
