### ISSUE TITLE
AXML Designer does not allow for more than one control to be dropped onto the design for relative layouts

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-android#2922]
### Steps to Reproduce

1. Create a new Xamarin Android App project in Visual Studio.
2. Navigate to "Resources/layout/activity_main.axml".
3. Try to add two buttons to the Design.

### Expected Behavior

Allow more than one control to be added.

### Actual Behavior

Only one control can be added.

### Version Information

Visual Studio 2017 and 2019.

### Log File

There is none.

**Comment by jgold6** [comment]
Slight correction:
### Steps to Reproduce
 1. Create a new Xamarin Android BLANK App project in Visual Studio. _(The Single View app template does not use the RelativeLayout)_
 
Possible workarounds:

1. Add the controls you need in the AXML source code directly.

2. If you don't require the RelativeLayout (which is often not recommended as it is expensive performance wise and is the slowest of the layouts to load due to havong to resolve all of the relative layout references), then switch to another type of layout. 

3. Open your AXML layout file in Android Studio and use the Android Studio designer to make your layouts.

**Comment by jpobst** [comment]
If this is still an issue:

This issue likely occurs in the Android Designer, which is owned by a different team who does not use GitHub for issue tracking.  

Please use the [tools available inside of VS](https://developercommunity.visualstudio.com/home) to report this issue.  This allows the issue to be routed to the correct team, and provides them the correct logs they need to diagnose it.

Thanks!
