### ISSUE TITLE
UI support for recording AOT profile

### ISSUE THREAD

**Issue by radekdoulik** [xamarin/xamarin-android#2933]
To use the full potential of AOT profiles we should give the user an ability to quickly create the startup AOT profile to use in the build of their apps.

## Initial idea

Make it possible to start app from IDE with aot profiler enabled and then retrieve the aot profile.

### UI part

In VS/Mac it might look like new menu item `Run/Start AOT Profiling`. Once the app starts, there will appear a button next to debugger and inspector buttons, which should retrieve the profile from the app and add it to the project tree with appropriate build action set.

### mono AOT profiler changes

Socket based command channel and data channel to the AOT profiler. It can be then forwarded by `adb` to host machine.

On the host the IDE or a command line tool like nc could be used to control the profiler. The profiler should accept command to save the profile. It will be saved either to the data channel or the output file depending and the AOT profiler arguments.

@JonDouglas how does it look?

**Comment by pjcollins** [comment]
I think our d16-2 window is quickly closing for this kind of work. I'm going to remove the milestone.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
