### ISSUE TITLE
AndroidClientHandler code is not structured well enough to override anything

### ISSUE THREAD

**Issue by SamuelDebruyn** [xamarin/xamarin-android#3059]
I tried to override [a method](https://github.com/xamarin/xamarin-android/blob/756117040ef85fd7d6c9ae5c7afe218da6cae734/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs#L263) to fix https://github.com/xamarin/xamarin-android/issues/3058

As soon as you copy this method over and try to change the line with the issue, you notice a lot of errors leading to private methods, properties or fields. When you copy over these methods from the source, you notice another bunch of errors with the same cause. Overriding this single method (I know, it's the most crucial one) leads me to copying all the files inside the Xamarin.Android.Net folder.

IMHO this class should be restructured so that it's a lot easier for inheritors to override some parts of it.

**Comment by jonathanpeppers** [comment]
@SamuelDebruyn can you post a simple C# code example of what you might want to override?

**Comment by grendello** [comment]
Hi @SamuelDebruyn,

This class was never meant to be extensible by the user to the degree above what's absolutely necessary to make the client handler work (e.g. the SSL setup, socket factory etc). It was a deliberate decision as the class is to serve as a drop-in replacement for the default HTTP client handler and there are many quirks to the underlying Java HTTP handling - we didn't want to make it "too easy" to introduce issues. Issue #3058 is a bug in the class and it should be fixed there (as you do in https://github.com/xamarin/xamarin-android/pull/3060) instead of overriding the default class behavior.
