### ISSUE TITLE
Android Emulator crashes Windows

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/xamarin-android#3079]
I'm not exactly sure whether this belongs here, but here I go. Also, I'm not alone.
If this isn't the correct place, please suggest where can I report it.

### Steps to Reproduce

1. Normal use of Android Emulator under Hyper-V

### Expected Behavior

No BSOD

### Actual Behavior

Occasionally the emulator will cause BSOD. Getting SYNTHETIC_WATCHDOG_TIMEOUT (1ca) BSOD code.

### Version Information

Emulator is 29.0.8 but it happens with earlier ones as well.

**Comment by grendello** [comment]
Hi @MihaMarkic,

It's not a Xamarin.Android issue so we can't fix it for you, but we will route the problem to the team which can take a look at it and update this issue with information once we have it available.

**Comment by JonDouglas** [comment]
The best place to report this issue is directly through the Android Emulator. Here are some instructions on how to do that:

https://developer.android.com/studio/report-bugs#emulator-bugs

If you suspect it's an issue with Windows / Windows Hypervisor Framework or similar, use the Windows feedback tool in Windows, or report it using VIsual Studio's `Report a Problem` feature! Thus I am closing this issue for now! 

Thanks!

**Comment by MihaMarkic** [comment]
Thanks for the info
