### ISSUE TITLE
Android: Cannot run Xamarin.Forms Android Linking 'SDK Assemblies Only' in Debug mode.

### ISSUE THREAD

**Issue by thudugala** [xamarin/xamarin-android#3136]
### Description

Cannot run Xamarin.Forms Android app when Linking is set to 'SDK Assemblies Only' in Debug mode.

### Steps to Reproduce

1.  Run the attached Solution. 

### Expected Behavior

Run the app without any issue.

### Actual Behavior

Error is thrown.

Unhandled Exception:
Android.Views.InflateException: Binary XML file line # 23: Binary XML file line # 23: Error inflating class android.support.v7.widget.FitWindowsFrameLayout occurred

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio 2019 16.1
- Platform Target Frameworks:
  - Android: Xamarin.Forms 3.6.0.344457

### Screenshots

![image](https://user-images.githubusercontent.com/4112014/58144676-78389b80-7ca3-11e9-896b-4eda9918eb1b.png)

![image](https://user-images.githubusercontent.com/4112014/58144717-9d2d0e80-7ca3-11e9-921e-7c923478803c.png)

### Reproduction Link

[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/3205417/App1.zip)

**Comment by jonathanpeppers** [comment]
I think the issue here is actually fixed by: https://github.com/xamarin/xamarin-android/pull/3121

We were running r8 in an "unsupported" scenario:
* Using multi-dex & code shrinking
* We were passing `multidex.keep` files

When bumping r8, I found they actually made r8 fail if you used this combination. I reworked Xamarin.Android so that it will ignore `multidex.keep` files in this case.

If you are hitting this, either use:
* `<AndroidLinkTool>r8</AndroidLinkTool>`
_OR_ 
* `<AndroidEnableMultiDex>True</AndroidEnableMultiDex>`
...but not both. 

`r8` would be for `Release` builds, and multi-dex for `Debug` builds only if needed. See: https://github.com/xamarin/xamarin-android/issues/3136#issuecomment-495047394

Please comment/file a new issue, if that doesn't solve the issue, thanks!
