### ISSUE TITLE
New strategy for support multidex jars/aars?

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#3156]
### The Problem

We currently ship `android-support-multidex.jar` which comes from: https://github.com/xamarin/xamarin-android/blob/055dabe34e1897305be178a260faee3815e3e908/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets#L245-L264

This appears to be version 1.0.1.

Java developers in Android Studio use this library by adding this to their `build.gradle`:
```groovy
dependencies {
  implementation 'com.android.support:multidex:1.0.3'
}
```
https://developer.android.com/studio/build/multidex#mdex-pre-l
https://mvnrepository.com/artifact/com.android.support/multidex/1.0.3

But it is only actually _needed_ if your `minSdkVersion` is less than 21. Otherwise Android can support multidex natively without using any support library.

### Questions

* How can developers use a newer multidex lib on their own? Do they need to? Some MSBuild knowledge is required in order to get it to work.
* Should we update what we ship in Xamarin.Android? Get it from maven?
* How do we support AndroidX moving forward?
* In all cases, if `minSdkVersion` is 21 or higher, do we need to avoid using these multidex libraries completely? (they are small)

### For AndroidX

We got AndroidX to work with a couple of examples.

* For migration: https://github.com/xamarin/XamarinAndroidXMigration/blob/master/source/Xamarin.AndroidX.Migration.BuildTasks/Xamarin.AndroidX.Migration.targets#L62-L78
* For if you are just using straight AndroidX: https://github.com/xamarin/AndroidSupportComponents/pull/174/files#diff-d8e801b8814e977eb10cfc9f9e92c94f

**Comment by JonDouglas** [comment]
@jonathanpeppers 

Current day support, it's fairly rare for people to support < 19 but it does exist still. So I think we should still support it. 

https://developer.android.com/about/dashboards/

> How can developers use a newer multidex lib on their own? Do they need to? Some MSBuild knowledge is required in order to get it to work.

They shouldn't need to except in very advanced cases. We should update this as often as possible since I doubt it will be updated in the near future. Rather the AndroidX version will be updated instead.

> Should we update what we ship in Xamarin.Android? Get it from maven?

Absolutely.

> How do we support AndroidX moving forward?

We support three scenarios:

1. 21 or higher - Multidex dependency isn't needed.
2. < 21 - Ideally we should be using `androidx.multidex:multidex:2.0.1` for AndroidX scenarios.
3. < 21 (Non AndroidX) - Ideally we should be using latest of `com.android.support:multidex:1.0.3` for Android Support Library scenarios.

These will need to have logic of `if AndroidX` or similar so the proper `MultiDexApplication` is used for the `<application>` tag:

i.e. AndroidX - ` android:name="androidx.multidex.MultiDexApplication"` vs. `android:name="android.support.multidex.MultiDexApplication"`

At least I believe GenerateJavaStubs does this today? Similar with custom applications as well.

> In all cases, if minSdkVersion is 21 or higher, do we need to avoid using these multidex libraries completely? (they are small)

Yes we should. There is no need for them as it's built into ART.

**Comment by jpobst** [comment]
.NET 6 Android is 21+, so I don't think we'll be implementing a Classic fix at this point.
