### ISSUE TITLE
Deprecated RunCodeAnalysis option results in linker error in d16-2

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#3322]
#### VS Mac 8.2
1. Create or load an XA project.
2. Right click Project -> Options.
3. Navigate to Code Anaylsis -> Enable Code Analysis on Build.
4. Switch to the Release configuration and build.

#### VS 2019 16.2
1. Create or load an XA project.
2. Switch to the Release configuration
3. Select Analyze -> Run Code Analysis -> On Solution
 
#### Command line:
1. msbuild /t:SignAndroidPackage /p:Configuration=Release  /p:RunCodeAnalysis=true

### Actual Behavior
The (now deprecated) CodeAnalysis options are resulting in a build failure when the linker is enabled after upgrading to 16.2, though the app assembly referenced in the error has been built and exists in the output and intermediate output dir:

```
 _CreatePackageWorkspace:
  Creating directory "obj/Release/android/assets/".
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018: The "LinkAssemblies" task failed unexpectedly. [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'DroidButton, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile? [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018: File name: 'DroidButton.dll' [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference reference, Mono.Cecil.ReaderParameters parameters) [0x00125] in <bf8d1485bd8b4cc8b07ee73dc73c2c6c>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (System.String fullName, Mono.Cecil.ReaderParameters parameters) [0x00007] in <bf8d1485bd8b4cc8b07ee73dc73c2c6c>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve (System.String fullName) [0x00000] in <bf8d1485bd8b4cc8b07ee73dc73c2c6c>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly (System.String fileName) [0x00007] in <bf8d1485bd8b4cc8b07ee73dc73c2c6c>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x0004d] in <d8e2132c4a15403dbf186d3f29b4d4ff>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Xamarin.Android.Tasks.LinkAssemblies.Execute () [0x0001b] in <d8e2132c4a15403dbf186d3f29b4d4ff>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute () [0x00029] in <9793e3774951417ca4f48a7c60193b35>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2147,5): error MSB4018:   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask (Microsoft.Build.BackEnd.ITaskExecutionHost taskExecutionHost, Microsoft.Build.BackEnd.Logging.TaskLoggingContext taskLoggingContext, Microsoft.Build.BackEnd.TaskHost taskHost, Microsoft.Build.BackEnd.ItemBucket bucket, Microsoft.Build.BackEnd.TaskExecutionMode howToExecuteTask) [0x002a9] in <9793e3774951417ca4f48a7c60193b35>:0  [/Users/peter/source/monodroid-samples/Button/DroidButton.csproj]
```
[msbuild.binlog.zip](https://github.com/xamarin/xamarin-android/files/3355751/msbuild.binlog.zip)

 
### Version Information
c30842125977ccffef34b22e4a6517a054529da3

**Comment by brminnick** [comment]
Thanks Peter! 

For now, is disabling "Project Options > Code Analysis > Enable Code Analysis on Build" a valid workaround?

I hit this same error in VS for Mac 8.2 build 983 and disabling "Enable Code Analysis on Build" fixed the error for me.

**Comment by pjcollins** [comment]
@brminnick Indeed. Disabling the option you've specified, or removing the following element from your project file should serve as a workaround:
 ```xml 
<RunCodeAnalysis>true</RunCodeAnalysis>
```

**Comment by brendanzagaeski** [comment]
A new preview version has now been published that includes a fix for this item.

Fix included in Xamarin.Android 10.0.0.40.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 3. To try the preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by miroserge** [comment]
Wouldn't it be better to leave this problem with the Open tag until the patches reach stable versions? I had a hard time figuring out why I couldn't build my project, and maybe there are others who are also having the same problem.

**Comment by brendanzagaeski** [comment]
I chatted with the team about ways to make it easier to identify which closed issues already have published fixes. Going forward, the team will be using additional closed [milestones](https://github.com/xamarin/xamarin-android/milestones) to help with that.

(Using the Open vs. Closed state of the issue would be trickier because GitHub's [automatic issue closing](https://help.github.com/articles/closing-issues-using-keywords) and [improved visibility for related pull requests](https://github.blog/changelog/2019-08-21-improved-visibility-for-related-pull-requests-in-issues/) features promote a workflow where issues are Closed when the fix is committed to the repository, so teams, including the Xamarin.Android team, typically use the Open vs. Closed states to help monitor which items on an active milestone do not yet have a fix committed. Interestingly, GitHub's issue search does not yet fully align with those other GitHub features. It currently still pre-fills `is:open` in the search. That's correct for contributors to the project, but isn't correct for users of published versions. I suspect in the future GitHub might provide a way for projects to customize the default issues search so it can be tailored to users as opposed to contributors.)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by miroserge** [comment]
Hi @brendanzagaeski, thank you for taking the time to consider my question and yes,  using additional milestones will help a lot!
