### ISSUE TITLE
You uploaded an APK that is not zip aligned. You will need to run a zip align tool on your APK and upload it again.

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3324]
Hi,

Why all my new projects shows shows:

> You uploaded an APK that is not zip aligned. You will need to run a zip align tool on your APK and upload it again.

when uploading the APK to Google Play?

and when I try:

`zipalign.exe -v -p 4 C:\Temp\zipalign\com.jafaria.app.apk C:\Temp\zipalign\com.jafaria.app-aligned.apk
`
and upload the APK then I get:

> You uploaded an APK with an invalid signature (learn more about signing). Error from apksigner: ERROR: JAR_SIG_NO_MANIFEST: Missing META-INF/MANIFEST.MF

I never shows these errors before

VS bug [#976385](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/976385)

**Comment by jonathanpeppers** [comment]
Hi @jrahma,

* How are you uploading to Google Play? Are you using the publishing UIs in Visual Studio? Windows or Mac?
* Can you post your version details for Visual Studio & Xamarin.Android?

If you could record a [diagnostic build log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output) that would also help.

**Comment by jrahma** [comment]
@jonathanpeppers 

1. How are you uploading to Google Play? Are you using the publishing UIs in Visual Studio? Windows or Mac?

Yes I am using the publishing UI using Archive and the Distribute and select the Keystore, enter the password then apk will be generated

I am using Visual Studio 2019 Version 16.1.5 for Windows

2. Can you post your version details for Visual Studio & Xamarin.Android?

**Compile Using :** Android 9.0

**Minimum Android Version:** Android 7.1 (API Level 25)

**Target Android Version :** Android 9.0 (API Level 28)

**Comment by jrahma** [comment]
Diagnostic build log is attached

Thanks

[BuildLog.zip](https://github.com/xamarin/xamarin-android/files/3363457/BuildLog.zip)

**Comment by jonathanpeppers** [comment]
Sorry @jrahma you might have to record the build log while deploying to device or emulator.

It doesn't look like the signing steps are in this log. 😞

**Comment by jrahma** [comment]
No worries @jonathanpeppers 

It's attached here now

[BuildLog2.zip](https://github.com/xamarin/xamarin-android/files/3363476/BuildLog2.zip)

**Comment by jonathanpeppers** [comment]
/cc @joj I think whatever is happening here is from the publishing workflow in VS, and we don't actually need an MSBuild log.

Is there a log he can grab from the publishing UI that would help here?

**Comment by jrahma** [comment]
guys if this is going to take longer time then is there any workaround? 

I am supposed to publish the app this month and my hands are tied now because all apps giving the same problem.

**Comment by jonathanpeppers** [comment]
@jrahma you can configure your `Release` build: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#signing-properties

```xml
    <AndroidKeyStore>True</AndroidKeyStore>
    <AndroidSigningKeyStore>filename.keystore</AndroidSigningKeyStore>
    <AndroidSigningStorePass>keystore.filename password</AndroidSigningStorePass>
    <AndroidSigningKeyAlias>keystore.alias</AndroidSigningKeyAlias>
    <AndroidSigningKeyPass>keystore.alias password</AndroidSigningKeyPass>
```

And then build your APK with just the `Release` configuration in the IDE, or command-line:
```
msbuild YourApp.Android.csproj /t:SignAndroidPackage /p:Configuration=Release
```

**Comment by jrahma** [comment]
command line throws error:

> C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\msbuild Jafaria.Android.csproj /t:SignAndroidPackage /p:Configuration=Release
> Microsoft (R) Build Engine version 4.8.3752.0
> [Microsoft .NET Framework, version 4.0.30319.42000]
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> Build started 7/9/2019 12:44:26 AM.
> Project "C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android\Jafaria.Android.csproj" on node 1 (SignAndroidPack
> age target(s)).
> C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android\Jafaria.Android.csproj(180,47): error MSB4066: The attribut
> e "Version" in element <PackageReference> is unrecognized.
> Done Building Project "C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android\Jafaria.Android.csproj" (SignAndroid
> Package target(s)) -- FAILED.
> 
> 
> Build FAILED.
> 
> "C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android\Jafaria.Android.csproj" (SignAndroidPackage target) (1) ->
>   C:\Users\jrahm\Source\Repos\Jafaria\Jafaria\Jafaria.Android\Jafaria.Android.csproj(180,47): error MSB4066: The attrib
> ute "Version" in element <PackageReference> is unrecognized.
> 
>     0 Warning(s)
>     1 Error(s)
> 
> Time Elapsed 00:00:00.34
>

**Comment by tondat** [comment]
@jrahma Thank you for your feedback!

Given that you have a clear repro of the issue and in order to continue investigating, we would really like you to please report the error using the VisualStudio `Report a problem` tool.

Here you can see the instructions https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019. 

When you report problems using this tool within VisualStudio, the IDE collects several diagnostic information that helps our investigation, like the IDE logs and environment configuration.

Also, as there is some build specific information that is not automatically attached and can be useful to investigate this case, we would also ask you to please install the `Project System Tools` extension that allows you to obtain internal build logs:
 https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools
    
To start the tool please use the menu option `View\Other Windows\Build Logging`.

The tools show up a start button that starts recording all the queries executed.
    
After that please try to reproduce the problem creating the archive and trying to distribute it.

Please attach to the reported error the content of the build output pane, the content of the Xamarin output pane and the logs detected by the tool related to the targets PackageForAndroid\SignAndroidPackage`.

With all this information, we should be able to move forward with the investigation.

Thank you for taking the time to report this problem,  we look forward to hearing from you!
