### ISSUE TITLE
[Bug][Android] App using resx files crashes when built with "Bundle assemblies into native code"

### ISSUE THREAD

**Issue by pab6655** [xamarin/xamarin-android#3340]
### Description
When doing a release build for android and check 'Bundle assemblies into native code' the app crashes on startup. The app uses resx file localization with the resx files put in a dedicated project. The error message on startup indicates a problem with loading that assembly. 
Minimized reproduction project: [ResxStrings.zip](https://github.com/xamarin/Xamarin.Forms/files/3372079/ResxStrings.zip)

### Steps to Reproduce

1. Do a release build of the attached project with 'Bundle assemblies into native code' checked.
2. Launch the app on a device or emulator.

### Expected Behavior
App launches successfully. The string from resx file is shown on the main page.

### Actual Behavior
App crashes on startup.
 
Error in android log: 
A/monodroid-assembly(22386): Could not load assembly 'ResxStrings.Resources' during startup registration.

### Basic Information

- Version with issue:
- Last known good version: ?
- IDE: Visual Studio 2017, 15.9.13
- Platform Target Frameworks: 
  - Android: Xamarin.Android SDK 9.1.7.0 
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by grendello** [comment]
The resource assembly is included in the bundle, however its not at the "root" of the project but rather under the `assets/ResxStrings.Resources.dll` path:

```
Task "MakeBundleNativeCodeExternal" (TaskId:385)
  Task Parameter:KeepTemp=False (TaskId:385)
  Task Parameter:AndroidNdkDirectory=/home/grendel/android/ndk/ (TaskId:385)
  Task Parameter:
      Assemblies=
          obj/Release/android/assets/ResxStrings.Android.dll
                  HasMonoAndroidReference=True
                  OriginalItemSpec=bin/Release/ResxStrings.Android.dll
                  ReferenceAssembly=/home/grendel/Projects/bugs/issue3340/ResxStrings/ResxStrings.Android/bin/Release/ResxStrings.Android.dll
                  TargetFrameworkIdentifier=MonoAndroid

[...]

  [mkbundle stdout] Storing satellite assembly '/home/grendel/Projects/bugs/issue3340/ResxStrings/ResxStrings.Android/obj/Release/android/assets/ResxStrings.Resources.dll' with name 'assets/ResxStrings.Resources.dll' (TaskId:385)
  [mkbundle stdout] Storing satellite assembly '/home/grendel/Projects/bugs/issue3340/ResxStrings/ResxStrings.Android/obj/Release/android/assets/ResxStrings.Resources.dll' with name 'assets/ResxStrings.Resources.dll' (TaskId:385)
```

This happens because of [this code in mkbundle](https://github.com/mono/mono/blob/b31a445e85523a9a41b0975203f7ccd1d6f185a8/mcs/tools/mkbundle/mkbundle.cs#L1315-L1326). The code works this way because satellite assemblies share the same assembly name but are placed in subdirectories named after the [locale they represent](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-satellite-assemblies-for-desktop-apps). `mkbundle` decides that any assembly whose name ends with `.resources.dll` is, in fact, a satellite assembly and then stores it with its last subdirectory intact (e.g. assembly with path `/path/to/my/assemblies/Test.Resources.dll` will be stored as `assemblies/Test.Resources.dll` in the bundle). The `.resources.dll` suffix is, alas, the only indicator `mkbundle` can use that it's dealing with a satellite assembly and we can't add any special interpretion of the subdirectory name either as it would require storing a list of all valid/possible locale names in the utility.

With that, the fix/workaround here is to rename the `ResxStrings.Resources` assembly to not use the `.resources` suffix. I modified the sample solution so that the `ResxStrings.Resources/ResxStrings.Resources.csproj` output `ResxStrings.Data.dll` and everything worked fine.

@jonathanpeppers Do you think we would somehow improve our diagnostics for this kind of situation? E.g. check whether an assembly with the `.resources.dll` suffix is, in fact, a satellite assembly? If we determine it's not, perhaps we could warn about the potential issue?

**Comment by dellis1972** [comment]
@grendello we have an MSBuild Item group which is specific to Satellite assemblies `@(_AndroidResolvedSatellitePaths)` so we should be able to at least identify which assemblies are satellite ones.
