### ISSUE TITLE
APK build copies sqlite lib for incorrect ABI into APK, causing DllNotFoundException

### ISSUE THREAD

**Issue by benlacey** [xamarin/xamarin-android#3373]
We're facing an issue with our projects, when deployed to an x86 emulator and attempting to use SQLite the app fails to load the `libe_sqlite.so` because the ARM version of the library has been packaged by Xamarin Android in the `lib/x86` folder of the APK instead of the correct x86 version.

I have managed to reduce the problem down to a simple repro app, which is attached.

### Steps to Reproduce

1. Build and deploy the attached repro project in `Debug | x86` configuration to an x86 Android emulator

Reproducing project here:
[bugrepro_nativelibfailure.zip](https://github.com/xamarin/xamarin-android/files/3411233/bugrepro_nativelibfailure.zip)

### Expected Behavior

You should see 'Started OK' in the middle of the activity

### Actual Behavior

Attempting to access the SQLite native library (via a call to Akavache) fails, and the exception is shown in the activity (System.DllNotFoundException: e_sqlite3)

### Investigation Notes

It seems that in the BuildApk task, even though SupportedAbis = x86, the task copies the `armeabi` version of `libe_sqlite.so` into the x86 target directory, leading to the `Apk already contains the item` warnings seen in the deploy logs when it tries to copy the correct x86 version.
It also attempts to incorrectly copy the `x86_64` version onto the same `x86` target file.

Unzipping the APK and checking the included lib confirms that the `lib/x86/libe_sqlite.so` file is indeed the `armeabi` version:

```
unzip com.audiogum.newapp.dev.apk 
file lib/x86/libe_sqlite3.so 
lib/x86/libe_sqlite3.so: ELF 32-bit LSB shared object ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, stripped
```

### Version Information

```
=== Visual Studio Professional 2019 for Mac ===

Version 8.1.5 (build 9)
Installation UUID: 6fee0024-dcfc-4914-83ec-91ad57558c5e
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.25 (d16-0 / 50f75273)

	Package version: 518010028

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.28 (2018-08/223ea7ef92e) (64-bit)
	Package version: 518010028

=== NuGet ===

Version: 5.0.2.5988

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.1.11
	2.1.9
	2.1.8
	2.1.7
	2.1.2
	2.1.1
	2.0.5
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.1.700/Sdks
SDK Versions:
	2.1.700
	2.1.505
	2.1.504
	2.1.503
	2.1.302
	2.1.301
	2.1.4
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.10
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2.1 (14490.122)
Build 10E1001

=== Xamarin.Mac ===

Version: 5.10.0.157 (Visual Studio Professional)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:48-0400

=== Xamarin.Android ===

Version: 9.3.0.23 (Visual Studio Professional)
Commit: HEAD/d0b48056f
Android SDK: /Users/blacey/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08@3a07bd426d3
Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
LibZipSharp: grendello/LibZipSharp/d16-1@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/blacey/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.44
Hash: aac645b
Branch: remotes/origin/d16-1
Build date: 2019-05-29 19:55:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Xamarin.iOS ===

Version: 12.10.0.157 (Visual Studio Professional)
Hash: 6bd94753
Branch: d16-1
Build date: 2019-06-12 17:28:47-0400

=== Xamarin Designer ===

Version: 16.1.0.467
Hash: f1657e133
Branch: remotes/origin/d16-1-new-document-model
Build date: 2019-06-18 21:57:42 UTC

=== Build Information ===

Release ID: 801050009
Git revision: bd0ab28ba941b19b39322247db020dcd0fb305d0
Build date: 2019-07-03 17:15:21+00
Build branch: release-8.1
Xamarin extensions: 8cc25b5cb090e6c23b62a7901000c299977eb08d

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Brute Clean 1.1
```

### Log File

Full diagnostic log for deployment process is attached.  See line 8917 for the BuildApk task output.
[deploy_log.txt](https://github.com/xamarin/xamarin-android/files/3411237/deploy_log.txt)

Logcat output also attached:
[logcat.txt](https://github.com/xamarin/xamarin-android/files/3411239/logcat.txt)

**Comment by jonathanpeppers** [comment]
Hi @benlacey,

When I build the project I get the error:
```
error XA0115: Invalid value 'armeabi' in $(AndroidSupportedAbis). This ABI is no longer supported. Please update your project properties.
```
Are you not getting this error message? We no longer support `armeabi` because the Android NDK no longer supports it either, if you remove that architecture does that solve the issue?

**Comment by benlacey** [comment]
Hi @jonathanpeppers - thanks for taking a look!

That `armeabi` error does indeed occur if I build in the `Debug | AnyCPU` configuration, but if I build in the x86-specific `Debug | x86` configuration the error described in the report happens.  I should really have removed the AnyCPU configuration from the build as it's pretty useless!

Retesting on a more recent version of VS for Mac, I get _slightly_ different behaviour in that the correct lib gets copied to the APK (and so the app can access sqlite), but the libs for other platforms are still attempted to be copied to the same target location:

```  Task "BuildApk"
    Adding native library: /Library/Frameworks/Xamarin.Android.framework/Versions/9.4.0.51/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-android.debug.so (APK path: lib/x86/libmonodroid.so)
    Adding native library: obj/x86/Debug/app_shared_libraries/x86/libxamarin-app.so (APK path: lib/x86/libxamarin-app.so)
    Adding native library: /Library/Frameworks/Xamarin.Android.framework/Versions/9.4.0.51/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-btls-shared.so (APK path: lib/x86/libmono-btls-shared.so)
    Adding native library: /Library/Frameworks/Xamarin.Android.framework/Versions/9.4.0.51/lib/xamarin.android/xbuild/Xamarin/Android/lib/x86/libmono-profiler-log.so (APK path: lib/x86/libmono-profiler-log.so)
    	Adding obj/x86/Debug/lp/5/nl/x86/libe_sqlite3.so
    	Adding obj/x86/Debug/lp/5/nl/armeabi/libe_sqlite3.so
    	Adding obj/x86/Debug/lp/5/nl/x86_64/libe_sqlite3.so
    	Adding /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/lib/x86/libmono-native.so
    obj/x86/Debug/lp/5/nl/armeabi/libe_sqlite3.so : warning XA4301: Apk already contains the item lib/x86/libe_sqlite3.so; ignoring.
    obj/x86/Debug/lp/5/nl/x86_64/libe_sqlite3.so : warning XA4301: Apk already contains the item lib/x86/libe_sqlite3.so; ignoring.
```

The order is different to the previous version of VS, with the correct platform coming first then the others following afterwards (and failing, as the correct x86 lib is already there).  So it appears to be semi-fixed in the more recent version of VS, but something is still lurking that attempts to copy the wrong platform libs during the build.

**Comment by jonathanpeppers** [comment]
@benlacey if you clean does the problem go away? I'm not seeing the issue happen when I do a fresh build.

But I wonder if doing this is causing it:
```
msbuild NewApp.Droid.csproj /p:Platform=ARM /t:SignAndroidPackage
msbuild NewApp.Droid.csproj /p:Platform=x86 /t:SignAndroidPackage
```

Then the second build is using files leftover from the `ARM` build.

So the fix may be to add an additional `$(IntermediateOutputPath)` property for each of your configurations:
```xml
<OutputPath>bin\x86\Debug</OutputPath>
<IntermediateOutputPath>obj\x86\Debug</IntermediateOutputPath>
```

Let me know if I'm on the right track here, thanks! I definitely see something needs fixed here.

**Comment by jonathanpeppers** [comment]
Actually, it looks like changing `$(IntermediateOutputPath)` to like my example shows a bug:

https://github.com/xamarin/xamarin-android/blob/ecc016a2157e2a048dfd08f57e5ce4952aae3127/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs#L257-L262

https://github.com/xamarin/xamarin-android/blob/ecc016a2157e2a048dfd08f57e5ce4952aae3127/src/Xamarin.Android.Build.Tasks/Utilities/MonoAndroidHelper.cs#L250-L255

If a directory is named `obj\x86\...`, then it is going to report `armeabi` as valid:

```
GetImportedLibraries
      NativeLibraries: 
        obj\x86\Debug\90\lp\5\nl\arm64-v8a\libe_sqlite3.so
        obj\x86\Debug\90\lp\5\nl\armeabi\libe_sqlite3.so
        obj\x86\Debug\90\lp\5\nl\armeabi-v7a\libe_sqlite3.so
        obj\x86\Debug\90\lp\5\nl\x86\libe_sqlite3.so
        obj\x86\Debug\90\lp\5\nl\x86_64\libe_sqlite3.so
```

Where the `ARM` configuration isn't doing this because it is not in the list of `ValidAbis`. I think this code should just be looking at the directory the `.so` file is contained within?

**Comment by benlacey** [comment]
That would appear to be the issue I'm running into!  My testing results are:

* No `IntermediateOutputPath ` specified = intermediate files output to `obj\x86\Debug` and APK warnings seen
* `IntermediateOutputPath` set to `obj\x86\Debug` = same warnings
* `IntermediateOutputPath` set to `obj\emulator\Debug` = no warnings regarding APK already containing libe_sqlite.so file

I guess the reason my builds consistently fail is that when `IntermediateOutputPath` is not specified it defaults to `obj\x86\Debug`, and maybe yours doesn't.  But now I know the workaround I'm happy.

Thanks for investigating!

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.0.99.100 and 10.1.0.1.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1 and 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
