### ISSUE TITLE
d16-2 .pkg installer breaks AppCenter

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#3457]
Context: https://xamarinhq.slack.com/archives/C03CEGRUW/p1565178419327500

For *years* -- ever since the introduction of `Xamarin.Android.framework`, iirc -- there have been four symlinks of consequence on macOS:

  * `/Library/Frameworks/Xamarin.Android.framework/Versions/Current`
  * `/Library/Frameworks/Mono.framework/External/xbuild/Novell`
  * `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android`
  * `/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid`

The first symlink is the most important one.  Multiple Xamarin.Android versions can be installed at the same time, and the `Current` symlink controls which version is used.

The remaining three symlinks point into `Xamarin.Android.framework`.

*However*, before d16-2 the latter three symlinks indirected *through* the `Current` symlink:

```bash
$ ls -l /Library/Frameworks/Mono.framework/External/xbuild/Novell
lrwxr-xr-x  1 root  wheel   58 Aug  1 13:06 /Library/Frameworks/Mono.framework/External/xbuild/Novell -> ../../../Xamarin.Android.framework/Libraries/xbuild/Novell
```

With d16-2 (via e83ba0ddc159d15abcfac1a5a4bce5a53e165d3f), that "indirection" no longer exists; it contains an explicit Xamarin.Android version:

```bash
$ ls -l /Library/Frameworks/Mono.framework/External/xbuild/Novell
lrwxr-xr-x  1 root  wheel  86 Aug  2 17:14 /Library/Frameworks/Mono.framework/External/xbuild/Novell -> ../../../Xamarin.Android.framework/Versions/9.4.0.51/lib/xamarin.android/xbuild/Novell
```

Additionally, pre-d16-2 installs had the symlinks:

  * `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild`
  * `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild-frameworks`

In which `/Library/Frameworks/Xamarin.Android.framework/Libraries` was a symlink through `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib`.

The benefit to the pre-d16-2 approach -- *which AppCenter relies on* -- is that *if* multiple Xamarin.Android versions are installed, *only* the `Current` symlink needs to be updated in order to *fully* change which Xamarin.Android version is used.

As of d16-2, that is no longer the case:

  * If d16-2 is installed, then e.g. d16-1 is installed, and the `Current` symlink is "manually" updated to refer to d16-2, the symlinks won't be valid, as e.g. `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild` won't exist.
  * if d16-1 is installed, then d16-2 is installed, and the `Current` symlink is "manually" updated to refer to d16-1, *all* of the symlinks will be *valid*, but they won't refer to the right version.  For example, `/Library/Frameworks/Mono.framework/External/xbuild/Novell` will refer to *only* the d16-2 install, and will no longer be using d16-1, *even though* the `Current` symlink is pointing to d16-1.

For AppCenter's sanity, we need to restore the pre-d16-2 symlink semantics on macOS:

  * `/Library/Frameworks/Xamarin.Android.framework/Libraries` should exist, and point to `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib`.
  * `/Library/Frameworks/Xamarin.Android.framework/Versions/@VERSION@/lib/xbuild` should exist, and should link to `xamarin.android/xbuild`
  * `/Library/Frameworks/Xamarin.Android.framework/Versions/@VERSION@/lib/xbuild-frameworks` should exist, and should link to `xamarin.android/xbuild-frameworks`

> VS bug [#962575](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962575)

**Comment by brendanzagaeski** [comment]
A new Preview version has now been published that includes a fix for this item.

Fix included in Xamarin.Android 10.0.0.40.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

The fix is not relevant for Windows.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
