### ISSUE TITLE
Error APT0000: unexpected element <library> found in <manifest> with Xamarin android version 10.0.0.4

### ISSUE THREAD

**Issue by hanseul1795** [xamarin/xamarin-android#3474]
### Steps to Reproduce

1. Build `.aab` or `.apk` file with Xamarin Android 10.0.0.4
2. Error APT0000: unexpected element  library found in manifest
3. Build fails

### Expected Behavior
No Error 

### Actual Behavior
I've tested with 9.1.199.79 version, it builds.
It failed on 10.0.0.4 version (from [https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-d16-3/27/Azure/] )

 ```
 <library android:name="moat-mobile-app-kit" />
  <meta-data android:name="android.support.VERSION" android:value="25.3.1" />
</manifest>

```
this is the part in `AndroidManifest.xml` where it fails.

**Comment by JonDouglas** [comment]
@hanseul1795 What is `<library>`? I don't see that on the reference list:

https://developer.android.com/guide/topics/manifest/manifest-intro#reference

Instead, you can use:

https://developer.android.com/guide/topics/manifest/uses-library-element.html

The problem most likely is that regular `aapt` in 9.1.X builds does not detect nor care to warn you about this because it doesn't hurt anything. However using `aapt2` by default in 10.0.X builds will tell you it's invalid because it's `aapt2` will throw errors on things `aapt` originally would not have.

The test here would be in the 10.0.X builds to disable `aapt2` and see if that allows you to build like you did previously. However generally speaking, I believe this is an invalid element.

https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.5#aapt2-enabled-by-default-for-all-projects

There's also documentation for this library here: https://developers.mopub.com/publishers/android/get-started/#step-3-update-your-android-manifest

**Comment by hanseul1795** [comment]
@JonDouglas 
Hello again!

`aapt2` was disabled when I tested this issue.

When I built the `.apk` file with 10.0.X version, it did not raise that error.
It only happens when I build `.aab` file.

**Comment by JonDouglas** [comment]
@hanseul1795 If you're using app bundles, you'll be using aapt2 under the hood:

https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/app-bundles.md#aapt2

**Comment by hanseul1795** [comment]
@JonDouglas you mean `<AndroidUseAapt2            Condition=" '$(AndroidPackageFormat)' == 'aab' ">False</AndroidUseAapt2>` this line won't work if I'm using app bundles?

**Comment by JonDouglas** [comment]
@hanseul1795 App Bundles uses `bundletool` under the hood which requires `aapt2` to be used to generate compiled resources in a Protobuf format. 

https://developer.android.com/studio/command-line/bundletool

https://developer.android.com/studio/command-line/aapt2

So in your case, I would believe that aapt2 is being used and throwing that error due to what I previously described with the behavior between the old aapt and the new aapt2 tooling.

**Comment by hanseul1795** [comment]
You were completely right @JonDouglas , I'll lose this issue, Thank you!
