### ISSUE TITLE
Writing to System.IO.Stream doesn't work for SAF Google Drive URI

### ISSUE THREAD

**Issue by mrjfalk** [xamarin/xamarin-android#3498]
### Steps to Reproduce

1. Use Storage Access Framework API to create a new file in Google Drive. Intent I use:
```csharp
Intent intent = new Intent(Intent.ActionCreateDocument);
intent.AddCategory(Intent.CategoryOpenable);
intent.SetType("*/*");
intent.PutExtra(Intent.ExtraTitle, "MyFile.ext");
etc...
```

2. Get the URI for the created file, e.g. content://com.google.android.apps.docs.storage/document/&lt;documentIdentifier&gt;

3. Get an output stream to this file:
```csharp
using(Stream stream = Application.Context.ContentResolver.OpenOutputStream(Android.Net.Uri.Parse(Path)))
{
…
}
```

4. Write to the stream:
```csharp
byte[] data = Encoding.UTF8.GetBytes("Test string...");
stream.Write(data, 0, data.Length);
```

### Expected Behavior
The file should contain the string "Test string...".

### Actual Behavior
The file in Google Drive is empty (0 KB). No exception is thrown either.

### Workaround
As mentioned in the answer here: https://stackoverflow.com/questions/48876846/store-file-with-the-storage-access-framework-on-google-drive writing to the stream as a Java `BufferedOutputStream` actually works:
```csharp
using(Stream stream = Application.Context.ContentResolver.OpenOutputStream(Android.Net.Uri.Parse(Path)))
{
    using (var javaStream = new global::Java.IO.BufferedOutputStream(stream))
    {
        byte[] data = Encoding.UTF8.GetBytes("Test string...");
        javaStream.Write(data, 0, data.Length);
        javaStream.Close();
     }
}
```

The `javaStream.Close()` is required, otherwise nothing is written here either.
                    

### Version Information
Xamarin.Android SDK 9.4.1.0

### Log File
Could not find anything interesting at all in Logcat when executing the writing using System.IO.Stream.

**Comment by mrjfalk** [comment]
If anyone else has the same issue and wants to still use System.IO.Stream (e.g. in shared code), a class such as this seems to work fine:

```csharp
internal class AndroidOutputStream : Stream
    {
        public override bool CanRead => false;

        public override bool CanSeek => false;

        public override bool CanWrite => true;

        public override long Length => throw new NotImplementedException();

        public override long Position { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

        private Java.IO.BufferedOutputStream _stream;

        public AndroidOutputStream(Java.IO.BufferedOutputStream javaStream)
        {
            _stream = javaStream;
        }

        public override void Flush()
        {
            _stream?.Flush();
        }

        public override void Close()
        {
            _stream?.Close();
            base.Close();
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            throw new NotImplementedException();
        }

        public override long Seek(long offset, SeekOrigin origin)
        {
            throw new NotImplementedException();
        }

        public override void SetLength(long value)
        {
            throw new NotImplementedException();
        }

        public override void Write(byte[] buffer, int offset, int count)
        {
            _stream.Write(buffer, offset, count);
        }
    }
```

And then just using it as:
```csharp
Stream stream = new AndroidOutputStream(new Java.IO.BufferedOutputStream(Application.Context.ContentResolver.OpenOutputStream(googleDriveUri))))
```

**Comment by brendanzagaeski** [comment]
*Release status update*

Many thanks for submitting this issue! A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published for macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
