### ISSUE TITLE
Android.Bluetooth.ProfileType not up to date with Android Q

### ISSUE THREAD

**Issue by striboldt** [xamarin/xamarin-android#3508]
### Steps to Reproduce

1. Build with preview release of Android Q SDK (9.0.99) together with AndroidX preview version 02
2. ProfileType does not contain enum value Hearing_Aids as stated in Android SDK: https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#getProfileProxy(android.content.Context,%20android.bluetooth.BluetoothProfile.ServiceListener,%20int)

### Expected Behavior
Able to lookup ProfileType.HearingAid
### Actual Behavior
ProfileType only maps:

```
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.Headset", JniField = "android/bluetooth/BluetoothProfile.HEADSET")] Headset = 1,
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.A2dp", JniField = "android/bluetooth/BluetoothProfile.A2DP")] A2dp = 2,
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.Health", JniField = "android/bluetooth/BluetoothProfile.HEALTH")] Health = 3,
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.Gatt", JniField = "android/bluetooth/BluetoothProfile.GATT")] Gatt = 7,
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.GattServer", JniField = "android/bluetooth/BluetoothProfile.GATT_SERVER")] GattServer = 8,
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.Sap", JniField = "android/bluetooth/BluetoothProfile.SAP")] Sap = 10, // 0x0000000A
    [IntDefinition("Android.Bluetooth.IBluetoothProfile.HidDevice", JniField = "android/bluetooth/BluetoothProfile.HID_DEVICE")] HidDevice = 19, // 0x00000013
```

### Version Information

=== Visual Studio Professional 2019 for Mac ===

Version 8.2.3 (build 16)
Installation UUID: 9e93df9f-eb23-409b-8a14-9ad3332af677
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.14.0.85 (d16-2-fix-mac-updates / 86973979)

	Package version: 600000319

=== Mono Framework MDK ===

Runtime:
	Mono 6.0.0.319 (2019-02/52203786470) (64-bit)
	Package version: 600000319

=== NuGet ===

Version: 5.1.0.6013

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.5
	2.2.2
	2.1.11
	2.1.9
SDK: /usr/local/share/dotnet/sdk/2.2.300/Sdks
SDK Versions:
	2.2.300
	2.2.104
	2.1.700
	2.1.505
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.0.0/lib/mono/msbuild/Current/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.11
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.3 (14492.2)
Build 10G8

=== Xamarin.Mac ===

Version: 5.14.0.114 (Visual Studio Professional)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:06-0400

=== Xamarin.iOS ===

Version: 12.14.0.114 (Visual Studio Professional)
Hash: c6691164
Branch: d16-2
Build date: 2019-07-29 15:54:05-0400

=== Xamarin.Android ===

Version: 9.4.1.0 (Visual Studio Professional)
Commit: xamarin-android/d16-2/ebd65c9
Android SDK: /Users/mstr/Library/Android/sdk
	Supported Android versions:
		5.0 (API level 21)
		7.0 (API level 24)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-02@e6f5369c2d2
Java.Interop: xamarin/java.interop/d16-2@d64ada5
LibZipSharp: grendello/LibZipSharp/d16-2@caa0c74
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-2@6f6c969

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/mstr/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.60
Hash: 686c817
Branch: remotes/origin/d16-2
Build date: 2019-08-07 15:49:58 UTC

=== Xamarin Designer ===

Version: 16.2.0.379
Hash: 3f0652957
Branch: remotes/origin/d16-2
Build date: 2019-08-01 17:32:50 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 802030016
Git revision: f438e4b3ac81dbc614da2f2d9ac3c70ea2e5c350
Build date: 2019-08-09 09:07:01+00
Build branch: release-8.2
Xamarin extensions: 67f026710e882e318fb0c90077b429be3dc0e688

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.0.99.100 and 10.1.0.1.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1 and 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
