### ISSUE TITLE
Provide way to sign package/bundle with custom keyfile without writing passphrase to log

### ISSUE THREAD

**Issue by mungojam** [xamarin/xamarin-android#3513]
When I run `msbuild` with `/t:SignAndroidPackage` and provide a custom keystore, the keystore and key passwords end up being written out to the build log because it logs the call made to `jarsigner` / `apksigner`.

I wanted to prevent the passwords being written to the log, so I have ended up doing the signing as a separate step. In this step I make use of the `:env` the suffix in `jarsigner` or the `env:` prefix in `apksigner` before I switched to bundles.

Below is what my build looks like now. `AndroidSigning_StorePass` is an environment variable that I populate in a pre-build step with the password:

```
    commands:
       - msbuild MyProj/MyProj.csproj /restore
         /p:Configuration=Release
         /p:AndroidSdkDirectory=/android/sdk
         /t:Package
       - jarsigner -sigalg SHA256withRSA -digestalg SHA-256
         -keystore ../my.keystore
         -keypass:env AndroidSigning_StorePass
         -storepass:env AndroidSigning_StorePass
         -signedjar ./MyProj/bin/Release/com.me.myapp-Signed.aab
         ./MyProj/obj/Release/android/bin/com.me.myapp.aab $AndroidSigning_KeyAlias
```

The above seems to work fine, but it took a lot of effort to get there. It would be better if I could use the standard build target but still keep the sensitive data out of the log. Then I wouldn't need to do the custom signing and could benefit from any future tweaks that you put in the standard build target.

**Comment by dellis1972** [comment]
@mungojam Thanks for the bug report, I will take a look at adding a couple of new MSBuild properties which will provide the `env` and `file` versions of the `-keypass` and `-storepass` command line arguments. 

In fact it might be easier to allow the user to do something like 

`/p:AndroidSigningStorePass=env:Foo` //use an EnvVar
`/p:AndroidSigningStorePass=file:Foo` // use a File
`/p:AndroidSigningStorePass=Foo` // use Foo

we can then just parse those values in the task an use the correct argument.

**Comment by mungojam** [comment]
> In fact it might be easier to allow the user to do something like

> /p:AndroidSigningStorePass=env:Foo //use an EnvVar
/p:AndroidSigningStorePass=file:Foo // use a File
/p:AndroidSigningStorePass=Foo // use Foo

> we can then just parse those values in the task an use the correct argument

happy with that solution for my own use. It does rely on people not happening to start their passwords with `env:` or `file:` though, unlikely but not implausible. I expect the same issue affects the underlying keytool though. Up to you :)

**Comment by dellis1972** [comment]
Yup, if you have env: or file: in your password that would be a problem lol.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published on Windows that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by mungojam** [comment]
Thanks, I actually need it for the Linux build of android which I fetch off Jenkins as part of a docker image. But that Linux build has been failing since earlier this year

https://github.com/xamarin/xamarin-android/issues/2009

**Comment by mrk-han** [comment]
Hey @mungojam , we are also seeking the Android.Xamarin.Linux build and just noticed it has been failing for sometime now. Have you received any communication on this? The main build looks like it is just failing to communicate to Github... https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/

**Comment by mungojam** [comment]
I've not heard anything on it unfortunately

**Comment by brendanzagaeski** [comment]
I'll aim to raise a question with team about whether there are plans to enable the Linux continuous build job again in the future.

For the moment, I'll add an update for the Windows and macOS packages.

*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by mrk-han** [comment]
>I'll aim to raise a question with team about whether there are plans to enable the Linux continuous build job again in the future.

Any word back on this? Thanks @brendanzagaeski

**Comment by brendanzagaeski** [comment]
Apologies for the slow reply. I found out that there is some work in progress to see about making .deb packages available again for more recent Xamarin.Android commits, but the timeline for availability isn't yet known. I'll stay in the loop on that work and update #2009 and #4116 when there's news.
