### ISSUE TITLE
How can I use interpreter in xamarin android

### ISSUE THREAD

**Issue by ysmoradi** [xamarin/xamarin-android#3521]
I'm able to use mono interpreter in wasm and xamarin iOS, but I don't know how to achieve the same in xamarin android. What should I do? Thanks in advance.

**Comment by jonpryor** [comment]
Why would you need to use the interpreter?  wasm and Xamarin.iOS need an interpreter because their environments do not support JIT use, which requires the ability to execute previously written-to memory.  (iOS is a W^X environment, so if memory can be written to it *cannot* ever be executed, which prevents normal JIT semantics.  I believe wasm has a similar constraint.)

The mono interpreter is not currently built for Android, but if you're willing to rebuild mono from source, you should be able to enable it.  (*Using* it is another matter entirely; I have no idea how to enable its use.)

Compare the `--enable-minimal` configure flags:

* iOS: https://github.com/mono/mono/blob/38c524cc2ad83001b3b2be28e9c7f25cbc126ca2/sdks/builds/ios.mk#L102
* Android: https://github.com/mono/mono/blob/38c524cc2ad83001b3b2be28e9c7f25cbc126ca2/sdks/builds/android.mk#L144

Note that Android doesn't currently specify `interpreter`.  At minimum, this would need to be changed, though I have no idea what else would need to change as well.

**Comment by ysmoradi** [comment]
In [mono 6.0](https://www.mono-project.com/docs/about-mono/releases/6.0.0/#interpreter) there are some attentions to interpreter performance. I was interested in testing that in my android apps to see if there any kind of performance improvements.
In Xamarin.iOS I'm able to add/remove interpreter easily. The same approach could be taken in Xamarin.Android project.
Thanks in advance.

**Comment by jpobst** [comment]
`$(UseInterpreter)` should now be functional (and the default for Debug apps) in .NET 6 Android:
https://github.com/xamarin/xamarin-android/pull/6843
