### ISSUE TITLE
Fast deploy of wearable project has regressed between d16-3 Preview 2 and Preview 3

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#3562]
Our fastdev support has regressed for wearable project types between d16-3 Preview 2 and Preview 3.

### Steps to Reproduce

1. Download and restore NuGets for: https://github.com/xamarin/monodroid-samples/tree/master/wear/DelayedConfirmation.
2. msbuild /t:Install DelayedConfirmationApp\DelayedConfirmationApp.csproj
3. msbuild /t:Install DelayedConfirmationApp\DelayedConfirmationApp.csproj

### Expected Behavior
Second deploy with no code changes should be fast.

### Actual Behavior
Second deploy with no code changes results in the .apk being rebuilt.

The issue appears to have been introduced somewhere in this diff: http://github.com/xamarin/xamarin-android/compare/21a650c170483a1ac99e1c4bf80d7ef3158ab281...489f2580373b0ddb2e1268a159e3eb935b2871a5

### Version Information
d16-3 Preview 3

### Log File
[Binary logs for good and bad incrementalinstall attempts](https://github.com/xamarin/xamarin-android/files/3556349/binlogs.zip)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included in Xamarin.Android 10.0.99.100.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 1. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published for macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.0.1.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
