### ISSUE TITLE
Creation of `libxamarin-app.so` fails on macOS Catalina due to usage of 32bit link tool

### ISSUE THREAD

**Issue by pjcollins** [xamarin/xamarin-android#3564]
### Steps to Reproduce

1. Attempt to build/package an XA project on macOS Catalina Beta 7.

### Expected Behavior
On Catalina, we'll need to ensure our build processes use the link/strip tools that we are re-distributing, rather than the ones from `$(AndroidSDK)/build-tools/*`.

### Actual Behavior
```
Task Parameter:AndroidSdkBuildToolsPath=/Users/user/Library/Developer/Xamarin/android-sdk-macosx/build-tools/28.0.3/ (TaskId:273)
  [Native Linker] /Users/user/Library/Developer/Xamarin/android-sdk-macosx/build-tools/28.0.3/aarch64-linux-android-ld --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -o obj/Release/app_shared_libraries/arm64-v8a/libxamarin-app.so --fix-cortex-a53-843419 -m aarch64linux obj/Release/android/typemap.jm.arm64-v8a.o obj/Release/android/typemap.mj.arm64-v8a.o obj/Release/android/environment.arm64-v8a.o (TaskId:273)
  [Native Linker] /Users/user/Library/Developer/Xamarin/android-sdk-macosx/build-tools/28.0.3/arm-linux-androideabi-ld --unresolved-symbols=ignore-in-shared-libs --export-dynamic -soname libxamarin-app.so -z relro -z noexecstack --enable-new-dtags --eh-frame-hdr -shared --build-id --warn-shared-textrel --fatal-warnings -o obj/Release/app_shared_libraries/armeabi-v7a/libxamarin-app.so -X -m armelf_linux_eabi obj/Release/android/typemap.jm.armeabi-v7a.o obj/Release/android/typemap.mj.armeabi-v7a.o obj/Release/android/environment.armeabi-v7a.o (TaskId:273)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2869,3): error XA3001: Could not link native shared library: libxamarin-app.so [/Users/user/Library/Caches/xqatmp/e0dd2595/Android/WorkingWithStyles.Android.csproj]
Done executing task "LinkApplicationSharedLibraries" -- FAILED. (TaskId:273)
```

### Version Information
d16-3 and master

### Log File
http://xqa.blob.core.windows.net/gist/log-6288f3af2576434780150fb813d5907b.txt

> VS bug [#976943](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/976943)

**Comment by brendanzagaeski** [comment]
A new Preview version has now been published that includes a fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.0.0.43.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included in Xamarin.Android 10.0.0.43

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(The fix is not relevant for Windows.)

**Comment by xhashimks** [comment]
@brendanzagaeski Still issue occurs after upgrading.. my Mac VS version is 8.4 and XA is 10.2.0

**Comment by brendanzagaeski** [comment]
@xhashimks, thanks for the info! When you get a chance, if you could submit a new issue with additional details about your scenario, including the diagnostic build output or possibly an example project, so that the team can take a look, that would be perfect.

Thanks in advance!
