### ISSUE TITLE
Project build error in Visual Studio 2019

### ISSUE THREAD

**Issue by VictorKochetkov** [xamarin/xamarin-android#3571]
Project build error with:
`Xamarin.Android.Common.targets: error MSB6006: "java.exe" exited with code 1.` 
or 
`Xamarin.Android.D8.targets: error MSB6006: "java.exe" exited with code 1` 
depending on Proguard or R8 enabled.

Same project successfully built in Visual Studio 2017.

No more logs are appears in build output. **Diagnostics** option is selected in Visual Studio settings.

Visual Studio 2019: _16.2.3_
Visual Studio 2017: _15.9.13_

**Comment by grendello** [comment]
@VictorKochetkov would you mind attaching the diagnostic build log you mentioned? The error you quote doesn't give us much, alas, there's more information surrounding it in the log. Alternatively, you could try building your application from the developer prompt by issuing this command:

```
msbuild /bl /t:"Restore;SignAndroidPackage"
```

which will generate a binary log file, `msbuild.binlog`, that you could please attach to this issue, thanks!

**Comment by AigioL** [comment]
I have the same problem
Xamarin.Android.D8.targets(81,5): error MSB6006: “java.exe”已退出，代码为 1。

Here is a sample project:
[IMApp.7z](https://1drv.ms/u/s!Ajh9GPemv07wuV4BW5-wBgakswAI?e=yQ3VTT)
[msbuild.binlog](https://1drv.ms/u/s!Ajh9GPemv07wuV1goNo_X7gaoWM9?e=HhQ8Ru)

**Version Information**

Microsoft Visual Studio Enterprise 2019
16.3.1
VisualStudio.16.Release/16.3.1+29324.140
Microsoft .NET Framework
4.8.03761

Enterprise

Xamarin   16.3.0.274 (d16-3@06531f8)

Xamarin Designer   16.3.0.230 (remotes/origin/d16-3-xcode11@bbe518670)

Xamarin Templates   16.3.565 (27e9746)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.0.0.43 (d16-3/8af1ca8)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2019-06@7af64d1ebe9
    Java.Interop: xamarin/java.interop/d16-3@5836f58
    LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333


Xamarin.iOS and Xamarin.Mac SDK   13.2.0.42 (5e8a208)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by dellis1972** [comment]
Looking at the build log the error is as follows

```
 Error in proguard.cfg at line 1, column 1:
 Expected char '-' at proguard.cfg:1:1
```

could you attach the pro guard.cfg file so we can investigate?

```
ProguardConfigurationFiles=
		{sdk.dir}tools\proguard\proguard-android.txt;
		{intermediate.common.xamarin};
		{intermediate.references};
		{intermediate.application};
		proguard.cfg;
```

it looks like there are invalid characters in that file which java does not support.

**Comment by AigioL** [comment]
@dellis1972 
[proguard.zip](https://github.com/xamarin/xamarin-android/files/3681405/proguard.zip)

**Comment by jonathanpeppers** [comment]
I think you need to remove the BOM (byte-order mark), here is what VS Code shows:

![image](https://user-images.githubusercontent.com/840039/66052100-a651a600-e4f5-11e9-9fd5-70a73c10dbe0.png)

You can click this, and then choose `Save with Encoding`:

![image](https://user-images.githubusercontent.com/840039/66052158-c08b8400-e4f5-11e9-94e6-4959cb65b1b4.png)

Then choose `UTF-8`.

You might consider using an `.editorconfig` file for `*.cfg` files, this setting removings BOMs on save in Visual Studio proper: https://github.com/xamarin/xamarin-android/blob/0134c2fb20f2f20127b24ef49177d9fe8226efdb/.editorconfig#L7-L9

**Comment by dellis1972** [comment]
I added a PR to make sure we raise the correct proguard errors https://github.com/xamarin/xamarin-android/pull/3733.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the improved error message for this scenario. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.1.0.29.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by jitendrajadav** [comment]
I have still this issue please check
here is the log: 

`1>------ Rebuild All started: Project: KegID, Configuration: Release Any CPU ------
1>ViewModel\BaseViewModel.cs(84,35,84,50): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
1>KegID -> C:\Users\jdj1\Source\Repos\SatelliteLogisticsGroup\kegid-x\KegID\KegID\bin\Release\netstandard2.0\KegID.dll
1>Done building project "KegID.csproj".
2>------ Rebuild All started: Project: KegID.Android, Configuration: Release Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(594,3): warning XA0119: Using Fast Deployment and a Code Shrinker at the same time is not recommended. Use Fast Deployment for Debug configurations and a Code Shrinker for Release configurations.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(598,3): warning XA0119: Using Fast Deployment and Android App Bundles at the same time is not recommended. Use Fast Deployment for Debug configurations and Android App Bundles for Release configurations.
2>C:\Users\jdj1\Source\Repos\SatelliteLogisticsGroup\kegid-x\KegID\KegID.Android\FodyWeavers.xml : warning XA0101: @(Content) build action is not supported
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>  KegID.Android -> C:\Users\jdj1\Source\Repos\SatelliteLogisticsGroup\kegid-x\KegID\KegID.Android\bin\Release\KegID.Android.dll
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Xamarin\Android\Xamarin.Android.D8.targets(81,5): error MSB6006: "java.exe" exited with code 1.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
`
![image](https://user-images.githubusercontent.com/1029026/70140951-e8e15b80-16bb-11ea-8f8a-2fcb25f1ac9b.png)

**Comment by jonathanpeppers** [comment]
@jitendrajadav can you file a new issue with a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output)? Thanks!

The log is truncated, so no way to tell what the actual error is.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item, as was [published earlier](https://github.com/xamarin/xamarin-android/issues/3571#issuecomment-561442497) on Windows.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by zipswich** [comment]
Had this error today.  Changing android:targetSdkVersion from 28 to 29 fixed it.
