### ISSUE TITLE
Hebrew and other non-Gregorian calendars are broken

### ISSUE THREAD

**Issue by jonpryor** [xamarin/xamarin-android#3580]
See: https://github.com/mono/mono/issues/16623

VS bug [#976811](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/976811)

**Comment by brendanzagaeski** [comment]
A new Preview version has now been published that includes a [partial fix for the Hebrew calendar](https://github.com/mono/mono/commit/2c3aeaf3780de7392a0d3cbe4dcf86846eb4dffa). The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.0.0.43.

Fix included on Windows in Visual Studio 2019 version 16.3 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.3 Preview 5. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the [partial fix for the Hebrew calendar](https://github.com/mono/mono/commit/2c3aeaf3780de7392a0d3cbe4dcf86846eb4dffa).

Fix included in Xamarin.Android 10.0.0.43.

Fix included on Windows in Visual Studio 2019 version 16.3. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.3. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by jpobst** [comment]
This is tracked in the Mono repo: https://github.com/mono/mono/issues/16623.

Closing as duplicate.
