### ISSUE TITLE
PeriodicWorkRequest not running as expected

### ISSUE THREAD

**Issue by jrahma** [xamarin/xamarin-android#3610]
Hi,

In the attached sample, I have created a @JonDouglas [PeriodicWorkRequest](https://devblogs.microsoft.com/xamarin/getting-started-workmanager/) to be running every 30 minutes

I have logged the DoWork in my AppCenter Analytics and I am getting the DoWork when I start the app but not every 30 minutes. For example, today I started the app and I got the DoWork logged but after that and until now (more than 2 hours) nothing is logged.

![image](https://user-images.githubusercontent.com/6236241/64602203-66544300-d3cf-11e9-8432-3fc5853c5dbd.png)

[LocalNotifications.zip](https://github.com/xamarin/xamarin-android/files/3594864/LocalNotifications.zip)

Thanks,
[Jassim](https://www.softnames.com)

**Comment by dellis1972** [comment]
@jrahma I tested your app locally I saw this in the adb logcat.  

```
[WM-WorkerWrapper] Work [ id=eb6ac16d-997c-41ed-983e-c973f72fbc22, tags={ md5b5c6a9a7089893aa468c5d39027034b6.AthanTime } ] was cancelled
[WM-WorkerWrapper] java.util.concurrent.CancellationException: Task was cancelled.
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1184)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:514)
[WM-WorkerWrapper] 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
[WM-WorkerWrapper] 	at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:289)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[WM-WorkerWrapper] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[WM-WorkerWrapper] 	at java.lang.Thread.run(Thread.java:764)
System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: value
  at System.DateTime.AddTicks (System.Int64 value) [0x0001c] in <492bf9a8d40a4127a2682b6964cbb669>:0 
  at System.DateTime.Add (System.Double value, System.Int32 scale) [0x0004f] in <492bf9a8d40a4127a2682b6964cbb669>:0 
  at System.DateTime.AddSeconds (System.Double value) [0x00000] in <492bf9a8d40a4127a2682b6964cbb669>:0 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.NotifyTimeInMilliseconds (System.DateTime notifyTime) [0x00027] in <aabb58ca159d43679c65a0a71fdb9c2a>:0 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.ShowLater (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x00039] in <aabb58ca159d43679c65a0a71fdb9c2a>:0 
  at Plugin.LocalNotification.Platform.Droid.NotificationServiceImpl.Show (Plugin.LocalNotification.NotificationRequest notificationRequest) [0x00030] in <aabb58ca159d43679c65a0a71fdb9c2a>:0 
Thread finished: <Thread Pool> #6
```

Which suggests there is something wrong with the way the various date time values are formatted.
The `Task was cancelled.` message means your background task was cancelled probably due to the issues with the dates. As a result you will not get any further tasks running.

Also looking at your code you have 

```
Task.Run(async () => 
```

but that is not awaited. So the code below it will start executing probably before that Task.Run completes. Since you use the values set in that Task.Run later in the code, I suspect you wanted that code to run before continuing with the rest of the code below it.

**Comment by dellis1972** [comment]
@JonDouglas do you have any ideas on this one? I commented out all the code which might cause a problem and the tasks only run when the app starts, and never again until you restart the app..

**Comment by jrahma** [comment]
@dellis1972 @JonDouglas 

Is there any solution for this guys? 

is it going to be fixed in the coming release?

**Comment by JonDouglas** [comment]
@dellis1972 Tasks have a minimum of 15 minutes to reoccur. So perhaps you may have tried less than that?

@jrahma The example provided in https://devblogs.microsoft.com/xamarin/getting-started-workmanager/ should work. It is very possible there is a bug somewhere in your code as dean mentioned earlier. Perhaps you can add more logging around your code to see where it may be failing and log them as you catch the exceptions.

I used your app, but ported over my sample to avoid excess code and it worked fine on the latest builds:

```
10-16 12:46:17.306 D/CalculatorWorker( 5465): Your Tax Return is: 2000
10-16 12:46:17.307 I/WM-WorkerWrapper( 5465): Worker result SUCCESS for Work [ id=a0e47988-a221-43af-a022-b1ebe5158992, tags={ md5b5c6a9a7089893aa468c5d39027034b6.CalculatorWorker } ]
```
->
```
10-16 13:01:52.907 D/CalculatorWorker( 5465): Your Tax Return is: 2000
10-16 13:01:52.909 I/WM-WorkerWrapper( 5465): Worker result SUCCESS for Work [ id=c429da6b-a981-4c4f-af74-1f8d27157689, tags={ md5b5c6a9a7089893aa468c5d39027034b6.CalculatorWorker } ]
```

**Comment by jrahma** [comment]
@JonDouglas it is still not working. Here is the updated project with updated releases

If you log the PeriodicWorkRequest into AppCenter's Event for example you'll see that it only fires one time when you open the app.. every time I close the app (kill the app) and start it again then the PeriodicWorkRequest will be fired but it will never run every 30 minutes although the timer is set for 30 minutes:

`PeriodicWorkRequest taxWorkRequest = PeriodicWorkRequest.Builder.From<AthanTime>(TimeSpan.FromMinutes(30)).Build();
`

Does this have anything to do with devices? I am using Honor 10 Lite


[LocalNotifications.zip](https://github.com/xamarin/xamarin-android/files/3738110/LocalNotifications.zip)

**Comment by jrahma** [comment]
This is AppCenter log, I left the App for 3 hours but the PeriodicWorkRequest only fired when I manually started the app 3 times but not every 30 minutes as expected

![image](https://user-images.githubusercontent.com/6236241/67002872-d8febf80-f0ed-11e9-897b-8cb3487509c1.png)

**Comment by jrahma** [comment]
@JonDouglas I tried it on emulator too but same issue. Emulator was running for almost 4 hours but only got the log when I start the app

**Comment by dellis1972** [comment]
@jrahma I found the problem.

The local LocalNotifications Plugin uses the `WorkManager` to provide times notifications. The PeriodicWorkRequest also uses the `WorkManager`. 

In your code you have the following line

```
NotificationCenter.Current.CancelAll ();
```

This is going to call `Cancel` on all the items registered in the `WorkManager` including your PeriodicWorkRequest. So the very first time the code runs it cancels everything.  This is why we see

```
Work [ id=eb6ac16d-997c-41ed-983e-c973f72fbc22, tags={ md5b5c6a9a7089893aa468c5d39027034b6.AthanTime } ] was cancelled
```
in the log. 

What you should do is call

```
NotificationCenter.Current.Cancel (x);
```

Where `x` is the NotificationId which use use for each of your `NotificationRequest` items. 
You will need to call `Cancel` for each item, so in this case 3 times. This way you only cancel the work items you are creating rather than everything.

I am going to close this issue since its not a problem within Xamarin.Android itself. Please reopen it if it if that is not the case.
