### ISSUE TITLE
Possible memory leak when Activity.Recreate() is called

### ISSUE THREAD

**Issue by ghost** [xamarin/xamarin-android#3706]
I noticed that every time that `Activity.Recreate()` is called, the application uses more memory. The attached project is just a File>New Project with a method that calls `Activity.Recreate()`. If you recreate the main activity some times it's possible to see that it will have more than 350k objects allocated. That's a lot for an app with just a button and a label. 

The application that I was working is bigger than this sample, it has 270k objects allocated when running, and if I try to recreate the main activity some times, it will throw an OutOfMemoryException. 

I also created an Android project using Android Studio, and the garbage collector is releasing the objects after recreating the main activity. 

![Screenshot (4)](https://user-images.githubusercontent.com/55998414/65907222-fb74a700-e391-11e9-991a-f66101280a70.png)

### Steps to Reproduce

1. Build the attached project and use Android Device Monitor to check number of allocated objects;
2. Tap the FAB to invoke `Activity.Recreate()` method;
3.  Use "Cause GC" button on Android Device Monitor to see the number of objects increasing every time that the activity is recreated.

[ActivityRecreateTest.zip](https://github.com/xamarin/xamarin-android/files/3672698/ActivityRecreateTest.zip)

### Expected Behavior
The application should not keep increasing the number of objects every time `Activity.Recreate()` is called.

### Actual Behavior
Number of objects increasing each time `Activity.Recreate()` is called.

### Version Information

Microsoft Visual Studio Professional 2017 
Version 15.9.16
VisualStudio.15.Release/15.9.16+28307.858
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Professional

Visual C++ 2017   00370-20004-14070-AA177
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   15.9.03024.0
Azure Functions and Web Jobs Tools

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.20417.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.13.12-pre (9bc9548)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61906.03120
Microsoft SQL Server Data Tools

TypeScript Tools   15.9.30718.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28307.858
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.12.3.83 (d15-9@23fa80172)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.16.30 (e0af99a34)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.128 (6f5ebb2)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.1.7.0 (HEAD/ba9da7a76)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.4.0.64 (9c8d8e0)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by jonpryor** [comment]
I suspect that there is an issue in Android, but cannot currently prove it.

Related: https://github.com/xamarin/java.interop/commit/68062a72cb9edb9fd8d6bc25e6ae8b8055732d2a

Rational:

 1. Build & Install [`ActivityRecreateTest.zip`](https://github.com/xamarin/xamarin-android/files/3672698/ActivityRecreateTest.zip):

    ```bash
    $ cd path/to/ActivityRecreateTest
    $ msbuild /t:Restore
    $ nuget restore ActivityRecreateTest.sln
    $ cd ActivityRecreateTest
    $ msbuild /restore /t:Install
    ```

 2. Enable [GREF logging](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#global-reference-messages):

        adb shell setprop debug.mono.log gref,gc

 3. Run the app:

        msbuild /t:_Run

 4. Within the app, tap the FloatingActionButton ~100 times.

 5. Grab the GREF log from the device:

        adb shell run-as ActivityRecreateTest.ActivityRecreateTest cat files/.__override__/grefs.txt > grefs.txt

`grefs.txt` contains a log of every JNI Global Reference created and destroyed by Xamarin.Android during the application lifetime, including those 100 FloatingActionButton clicks.

Next, obtain a `logcat-parse` with the fixes in https://github.com/xamarin/java.interop/commit/68062a72cb9edb9fd8d6bc25e6ae8b8055732d2a.  (This will be included in d16-4 P3...whenever that gets shipped.)

`logcat-parse.exe` can be used to more easily reason about `grefs.txt`:

```
$ mono /path/to/logcat-parse.exe grefs.txt
```

How many GREFs are there?

```
csharp> grefs.GrefCount;
282
```

This matches the last `+g+` line in my `grefs.txt` file, so at least they're consistent:

```
+g+ grefc 282 gwrefc 0 obj-handle 0x71/I -> new-handle 0x3dca/G from thread '(null)'(1)
```

How many objects are *alive*?

```
csharp> grefs.AlivePeers.Count();
282
```

282 peer objects are alive.  This is good; it matches the GREF count.  (If this *doesn't* match the GREF count, you have a buggy `logcat-parse.exe` *or* there's another bug in `logcat-parse.exe`...)

282 does seem rather large.  What types are there?

```
csharp> grefs.GetAliveJniTypeCounts();
{{ "", 14 },
  { "com/android/internal/os/RuntimeInit$KillApplicationHandler", 1 },
  { "android/runtime/UncaughtExceptionHandler", 1 },
  { "md5327d1d288bcaf8c0cc06d09d4b2f8e3a/MainActivity", 50 },
  { "android/support/v7/widget/Toolbar", 50 },
  { "android/support/design/widget/FloatingActionButton", 50 },
  { "android/support/v7/view/menu/MenuBuilder", 50 },
  { "android/support/v7/view/SupportMenuInflater", 50 },
  { "mono/android/view/View_OnClickListenerImplementor", 9 },
  { "android/os/Bundle", 7 }}
```

There are *50* `FloatingActionButton`, `MainActivity`, `MenuBuilder`, `SupportMenuInflater`, and `Toolbar` instances.

On the plus side, I tapped the FloatingActionButton *100* times, so apparently *half* of them were collected.  ¯\_(ツ)_/¯

That's sign number 1 that there isn't an obvious *C#-side* leak.

The next sign is that Xamarin.Android *attempted to collect* the alive peers...

```
csharp> var firstMain = grefs.AlivePeers.Where(p => p.JniType == "md5327d1d288bcaf8c0cc06d09d4b2f8e3a/MainActivity").First();
csharp> firstMain.RemovedHandles;
{ 0x7fd2e9a5d0 from thread '(null)'(1), 0x2b36/G from thread 'finalizer'(13819), 0x487/W from thread 'finalizer'(13819) }
```

`PeerInfo.RemovedHandles` contains all previously seen JNI handles for a given peer.  In this case it was previously seen on `thread 'finalizer'(13819)`, meaning it went through the C# finalization process.  The reason this instance is still alive is because *something in **Java** is keeping the instance alive*.

What I *don't* know is *what* in Java would be keeping our objects alive.

Additionally, *most* of the `MainActivity` instances still alive have gone through the finalizer at least once:

```
csharp> grefs.AlivePeers.
    Where(p => p.JniType == "md5327d1d288bcaf8c0cc06d09d4b2f8e3a/MainActivity").
    Count(p => p.RemovedHandles.Count(h => h.ToString().Contains("finalizer"))==0);
9
```

A C#-side GC hasn't been attempted on only 9 of the `MainActivity` instances.

**Comment by jonpryor** [comment]
Next steps: followup on the hypothesis that this is somehow Android/Java related.

@brendanzagaeski: Please "port" the sample to Java and see if the Java GC memory counters increase when only Java is involved.

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
