### ISSUE TITLE
ServiceAttribute is missing foregroundServiceType

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/xamarin-android#3712]
Android API 29 introduced `foregroundServiceType` on Services to classify what kind of service it is. Kind of like on iOS, for background downloads, music etc.

This attribute is needed in the AndroidManifest.xml when targeting API 29 (Android Q), when wanting to distinguish between stuff like Foreground Location updates and Background Location updates.

### Steps to Reproduce

1. Add `[Service]` to your Service class. 
2. Explore the properties exposed

### Expected Behavior

I would expect `ForegroundServiceType` and some kind of enum would be available when `TargetFrameworkVersion` is set to v10.0 in the csproj

### Actual Behavior

No ForegroundServiceType is available

### Version Information

Visual Studio Community 2019 for Mac
Version 8.3 (build 1805)

Xamarin.Android
Version: 10.0.0.43 (Visual Studio Community)
Commit: xamarin-android/d16-3/8af1ca8
Android SDK: /Users/cheesebaron/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 29.0.0

**Comment by Cheesebaron** [comment]
Workaround right now is to remove `[Service]` from your service and add it manually to the AndroidManifest.

**Comment by gugavaro** [comment]
Hi @Cheesebaron can you please provide a project that repros it?
thanks,
Gustavo.

**Comment by Cheesebaron** [comment]
[ServiceTypeTest.zip](https://github.com/xamarin/xamarin-android/files/3734154/ServiceTypeTest.zip)

I've attached a project.

Using the `ServiceAttribute` as seen on `MyService`, there is no way to specify `ForegroundServiceType` as that property does not exist.

The workaround is to manually register the service in the manifest as seen for `MyService2`.

**Comment by gugavaro** [comment]
Thank you @Cheesebaron 
I will take a look on it.

Gustavo.

**Comment by chrisfoulds** [comment]
How would I declare manually for a Xamarin forms project ? , is there an ETA for this being added ?

**Comment by Cheesebaron** [comment]
@chrisfoulds remove the `[Service]` attribute on your service and add the entry to your AndroidManifest.xml file yourself. See the attatched ServiceTypeTest.zip for an example.

**Comment by chrisfoulds** [comment]
@Cheesebaron I tried that and it didn't work which is why I asked.

I added : 
<service android:name="com.abc.testapp.TimestampService"  />

Yet the autogenerated one using [Service] comes out as :
<service android:name="md586c6802ef9432e3426afeadf29df91ef.TimestampService" />

So quite different locations

**Comment by Cheesebaron** [comment]
Add the `[Register("com.abc.testapp.TimestampService")]` on your Service.

**Comment by chrisfoulds** [comment]
@Cheesebaron thanks, worked a treat  wasn't aware of that one.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.2.0.84.

Fix included on Windows in Visual Studio 2019 version 16.5 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by unamed000** [comment]
I'm not able to find this attribute in the latest stable version of Xamarin.Android. Anyone has any ideas?
