### ISSUE TITLE
Conflicts Between different version os Microdoft.Csharp

### ISSUE THREAD

**Issue by Tonislau** [xamarin/xamarin-android#3761]
Warning:

Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	CXApp.Android

**Comment by grendello** [comment]
@Tonislau please attach the full build log, we need to know the context in which the messages appear, thanks!

**Comment by jonathanpeppers** [comment]
@Tonislau let us know if you can send a build log and we can reopen, thanks!

**Comment by kvpt** [comment]
I also encounter this issue since a long time.
I think it is easy to reproduce.
For my case, I have a NetStandard project with a reference to Microsoft.CSharp (because I have to catch RuntimeBinderException from Json.Net).
And I reference this project in the Android project.
In this case when the Android project build, MsBuild report a warning MSB3277.

**Comment by jonathanpeppers** [comment]
@kvpt can you file a new issue with a small sample project, thanks!
