### ISSUE TITLE
Target _Gdb not found in project

### ISSUE THREAD

**Issue by m93a** [xamarin/xamarin-android#3778]
### Steps to Reproduce

1. Fetch a sample project:
```bash
git clone git@github.com:xamarin/monodroid-samples.git
cd monodroid-samples/Button
```
2. Build and deploy it
```bash
emulator @Nexus &
msbuild /t:Build,Install
```
3. Attach GDB and run the app
```bash
msbuild /t:_Gdb
```

### Expected Behavior
An app connected to `gdb` should start up in the emulator, like described in [the docs](https://docs.microsoft.com/cs-cz/xamarin/android/deploy-test/gdb).

### Actual Behavior
Build fails, saying that the target `_Gdb` doesn't exist.
```
Project "monodroid-samples/Button/DroidButton.sln" on node 1 (_Gdb target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "monodroid-samples/Button/DroidButton.sln" (1) is building "monodroid-samples/Button/DroidButton.csproj" (2) on node 1 (_Gdb target(s)).
monodroid-samples/Button/DroidButton.csproj : error MSB4057: The target "_Gdb" does not exist in the project.
Done Building Project "monodroid-samples/Button/DroidButton.csproj" (_Gdb target(s)) -- FAILED.
Done Building Project "monodroid-samples/Button/DroidButton.sln" (_Gdb target(s)) -- FAILED.

Build FAILED.

"monodroid-samples/Button/DroidButton.sln" (_Gdb target) (1) ->
"monodroid-samples/Button/DroidButton.csproj" (_Gdb target) (2) ->
  monodroid-samples/Button/DroidButton.csproj : error MSB4057: The target "_Gdb" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.76

```

### Version Information
 * elementaryOS 5.0 (based on Ubuntu 18.04.2)
 * Mono 6.4.0.198
 * MSBuild 16.3.0-ci for Mono
 * Xamarin.Android 10.0.0.43 (built with `make jenkins`, [details here](https://askubuntu.com/questions/1177970/how-to-develop-for-android-with-xamarin))
 * gdb (Ubuntu 8.1-0ubuntu3.1) 8.1.0.20180409-git

### Log File
N/A

**Comment by dellis1972** [comment]
You have to pass the path to the `csproj` for the `_Gdb` target to work. This is the same for all the custom Xamarin.Android targets. When you just call `msbuild` it will default to building the solution and MSBuild will not find the required targets.

So try this instead.

`msbuild monodroid-samples/Button/DroidButton.csproj /t:_Gdb`

**Comment by dellis1972** [comment]
or

`msbuild DroidButton.csproj /t:_Gdb`

of you are already in the `monodroid-samples/Button` directory.

**Comment by dellis1972** [comment]
@jonathanpeppers generally our debugging support is close source. The _Gdb target itself depends on a bunch of things that depend on AndroidTools which is not open sourced.

**Comment by brendanzagaeski** [comment]
### Background info

 1. I think @jonathanpeppers was getting at this, but just to make sure we're all clear, this report is about using an open source build that the reporter built and ran locally on:

    > elementaryOS 5.0 (based on Ubuntu 18.04.2)

    So invoking `msbuild` on the *.csproj* file won't change the error message. If m39a runs the following command:

    ```
    msbuild monodroid-samples/Button/DroidButton.csproj /t:_Gdb
    ```

    They will still see the same error:

    ```
    error MSB4057: The target "_Gdb" does not exist in the project.
    ```

    Because the open source build does not include the `_Gdb` target.

 2. That said, the fact that the open source build does not include the `_Gdb` target is arguably a good thing. After working on the related, though primarily contributor-focused, [*Development tips and native debugging*](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md) document earlier this year, I had the understanding that the `_Gdb` target was no longer maintained and should likely be removed in a future round of code cleanup.

    In particular, https://github.com/xamarin/xamarin-android/commit/d80b485bcbc6dff29dbd79aa2423f283dd62c60a removed the `gdbserver` binary from debug APKs and removed support for launching the `gdbserver` binary via the *libmono-android* runtime.

    So the `_Gdb` target doesn't work in commercial builds on macOS or Windows right now either.

    It is still possible to debug Xamarin.Android apps from the [command line using GDB](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md#attaching-gdb-on-the-command-line-on-windows-or-macos), but since most Xamarin.Android users are on Windows or macOS, my default recommendation for them would be to use the integrated GDB support in Visual Studio on Windows or the mono/lldb-binaries on macOS instead.

### Recommendation for this GitHub issue

For this particular GitHub issue about Linux, [attaching GDB on the command line](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md#attaching-gdb-on-the-command-line-on-windows-or-macos) would be a fine approach. Note that that contributor-focused article only mentions *libmonosgen-2.0*, but you would need to copy *any* native unmanaged library you wanted to debug to the local *gdb-symbols* directory.

Another approach that might be more convenient would be to use Android Studio. I'm fairly certain the [*Attaching LLDB using Android Studio*](https://github.com/xamarin/xamarin-android/blob/master/Documentation/workflow/DevelopmentTips.md#attaching-lldb-using-android-studio-on-windows-or-macos) steps also work on Linux. Those steps are nice because LLDB takes care of setting up all the native unmanaged libraries automatically (at the cost of having to wait for it to download them from the device on the first debugging session) and you get a graphical UI for stepping through the native unmanaged source files.

**Comment by m93a** [comment]
Thank you all for your responses, I will give LLDB a try! However, since I came here from [the specs](https://docs.microsoft.com/cs-cz/xamarin/android/deploy-test/gdb) (I've never even used GDB before), I think that it's advisable to add some deprecation warning there. Maybe even point them to the LLDB tutorial. Than I'll happilly close the issue :)

**Comment by jpobst** [comment]
Closing, as this seems expected with an OSS build.
