### ISSUE TITLE
Android 10 not appearing in "Android SDKs and Tools"

### ISSUE THREAD

**Issue by arivoir** [xamarin/xamarin-android#3794]
I have the latest stable Visual Studio 16.3.5 for Windows. 

![image](https://user-images.githubusercontent.com/17496741/66857868-880c9100-ef5e-11e9-8905-e03e55c2ff73.png)

I tried to update Android projects to version 10, but the "Android SDKs and Tools" is not listing that option.

![image](https://user-images.githubusercontent.com/17496741/66857914-9e1a5180-ef5e-11e9-8527-c46c023b6dd7.png)

On the other hand the, the Android 10.0 is available in the properties of the project
![image](https://user-images.githubusercontent.com/17496741/66858032-e3d71a00-ef5e-11e9-9e88-8fb67c4f59b2.png)

But it throws the following error.

> Error		Could not find android.jar for API Level 29. This means the Android SDK platform for API Level 29 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change your Xamarin.Android project to target an API version that is installed. (C:\Program Files (x86)\Android\android-sdk\platforms\android-29\android.jar missing.)			

What is it happening?

**Comment by brendanzagaeski** [comment]
Thanks for the report! This behavior is also being tracked in <https://developercommunity.visualstudio.com/content/problem/746414/the-android-sdk-manager-does-not-yet-offer-downloa.html>.

I'll copy over some information and keep the status of this GitHub issue synced with that item.

### Workaround

 1. Click on the gear icon at the bottom right of the Android SDK Manager window.
 2. Temporarily select **Repository > Google (Unsupported)**.
 3. Install the desired **Android 10.0** SDK components.
 4. Click the gear icon again, and set it back to **Repository > Microsoft (Recommended)**.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes a fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

The fix is not yet available on macOS. I will update this item again when a Preview version with the fix is available on macOS.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix not yet available on macOS.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published that includes the fix for this item.

Fix included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by visionfaysal** [comment]
brendanzagaeski thank you so much ... you are a great developer

**Comment by visionfaysal** [comment]
you resolve my issue using this 
Click on the gear icon at the bottom right of the Android SDK Manager window.
Temporarily select Repository > Google (Unsupported).
Install the desired Android 10.0 SDK components.
Click the gear icon again, and set it back to Repository > Microsoft (Recommended).

**Comment by Jack-Paul** [comment]
The same issue is happening for me but now it's not showing android 11.

![image](https://user-images.githubusercontent.com/34718301/105790930-2cc3ae00-5fab-11eb-8c29-fd2e37254c43.png)
I am using the latest version of Visual studio in windows 16.8.4
Please advice.

**Comment by valentasm1** [comment]
![image](https://user-images.githubusercontent.com/8047891/107144288-e5da9e80-6942-11eb-9bf1-988a7c607fba.png)
Select gear at bottom > Repository > Full List (unsuported)
