### ISSUE TITLE
msbuild is not copying package file to output path when using aab package format

### ISSUE THREAD

**Issue by claudioredi** [xamarin/xamarin-android#3804]
### Steps to Reproduce

1. Edit your Android project and add `<AndroidPackageFormat>aab</AndroidPackageFormat>` to any build configuration
2. Run `msbuild MyApp.csproj /t:PackageForAndroid /p:OutputPath=bin/SomeConfiguration /p:Configuration=SomeConfiguration -restore`

### Expected Behavior
Path `bin/SomeConfiguration` contains `xxxxx.aab` package file

### Actual Behavior

Path `bin/SomeConfiguration` does not contains `xxxxx.aab` package file. I see it inside `obj` folder but it's not moved. 

Package is copied when `apk` format is used.

### Version Information
```=== Visual Studio Community 2019 for Mac ===

Version 8.3.4 (build 8)
Installation UUID: 706648b1-5752-416c-b714-16a299f3abe9
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Version: 3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.1.13

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.0 (14936)
Build 11A420a

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/claudioredi/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/claudioredi/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 803040008
Git revision: 8da5857bc3d33e5667cacaab3bd1ab55375ed3e3
Build date: 2019-10-14 18:26:13+00
Build branch: release-8.3
Xamarin extensions: 61c91e660a01512a3b8187c749fd3bccc75a2bf4

=== Operating System ===

Mac OS X 10.14.5
Darwin 18.6.0 Darwin Kernel Version 18.6.0
    Thu Apr 25 23:16:27 PDT 2019
    root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

### Log File
Build log file
[build_output.txt](https://github.com/xamarin/xamarin-android/files/3736224/build_output.txt)

**Comment by jonathanpeppers** [comment]
@claudioredi `PackageForAndroid` will produce the unsigned App Bundle. Can you use `SignAndroidPackage` instead, or are you specifically looking to use the unsigned one?

We put the unsigned one in `obj`, because we thought it was not particularly useful. But maybe that is not the case? To change it now, I think we would have to work with the IDE / App Center teams and make sure we don't break something.

**Comment by claudioredi** [comment]
@jonathanpeppers  I've seen `SignAndroidPackage` working perfect and definitively I could use it. The thing is that Azure Dev Ops seems to be better integrated with  `PackageForAndroid`. Task for building a Xamarin.Android project contains a checkbox to create app package, it explicitly says that will use  `PackageForAndroid`

<img width="690" alt="Screen Shot 2019-10-17 at 4 17 47 PM" src="https://user-images.githubusercontent.com/1825057/67040629-40227100-f0fa-11e9-8a5a-8a89f260abab.png">

I'm sure I could customize the build task to use `SignAndroidPackage`, I definitively considered that as an option... but wanted to validate if this was an unexpected bug since the previous behavior was to place package on output path.

**Comment by dellis1972** [comment]
I suspect App Center is doing its own Signing step when it publishes apps to the play store. Which is why they use the Unsigned output. 

We have a task called `_CopyPackage` which is responsible for copying the apk to the bin directory when `PackageForAndroid` is called. Currently the aab is not added to the list of inputs for that target, which is why it doesn't get copied. As @jonathanpeppers mentioned, at the time we didn't think the unsigned package would be very useful, so we can change that. 

Next thing to find out is if App Center will even support aab files. If they are using apksigner for their signing process it won't work since aab files need to be signed with jar signer.  So that is something else too investigate.

**Comment by claudioredi** [comment]
@dellis1972 : It's my first try of app bundle on Xamarin so checking if aab format is supported on app center is another thing to validate :) I know they have some sort of support because of [this](https://github.com/microsoft/appcenter/issues/194) ticket.

I use app center to distribute the app on test environments so definitively It's on my list to validate if aab will be distributed correctly or not.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
