### ISSUE TITLE
Default C# 8

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/xamarin-android#3807]
In VS 2019 16.3/8.3 C# 8 should be the default language version as it is officially supported. @terrajobst  @cartermp 

I created one in iOS too: https://github.com/xamarin/xamarin-macios/issues/7245

**Comment by JonDouglas** [comment]
Our targets need to increase the `<MaxSupportedLangVersion>` to 8.0 in order to opt-in to C# 8 support by default I believe. We'll work to include this by default.

/cc @jonathanpeppers @jpobst

**Comment by jpobst** [comment]
Some links for reference:

https://github.com/dotnet/roslyn/blob/d28899e051db225e4c1126c61c5bda2dba2a32b1/src/Compilers/Core/MSBuildTask/Microsoft.CSharp.Core.targets#L6-L10

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version

**Comment by mattleibow** [comment]
I just use `<LangVersion>` in my projects - doesn't that work?

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.1.0.29.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by EvoPulseGaming** [comment]
Using Xamarin.Android 10.2.0.16 and its still complaining about 8.0 (vs2019 16.5.0 preview 1)

I've updated everything possible, and this doesn't work.

**Comment by jamesmontemagno** [comment]
I did a file -> new project and it worked just fine for me. in 16.4

This is specifically inside of the Android project.  You still need to turn it on manually for .NET standard 2.0: https://montemagno.com/use-csharp-8-everywehre/

**Comment by chrisgate** [comment]
i did too @jamesmontemagno ......is there any thing in android .csproj that specify is 8.0 compatible?

**Comment by jamesmontemagno** [comment]
So, in the latest 16.4 it should just work from what I tested, however, I didn't test older projects on it.

You can add:
```
<LangVersion>8.0</LangVersion>
```

to your csproj and that will light it up :)

**Comment by chrisgate** [comment]
add to android .csproj ?

**Comment by jamesmontemagno** [comment]
Yup, I put it in all my projects, it is wherever you want to use 8.0 you just put it in there.

**Comment by chrisgate** [comment]
thank you

**Comment by EvoPulseGaming** [comment]
This worked for me as well

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item for the Xamarin.Android project type, as was [published earlier](https://github.com/xamarin/xamarin-android/issues/3807#issuecomment-561444354) on Windows.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by EvoPulseGaming** [comment]
This can't be right, as in 16.5 I still had to manually change it on windows visual studio

**Comment by jpobst** [comment]
@EvoPulseGaming Can you be more specific as to what isn't working for you? What type of project, etc?

I just created a new Xamarin Android app from the template in 16.5 P1 and am able to use C# 8 features without changing anything.

**Comment by EvoPulseGaming** [comment]
What about everyone with an existing project?

**Comment by jpobst** [comment]
It should be automatic, unless you've set `<LangVersion>` manually to something else in your project.

**Comment by brendanzagaeski** [comment]
In case it might also be useful to mention, note that this specific GitHub issue in the xamarin-android repo is only about the Xamarin.Android project type. So for example, if you create a new **Mobile App (Xamarin.Forms)** app, the .NET Standard library part of that app does *not* yet default to supporting C# 8.0 language features, but the Xamarin.Android app project part of the app *does*.

**Comment by EvoPulseGaming** [comment]
Ohhh, okay, gotcha. Thanks for the clarification.

**Comment by MihaMarkic** [comment]
Visual Studio 16.7.4 and a new Xamarin Android project still requires editing .csproj for some reason. ¯\_(ツ)_/¯
@brendanzagaeski

**Comment by jonathanpeppers** [comment]
Roslyn renamed an MSBuild property that broke this in 16.7, see: https://github.com/xamarin/xamarin-android/pull/5054

This fix is in 16.8.
