### ISSUE TITLE
Auto generated Resource.designer.cs does not support aliased references

### ISSUE THREAD

**Issue by albanur** [xamarin/xamarin-android#3808]
### Steps to Reproduce

1. Add reference to library targeted for monoandroid with alias (containing resources), example: 
```xml
<ProjectReference Include="..\LibraryA\LibraryA.csproj">
  <Project>{A31DB667-7565-4C13-99CD-82064660960F}</Project>
  <Name>LibraryA</Name>
  <Aliases>LibA</Aliases>
</ProjectReference>
```
2. Build main project

Example project: [AliasExample.zip](https://github.com/xamarin/xamarin-android/files/3739055/AliasExample.zip)

### Expected Behavior
Project builds properly.

### Actual Behavior
Build fails with following error:
`Resources/Resource.designer.cs(29,12,29,20): error CS0400: The type or namespace name 'LibraryA' could not be found in the global namespace (are you missing an assembly reference?)`

The generated Resource.designer.cs file contains the reference to resource in aliased library, but the reference is using `global` instead of proper `LibA` alias:

```cs
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AliasExample.Droid.Resource", IsApplication=true)]

namespace AliasExample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LibraryA.Resource.String.action_settings = global::AliasExample.Droid.Resource.String.action_settings;
			global::LibraryA.Resource.String.app_name = global::AliasExample.Droid.Resource.String.app_name;
...
```

### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.3.4 (build 8)
Installation UUID: f31f4dd5-2c32-43ce-b1bd-a42b00d292f1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.24 (d16-3 / 08809f5b)

	Package version: 604000208

=== Mono Framework MDK ===

Runtime:
	Mono 6.4.0.208 (2019-06/07c23f2ca43) (64-bit)
	Package version: 604000208

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.0.100/Sdks
SDK Versions:
	3.0.100
	2.2.300
	2.2.106
	2.1.505
	2.1.504
	2.1.202
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.4.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.0.0
	2.2.5
	2.2.4
	2.1.13
	2.1.9
	2.1.8
	2.0.9

=== Xamarin.Profiler ===

Version: 1.6.12.26
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Xamarin.Android ===

Version: 10.0.3.0 (Visual Studio Community)
Commit: xamarin-android/d16-3/4d45b41
Android SDK: /Users/grko/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.4
SDK Build Tools Version: 29.0.2

Build Information: 
Mono: mono/mono/2019-06@5608fe0abb3
Java.Interop: xamarin/java.interop/d16-3@5836f58
LibZipSharp: grendello/LibZipSharp/d16-3@71f4a94
LibZip: nih-at/libzip/rel-1-5-1@b95cf3fd
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.27.1@8212a2d
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-3@cb41333

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/grko/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 1.4.0.65
Hash: c33b107
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:20 UTC

=== Android Device Manager ===

Version: 1.2.0.116
Hash: d2b2af0
Branch: remotes/origin/d16-3
Build date: 2019-10-08 23:36:44 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Apple Developer Tools ===

Xcode 11.1 (15405)
Build 11A1027

=== Xamarin.Mac ===

Version: 6.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin.iOS ===

Version: 13.4.0.2 (Visual Studio Community)
Hash: e37549bc
Branch: xcode11.1
Build date: 2019-10-07 22:43:23-0400

=== Xamarin Designer ===

Version: 16.3.0.247
Hash: 52eac1a9e
Branch: remotes/origin/d16-3
Build date: 2019-10-03 23:04:28 UTC

=== Build Information ===

Release ID: 803040008
Git revision: 8da5857bc3d33e5667cacaab3bd1ab55375ed3e3
Build date: 2019-10-14 18:26:13+00
Build branch: release-8.3
Xamarin extensions: 61c91e660a01512a3b8187c749fd3bccc75a2bf4

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Thu Jun 20 18:42:21 PDT 2019
    root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Comment by aquakul** [comment]
Any update on when  this will be available ? Any alternate till then ?

**Comment by dellis1972** [comment]
@aquakul sorry for the delay. It took some time to figure out how to do what is needed using the CodeDom. I think I have a solution now, I'll be putting up a PR today hopefully. Unfortunately the only workaround for now is to not use the Aliases feature, since the Resource.Designer.cs code generator is part of our build process.  This Issue will be updated when the PR is opened.

**Comment by dellis1972** [comment]
PR is up at https://github.com/xamarin/xamarin-android/pull/3972

**Comment by aquakul** [comment]
> 
> 
> @aquakul sorry for the delay. It took some time to figure out how to do what is needed using the CodeDom. I think I have a solution now, I'll be putting up a PR today hopefully. Unfortunately the only workaround for now is to not use the Aliases feature, since the Resource.Designer.cs code generator is part of our build process. This Issue will be updated when the PR is opened.

@dellis1972  Thanks Dellis for the update. For now I have moved all my resources to a different Android lib project and added that as a dependency in my primary project. That I get to keep my alias (which i need to avoid conflicting symbols in multiple dll's ) and also has the resources.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.2.0.84.

Fix included on Windows in Visual Studio 2019 version 16.5 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by james-allison** [comment]
I'm hitting this error with Xamarin.Android 10.2.0.100 having just updated to VS2019 16.5 

In also moving to Xamarin Forms 4.5, I've had to specify an alias for an assembly to avoid a namespace conflict between AndroidX.Media and Android.Support.Media.Compat for the MediaSessionCompat class.

(I need Android.Support as I'm using GooglePlayServices.Maps - which hasn't been moved to AndroidX.)

However, If I include the alias, it forces an 'extern alias global,androidx;' line to the top of the auto generated Resource.designer.cs with incorrect syntax, breaking the build.

**Comment by brendanzagaeski** [comment]
@james-allison, thanks for the quick feedback on today's new release! I was able to reproduce the scenario you mention, and I have submitted a follow-up issue about: <https://github.com/xamarin/xamarin-android/issues/4409>.

Depending on your usage scenario, a potential workaround could be to remove the `global,` part from the `Aliases` metadata so that the `Aliases` metadata contains only `androidx`. That should in theory be compatible with the current fix from this issue #3808.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item (not yet including support for comma-delimited lists). The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item (not yet including support for comma-delimited lists).

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by bzd3y** [comment]
I know this issue is closed, but this is the only issue I have been able to find that seems even remotely related. After updating to VS2019 6.5.2 (and 16.5.3) I get errors that appear to be related to this. The following lines are added to the top of the generated resource file on build:

extern alias indoor, global;
extern alias proximity, global;

And the project fails to build, citing these two lines as errors. The `, global` in both is what gets underlined as causing multiple errors.

I saw there was an update for Visual Studio to 16.5.3 released today that I was hopeful would fix this, but it seems to make it worse and the entire resource file is filled with errors.

I just downgraded to 16.4.6 and that fixes the problem with those two lines not being added to the top of the generated file.

Does anybody have any insight into where those two lines are coming from?

**Comment by brendanzagaeski** [comment]
@bzd3y, that's the follow-up issue about comma-delimited aliasses <https://github.com/xamarin/xamarin-android/issues/3808#issuecomment-599907124>:

> I was able to reproduce the scenario you mention, and I have submitted a follow-up issue about: <https://github.com/xamarin/xamarin-android/issues/4409>.
>
> Depending on your usage scenario, a potential workaround could be to remove the `global,` part from the `Aliases` metadata so that the `Aliases` metadata contains only `androidx`. That should in theory be compatible with the current fix from this issue #3808.

**Comment by bzd3y** [comment]
Okay thanks, I was wondering that. And thanks for the quick reply! Sorry, I'm not that familiar with the internals of what is going on. Where is the metadata you are referring to there? I tried removing it from the generated file, but it just gets added again on build, which makes sense.

Should my questions be in that other issue? Or is there a better place to get help with this?

**Comment by brendanzagaeski** [comment]
@bzd3y. The quick answer about "where is the metadata" is that in general it would appear as an `<Aliases>` element somewhere in the XML of your *.csproj* file if you open the *.csproj* file in a text editor. If you don't see an `<Aliases>` element there, then something trickier might be happening. In that case, the best next step would be to submit a [new issue](https://github.com/xamarin/xamarin-android/issues/new) so the team can take a look. If possible, attach either your diagnostic MSBuild output or a minimized sample project that reproduces the issue on the new issue.

**Comment by bzd3y** [comment]
Okay, I do see the <Aliases> tag (two of them), thank you. So is my understanding correct that the problem is that the generating tool produces one line like `extern alias whatever, global` when it should produce two lines? And #4409 is going to fix that?

I'm confused about how these two lines are being added to the generated file at all when they were not before.

**Comment by brendanzagaeski** [comment]
Correct. There should be a separate `extern alias` line for each comma-separated item that appears in the corresponding `<Aliases>` element.

The fix for #4409 in fact just picks the *first* alias and generates a single `extern alias` line with no commas in *Resource.designer.cs*.

Depending on why your project is using `<Aliases>` to begin with, a possible way to solve the problem would be to edit the `<Aliases>` elements so they only contain 1 name. (Related reference: [`extern alias` documentation](https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/extern-alias).)

> I'm confused about how these two lines are being added to the generated file at all when they were not before.

The reason is that Xamarin.Android 10.2 includes the fix for this issue #3808, which is what adds the `extern alias` lines to *Resource.designer.cs*.

It's interesting that with Xamarin.Android 10.1 your project doesn't get the error from the first from this issue description <https://github.com/xamarin/xamarin-android/issues/3808#issue-508424595>. If you can share the diagnostic build output or a sample project that shows that different behavior between Xamarin.Android 10.1 and Xamarin.Android 10.2, please submit a new issue with that info so the team can take a look.

**Comment by bzd3y** [comment]
Okay, these fixes don't seem to be working, at least in my case. It will probably take a new issue to figure that out. I didn't write the code that is producing the error, so maybe I'm missing something. I will try to get more information and start a new issue after I get done with the work this was preventing me from doing.

Thanks for your help!

**Comment by bzd3y** [comment]
@brendanzagaeski #4542 is the new issue I created, if you are interested. Thanks again for your help.
