### ISSUE TITLE
Using the wrong class library when a ref/ and lib/ in nuget

### ISSUE THREAD

**Issue by mattleibow** [xamarin/xamarin-android#3920]
### Steps to Reproduce

1. Download sample: https://github.com/mattleibow/NuGetFoldersTest
2. Run build.ps1
3. Run android app in NuGetFoldersTest.sln

What is happening is in the NuGet, there are 3 assemblies (netstandard, ios, android). Since the netstandard is only for reference and should always be replaced by the runtime, it is in the `ref` folder. The android and ios assemblies are in the `lib` folder.

When building, the shared projects should use the ref, and then the android and ios have their own platform-specific assemblies. What is happening is that on android the ref/netstandard assembly is being added to the apk instead of the lib/monoandroid. ios works fine and uses the lib.xamarinios assembly.

### Expected Behavior

The text on the app says Hello from Android.

### Actual Behavior

The text says hello from netstandard.

### Version Information

Latest preview ;)

**Comment by mattleibow** [comment]
I have a workaround for now to include the monoandroid dll in both the ref and lib folders.

**Comment by jonathanpeppers** [comment]
@mattleibow is the NetStandard library supposed to be just a "reference assembly" and have no implementation?

It seems like the csproj should have `<ProduceReferenceAssembly>True</ProduceReferenceAssembly>` and you ship the assembly that is output to `bin\Release\netstandard2.0\ref\` in the NuGet? This would cause `[assembly: System.Runtime.CompilerServices.ReferenceAssemblyAttribute]` to be included? 

When @dellis1972 was looking, the absence of this attribute was the issue: 

https://xamarinhq.slack.com/archives/C03CEGRUW/p1574072958063200

**Comment by mattleibow** [comment]
That is true, it _should_ be a reference assembly. But, at the same time, if it is in the `ref` folder, that implicitly means it is a reference assembly - and should never reach the app package.

**Comment by dellis1972** [comment]
This diff *might* help

```
diff --git a/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs b/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
index 99068f96..c3a4ee9c 100644
--- a/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
+++ b/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
@@ -85,7 +85,8 @@ namespace Xamarin.Android.Tasks
                                foreach (var assembly in Assemblies) {
                                        // Add each user assembly and all referenced assemblies (recursive)
                                        string resolved_assembly = resolver.Resolve (assembly.ItemSpec);
-                                       if (MonoAndroidHelper.IsReferenceAssembly (resolved_assembly)) {
+                                       bool refAssembly = !string.IsNullOrEmpty (assembly.GetMetadata ("NuGetPackageId")) && resolved_assembly.Contains ($"{Path.PathSeparator }ref{Path.PathSeparator }");
+                                       if (refAssembly || MonoAndroidHelper.IsReferenceAssembly (resolved_assembly)) {
                                                // Resolve "runtime" library
                                                if (lockFile != null)
                                                        resolved_assembly = ResolveRuntimeAssemblyForReferenceAssembly (lockFile, assembly.ItemSpec);
```

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.2.0.84.

Fix included on Windows in Visual Studio 2019 version 16.5 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
