### ISSUE TITLE
Specify Version of Mono for each Release

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/xamarin-android#3922]
When setting up CI I also have to match Mono version with Android version. Would be nice to just have a reference as to which version of mono to install.

**Comment by radekdoulik** [comment]
I see the mono version mentioned in the latest release notes

https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.0#mono-framework-version-update-to-64
https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.1#mono-framework-version-update-to-66

Are you looking for older versions or do you suggest we should have it mentioned in some file which would be part of the installations?

@brendanzagaeski @jonpryor what is your opinion on that?

**Comment by brendanzagaeski** [comment]
I think what James is looking for is the corresponding desktop Mono Framework MDK version that's in the Visual Studio for Mac updater channel at the same time as each Xamarin.Android release. At some point in the future, Visual Studio for Mac might start providing a page with a history of that information, but as far as I know, at the moment it's not listed anywhere publicly. So for this scenario with the Mono Framework MDK, I can include it in the Xamarin.Android release notes.

One detail I want to be a little careful about is to put the information a bit out of the way because otherwise it would make the release notes more noisy for users who aren't setting up CI.

My current thought is to put the information only in the version of the notes [on GitHub](https://github.com/xamarin/xamarin-android/releases), and to put it at the bottom of the release notes, in its own section after *OSS core*.

**Comment by brendanzagaeski** [comment]
All set. I added this for today's release as well as for two older versions Xamarin.Android 10.0 and Xamarin.Android 9.4.1.0.

(The current Xamarin.Android 10.2 Preview is not yet published on macOS, so I didn't yet add a Mono Framework MDK version there. I'll take care of that once it is published.)
