### ISSUE TITLE
X509Certificate.CreateFromSignedFile throw exception

### ISSUE THREAD

**Issue by mailfcly** [xamarin/xamarin-android#3949]
### Description
Build code with Xamarin forms. Test it with Android.
"X509Certificate.CreateFromSignedFile" throw exception in vs2019. 
But it is OK in vs2017.

### Test code
```
        private bool IsSigned(string filePath)
        {

            bool chainIsValid = false;
            try
            {
                if (File.Exists(filePath))
                {
                    X509Certificate theSigner = X509Certificate.CreateFromSignedFile(filePath);
                    X509Certificate2 theCertificate = new X509Certificate2(theSigner);

                    RSACryptoServiceProvider publicKeyProvider = (RSACryptoServiceProvider)theCertificate.PublicKey.Key;
                    byte[] Data = Encoding.UTF8.GetBytes("test.com");
                    chainIsValid = publicKeyProvider.VerifyData(Data, "SHA1", new byte[10]);
                }
            }
            catch (Exception ex)
            {
                chainIsValid = false;
            }

            return chainIsValid;
        }
```

### Exception
```
`MonoBtlsPkcs12.Import` failed.
  at Mono.Btls.MonoBtlsObject.CheckError (System.Boolean ok, System.String callerName) [0x0003b] in <fc50dd60821248f5acc5a6cbf53c14bf>:0 
  at Mono.Btls.MonoBtlsObject.CheckError (System.Int32 ret, System.String callerName) [0x00000] in <fc50dd60821248f5acc5a6cbf53c14bf>:0 
  at Mono.Btls.MonoBtlsPkcs12.Import (System.Byte[] buffer, Microsoft.Win32.SafeHandles.SafePasswordHandle password) [0x0002e] in <fc50dd60821248f5acc5a6cbf53c14bf>:0 
  at Mono.Btls.X509CertificateImplBtls.ImportPkcs12 (System.Byte[] data, Microsoft.Win32.SafeHandles.SafePasswordHandle password) [0x0003e] in <fc50dd60821248f5acc5a6cbf53c14bf>:0 
  at Mono.Btls.X509CertificateImplBtls..ctor (System.Byte[] data, Microsoft.Win32.SafeHandles.SafePasswordHandle password, System.Security.Cryptography.X509Certificates.X509KeyStorageFlags keyStorageFlags) [0x0003b] in <fc50dd60821248f5acc5a6cbf53c14bf>:0 
```

**Comment by brendanzagaeski** [comment]
Thanks for the report! It looks like this problem has been resolved by the fix for <https://github.com/mono/mono/issues/14721>.

I tested the following code:

```csharp
var memoryStream = new MemoryStream();
System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("AndroidSingleViewApp1.SignedExecutable.exe").CopyTo(memoryStream);
string file = Path.Combine(Application.DataDir.ToString(), "SignedExecutable.exe");
File.WriteAllBytes(file, memoryStream.ToArray());
System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(file);
```

### Behavior on Visual Studio 2019 version 16.3.10 with Xamarin.Android 10.0

The call to `CreateFromSignedFile()` failed with the *\`MonoBtlsPkcs12.Import\` failed* message.

### Behavior on Visual Studio 2019 version 16.4 Preview 5 with Xamarin.Android 10.1

The call to `CreateFromSignedFile()` completed without any exceptions.

### Testing notes

I manually uninstalled the *Mono Shared Runtime* app from the device when switching between versions to work around <https://github.com/xamarin/xamarin-android/issues/3784>.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4 Preview 5. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.1.0.30.

Fix included on Windows in Visual Studio 2019 version 16.4. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.4 Preview 2.1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.1.1.0.

Fix included on macOS in Visual Studio 2019 for Mac version 8.4. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.4 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
