### ISSUE TITLE
_UpdateAndroidResgen fails because R.java is used by other process

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/xamarin-android#4062]
### Steps to Reproduce

Our build in MvvmCross has started to fail building. Only sometimes it completes successfully.

We are using the Azure Pipelines `windows-latest` build image.

1. Try build MvvmCross on Windows using the Cake build script
    `.\build.ps1`
2. Build fails when reaching MvvmCross.Plugins.Location.Fused Android library

### Expected Behavior

Build should complete without errors

### Actual Behavior

see: https://dev.azure.com/Cheesebaron/MvvmCross/_build/results?buildId=805

```
"D:\a\1\s\MvvmCross.sln" (Build target) (1) ->
"D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj" (default target) (32) ->
"D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj" (Build target) (32:4) ->
(_UpdateAndroidResgen target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000: Unhandled exception: System.IO.IOException: The process cannot access the file 'D:\a\1\s\MvvmCross.Plugins\Location.Fused\obj\Release\monoandroid90\android\src\com\google\android\gms\common\R.java' because it is being used by another process. [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at Xamarin.Android.Tasks.GenerateLibraryResources.GenerateJava(Library library) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1669,2): error XA0000:    at Xamarin.Android.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) [D:\a\1\s\MvvmCross.Plugins\Location.Fused\MvvmCross.Plugin.Location.Fused.csproj]
```

# Version Infomation

It builds against `monoandroid90;monoandroid10.0;`

The library uses the following package reference:

```
<PackageReference Include="Xamarin.GooglePlayServices.Location" Version="71.1600.0" />
```

**Comment by chrisevans9629** [comment]
I am getting this error as well when using ``Xamarin.GoogleMaps`` and ``Microsoft.AppCenter.Push``.  I keep getting
``
Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\Users\cevans\source\repos\LinkerTest\LinkerTest\LinkerTest.Android\obj\Debug\90\android\src\com\google\android\gms\base\R.java' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Xamarin.Android.Tools.Files.HashFile(String filename, HashAlgorithm hashAlg)
   at Xamarin.Android.Tools.Files.HashFile(String filename)
   at Xamarin.Android.Tools.Files.HasStreamChanged(Stream source, String destination)
   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)
   at Xamarin.Android.Tasks.GenerateLibraryResources.GenerateJava(Library library)
   at Xamarin.Android.Tasks.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s)	LinkerTest.Android ``

The only solution I have found is removing the packages so far

**Comment by Cheesebaron** [comment]
Downgrading Xamarin.Build.Download to 0.4.11 worked. Cosing this as it is a duplicate of https://github.com/xamarin/xamarin-android/pull/4043
