### ISSUE TITLE
xaprepare build tool is broken.

### ISSUE THREAD

**Issue by smaudet** [xamarin/xamarin-android#4130]
### Steps to Reproduce

At least on OSX (Mohjave, Catalina untested), the build is horribly broken. Most of the issues seem to stem from xaprepare. I was able to go in and fix somethings but, basic stuff like:

Reading SSH env vars so git can work properly,
Inaccurate/misleading build documentation steps (github repo is private or not existent, not mentioned in build and mentioned as "optional")
Requires patching out/broken external build step (dies in JavaInterop).

Additionally program is nigh un-usable because it requires a password to 'pin' some brew deps...repeatedly, no attempt to actually detect whether or not PINing is required or not.

This is off of master branch.

It is enough to install dependencies with brew (these are not properly documented either), and attempt `make prepare` to see the breakage.

### Expected Behavior

Build should work with some simple commands

### Actual Behavior

Build is horribly over-engineered requiring reading a lot of misleading documentation which is incorrect (there was no good reason to write a C# program with rough edges when a simple shell script would have more than sufficed) and fails in multiple ways.

### Version Information

master branch. Dependencies as found on commit:
4e364babe27c62fa8704e443740de6be98ed45bf

**Comment by jonpryor** [comment]
How *exactly* is `xaprepare` "broken"?  What commands did you run, what was the error output?

`xaprepare` isn't even a utility which should be directly executed by the developer as part of the build.  As per the build instructions ([Unix](https://github.com/xamarin/xamarin-android/blob/master/Documentation/building/unix/instructions.md), [Windows](https://github.com/xamarin/xamarin-android/blob/master/Documentation/building/windows/instructions.md)), you should use e.g. `make prepare` or `msbuild /t:Prepare Xamarin.Android.sln`.

At no point is `xaprepare` even *mentioned* in either of those pages.

*Note*: Those pages *do* mention an ***optional*** step of "Prepare external/proprietary git dependencies".  If this fails for you -- which it *will*, as it will attempt to clone private git repos which you presumably don't have access to -- then *do not* execute the (again) ***optional*** build step.

> Inaccurate/misleading build documentation steps (github repo is private or not existent, not mentioned in build and mentioned as "optional")

Please, which *specific* bits of documentation are incorrect or misleading?

Some bits are "optional" precisely because they cannot be built by external developers.  We're trying to document the system for both internal and external developers.  If an optional bit fails, *don't do that*.

> Requires patching out/broken external build step (dies in JavaInterop).

What *precisely* is the failure?

It is difficult to fix the failure without understanding how it is failing.
