### ISSUE TITLE
Java.Lang.ClassNotFoundException when running Xamarin.Android Unit Test project

### ISSUE THREAD

**Issue by aimore** [xamarin/xamarin-android#4177]
### Steps to Reproduce

1. Create new Unit test App for Xamarin.Android
<img width="805" alt="Screen Shot 2020-01-26 at 8 21 31 am" src="https://user-images.githubusercontent.com/8807639/73127490-3ec7e500-4015-11ea-81f9-f15edb0740ed.png">
<img width="411" alt="Screen Shot 2020-01-26 at 8 21 45 am" src="https://user-images.githubusercontent.com/8807639/73127494-48514d00-4015-11ea-97cf-29b3020368c7.png">
2. Add your Xamarin.Android reference in the Unit test project.
3. Run Unit test app on Android Emulator Pixel 3 API 28

### App throws an exception:
`{Java.Lang.ClassNotFoundException: Didn't find class "md545536373befe5ba5b0be978b998d36b6.TestSuiteActivity_TestData" on path: DexPathList[[zip file "/data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/base.apk"],nativeLibraryDirectories=[/data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/lib/x86, /data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: Didn't find class "md545536373befe5ba5b0be978b998d36b6.TestSuiteActivity_TestData" on path: DexPathList[[zip file "/data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/base.apk"],nativeLibraryDirectories=[/data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/lib/x86, /data/app/MoneysoftDroidTest.MoneysoftDroidTest-xj6SXiog4Hdl8m08iiEcEQ==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at crc646202d106d622b1a8.MainActivity.n_onCreate(Native Method)
	at crc646202d106d622b1a8.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:7802)
	at android.app.Activity.performCreate(Activity.java:7791)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
}`

``
### Version Information

=== Visual Studio Community 2019 for Mac ===

Version 8.4.2 (build 59)
Installation UUID: 33b5fbb7-28b1-4e67-8ba7-ac8690e662fe
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.16.1.25 (issue-7441-d16-3-vsmac / 881172e73)

	Package version: 606000155

=== Mono Framework MDK ===

Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

=== Roslyn (Language Service) ===

3.4.0-beta4-19562-05+ff930dec4565e2bc424ad3bf3e22ecb20542c87d

=== NuGet ===

Version: 5.3.0.6192

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/3.1.101/Sdks
SDK Versions:
	3.1.101
	3.0.101
	3.0.100
	2.1.701
	2.1.700
	2.1.505
	2.1.504
	2.1.302
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.6.0/lib/mono/msbuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	3.1.1
	3.0.1
	3.0.0
	2.1.15
	2.1.14
	2.1.13
	2.1.12
	2.1.11
	2.1.9
	2.1.8
	2.1.2
	2.0.5

=== Xamarin.Profiler ===

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 11.2.1 (15526.1)
Build 11B500

=== Xamarin.Mac ===

Version: 6.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin.iOS ===

Version: 13.10.0.17 (Visual Studio Community)
Hash: 5f802ef53
Branch: xcode11.3
Build date: 2020-01-07 11:53:06-0500

=== Xamarin Designer ===

Version: 16.4.0.478
Hash: 95f0ab363
Branch: remotes/origin/d16-4
Build date: 2020-01-08 23:59:46 UTC

=== Xamarin.Android ===

Version: 10.1.3.7 (Visual Studio Community)
Commit: xamarin-android/d16-4/d66aed0
Android SDK: /Users/aimoresa/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.5
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: fd9f379
Java.Interop: xamarin/java.interop/d16-4@c4e569f
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.28.0@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/aimoresa/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.4.0.9
Hash: 3f7256f
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:04 UTC

=== Android Device Manager ===

Version: 16.4.0.30
Hash: f9172e2
Branch: remotes/origin/d16-4
Build date: 2020-01-14 22:19:24 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 804020059
Git revision: eb6fcdd83a227678e487aa733df3c8745f54fafc
Build date: 2020-01-17 12:12:02+00
Build branch: release-8.4
Xamarin extensions: ec32c90978c94f03d72f507b01f5aee70952ce87

=== Operating System ===

Mac OS X 10.14.6
Darwin 18.7.0 Darwin Kernel Version 18.7.0
    Tue Aug 20 16:57:14 PDT 2019
    root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

=== Enabled user installed extensions ===

Xamarin.Forms HotReload extension 1.4.0

### Log file:

https://gist.github.com/aimore/2640e1fe1cf2c68733d0a46b84548891

**Comment by brendanzagaeski** [comment]
**Cross-referencing note for the Xamarin.Android team:**

Note that the message seen for the Xamarin.Android.NUnitLite assembly in the **References** list Visual Studio for Mac is unrelated to the error that's occurring when running the app. That is, the message:

> Assembly not found for framework Xamarin.Android v9.0 Support

Is due to <https://github.com/xamarin/xamarin-android/issues/3507>, which causes Visual Studio for Mac to show a misleading error in the References list but doesn't affect the build itself.

**Comment by brendanzagaeski** [comment]
## Temporary workaround

Set the `$(AndroidPackageNamingPolicy)` MSBuild property to `LowercaseMD5` in the test project *.csproj* file: 

```xml
<PropertyGroup>
    <AndroidPackageNamingPolicy>LowercaseMD5</AndroidPackageNamingPolicy>
</PropertyGroup>
```

## Alternative temporary workaround

Disable **Use Shared Mono Runtime** under the **Android Build** section of the project property pages.

## Preliminary investigation notes

This issue was introduced by the new default names for generated Java types in Xamarin.Android 10.1: https://docs.microsoft.com/xamarin/android/release-notes/10/10.1#breaking-change-for-generated-java-type-names

The issue seems to have been fixed by something that's included in the current Xamarin.Android 10.2 Preview. I experimented with a few different versions and narrowed down the commit range for the fix to: https://github.com/xamarin/xamarin-android/compare/5f3b68e1a362ac2ad4b53b70f01f0044bf4c63e6...0a951055cce5e973f5e48e027f74a7ff2c459bde

The problem also affects Windows and has been reported in <https://developercommunity.visualstudio.com/content/problem/878335/since-vs-1642-deployment-of-unit-test-app-fails-du.html>.

**Comment by brendanzagaeski** [comment]
Also, the fix is somewhere outside of *Xamarin.Android.Build.Tasks.dll* and *Xamarin.Android.Common.targets*. The app still works as expected if I copy those files from Xamarin.Android 10.1 into the Xamarin.Android 10.2 installation and rebuild the app.

**Comment by pjcollins** [comment]
As @brendanzagaeski mentions, this issue does not appear to affect the current VS for Mac 8.5 preview with Xamarin.Android 10.2. I'm moving this to the d16-5 milestone to be tracked for resolution in that release.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)

**Comment by aimore** [comment]
Thanks @brendanzagaeski , after update it solved the issue
