### ISSUE TITLE
Building Android project fails when Microsoft.Extensions.Hosting is referenced

### ISSUE THREAD

**Issue by filipleifer** [xamarin/xamarin-android#4182]
### Steps to Reproduce

1. Have Visual studio 16.4.3 installed
2. Redirect default nuget restore path by setting env. variable "NUGET_PACKAGES" for example to "C:\\.nuget" 
3. Run Visual studio
4. Create new blank mobile project with Android
5. Add reference to nuget "Microsoft.Extensions.Hosting" version 3.1.1 via "Manage NuGet Packages"
6. Build Android project

**Example project:**

[XamarinBuildError.zip](https://github.com/xamarin/xamarin-android/files/4122615/XamarinBuildError.zip)

### Expected Behavior
Build should succeed because all nugets mentioned in error messages below are in nuget folder succesfully downloaded and ready for use.

### Actual Behavior
Problem with Nuget resolution occurs:

2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): warning XA0107: Ignoring  as it is a Reference Assembly
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): warning XA0107: Ignoring  as it is a Reference Assembly
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): warning XA0107: Ignoring  as it is a Reference Assembly
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): warning XA0107: Ignoring  as it is a Reference Assembly
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): error XA2002: Can not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `Microsoft.Extensions.Hosting.Abstractions`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `Microsoft.Extensions.Hosting.Abstractions`.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): error XA2002: Can not resolve reference: `System.Diagnostics.EventLog`, referenced by `Microsoft.Extensions.Logging.EventLog`. Please add a NuGet package or assembly reference for `System.Diagnostics.EventLog`, or remove the reference to `Microsoft.Extensions.Logging.EventLog`.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1808,2): error XA2002: Can not resolve reference: `Microsoft.Bcl.AsyncInterfaces`, referenced by `System.Text.Json`. Please add a NuGet package or assembly reference for `Microsoft.Bcl.AsyncInterfaces`, or remove the reference to `System.Text.Json`.

### What can be the problem:
Some problem with processing android project.assets file.

**Comment by brendanzagaeski** [comment]
Thanks for the report! I was able to reproduce this issue when using Visual Studio 2019 version 16.4.3, but I was no longer able to reproduce the issue when using Visual Studio 2019 version 16.5 Preview 2.

I tried a local build of xamarin-android where I removed <https://github.com/xamarin/xamarin-android/commit/40d4df6ee5c963d346b8062c481a26dd5135bb55>, and I confirmed that the problem reappeared. Specifically, the following part of that commit is what fixes this issue:

```patch
--- a/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
+++ b/src/Xamarin.Android.Build.Tasks/Tasks/ResolveAssemblies.cs
@@ -176,6 +177,8 @@ namespace Xamarin.Android.Tasks
                        }
                        foreach (var folder in lockFile.PackageFolders) {
                                var path = assemblyPath.Replace (folder.Path, string.Empty);
+                               if (path.StartsWith ($"{Path.DirectorySeparatorChar}"))
+                                       path = path.Substring (1);
                                var libraryPath = lockFile.Libraries.FirstOrDefault (x => path.StartsWith (x.Path.Replace('/', Path.DirectorySeparatorChar), StringComparison.OrdinalIgnoreCase));
```

So I will mark this issue as fixed, and I will update it again when the Release version with the fix becomes available.

**Comment by brendanzagaeski** [comment]
*Release status*

A new Preview version has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 10.2.0.84.

Fix included on Windows in Visual Studio 2019 version 16.5 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by filipleifer** [comment]
Thanks for your info. I can confirm that I cannot reproduce the issue in VS 16.5.0 too.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on Windows that includes the fix for this item. The fix is not yet published in a Release version on macOS. I will update this item again when a Release version is available on macOS that includes the fix.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on Windows in Visual Studio 2019 version 16.5. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.

(Fix also included on macOS in Visual Studio 2019 for Mac version 8.5 Preview 1 and higher. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).)

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version has now been published on macOS that includes the fix for this item.

Fix included in Xamarin.Android 10.2.0.100.

Fix included on macOS in Visual Studio 2019 for Mac version 8.5. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.5 and higher. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the latest version from <https://visualstudio.microsoft.com/downloads/>.)
