### ISSUE TITLE
httpclient is permanently unresponsive

### ISSUE THREAD

**Issue by shouhujishu** [xamarin/xamarin-android#4324]
When using httpclient to access an address that does not exist on the port, it will cause an infinite stuck waiting timeout invalid.
### Steps to Reproduce

System.Net.Http.HttpClient http = new System.Net.Http.HttpClient();
http.Timeout = TimeSpan.FromMilliseconds(300);
var N = await http.GetAsync("https://www.baidu.com:8000");

### Expected Behavior
Abnormal connection error
### Actual Behavior
(Task.run)Wait indefinitely and cause the main thread to become unresponsive
### Version Information
IDE:Microsoft Visual Studio Professional 2019版本 16.4.5
Xamarin 16.4.000.311 (d16-4@ddfd842)
Xamarin.Android SDK   10.1.4.0 (d16-4/e44d1ae)

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
