### ISSUE TITLE
Just make it easier bulding of apps

### ISSUE THREAD

**Issue by fisforfaheem** [xamarin/xamarin-android#4488]
like flutter do, Flutter lets you build apps for all platforms with no tweaking or 100 percent no change  please make it possible for xamarin to use 100 percent automatic like flutter whic autobuild everything 4 u unlike ony 75 pewrsnt code

**Comment by JonDouglas** [comment]
Hi @fisforfaheem,

Although this repository is part of Xamarin, it's only the Android SDK portion of it. For general improvements to the Xamarin platform, please feel free to [suggest a feature here instead!](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature)

For the cross-platform aspect, use the link above or report an issue to the Xamarin.Forms repository:

https://github.com/xamarin/Xamarin.Forms/issues

Because I don't believe this belongs as an issue in this repository, I'm closing this issue for now.
