### ISSUE TITLE
[Bug] android logs being spammed with type mapping message

### ISSUE THREAD

**Issue by GZidar** [xamarin/xamarin-android#4727]
### Description
I am seeing a huge number (thousands) of log entries with the below text appearing in the output window:

W/monodroid-assembly typemap: unable to find mapping to a Java type from managed type 'System.Int32, mscorlib'

or

W/monodroid-assembly typemap: unable to find mapping to a Java type from managed type 'System.Byte, mscorlib'

I don't recall seeing this before. The two examples above are the most common but the same message appears for other types as well

### Basic Information

- Version with issue: 4.6.0.800 (but also happened in 4.6.0.726)
- Android Support Library Version: AndroidX

> VS bug [<span>#</span>1130963](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1130963)

**Comment by brendanzagaeski** [comment]
*Cross-referencing note for the Xamarin team*

Corresponding Developer Community item: <https://developercommunity.visualstudio.com/content/problem/1021788/javainterop-assembly-not-found-for-xamarin-android.html>

**Comment by apeivandi** [comment]
Hi
Why is this issue was closed? What's the solution? I still see all the outputs and it's really annoying as rest of debug logs are impossible to be seen or used as long as all the extra messages are displayed.

Best

**Comment by brendanzagaeski** [comment]
@apeivandi, thanks for the question.

**Comment by brendanzagaeski** [comment]
@apeivandi, thanks for the question.

By default, the Closed state of an issue on GitHub indicates that a fix for the issue has been merged to the development branch and will be published in a future Xamarin.Android version. That's because GitHub's [automatic issue closing](https://help.github.com/articles/closing-issues-using-keywords) and [improved visibility for related pull requests](https://github.blog/changelog/2019-08-21-improved-visibility-for-related-pull-requests-in-issues/) features promote a workflow where issues are Closed when the fix is committed to the repository. As a result, teams, including the Xamarin.Android team, typically use the Open vs. Closed states to help monitor which items on an active milestone do not yet have a fix committed.

Due to that workflow that the GitHub automation promotes, this xamarin-android repository instead uses ["In Preview: " and "Published: " milestones](https://github.com/xamarin/xamarin-android/milestones?state=closed) combined with comments to indicate when fixes are _published_ (as opposed to _committed_). Here's an example of how that looks: <https://github.com/xamarin/xamarin-android/issues/4409#issuecomment-615018927>.

I will be updating this item with a similar comment as soon as the fix that is currently _committed_ to the development branch is _published_ in a publicly available version of Xamarin.Android.

At the moment there isn't a known workaround for this issue, but the team is working to publish the fix as soon as possible.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published on Windows that includes the fix for this item.

The fix is not yet available on macOS. I will update this item again when a Release version with the fix is available on macOS. If there are no unexpected complications, it will be available later this week.

Fix included in Xamarin.Android SDK version 10.3.1.4.

Fix included on Windows in Visual Studio 2019 version 16.6.1. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix not yet available on macOS.

Fix not yet available in the Preview version. I will update this item again when a Preview version is available that includes the fix.

**Comment by brendanzagaeski** [comment]
*Release status update*

A new Release version of Xamarin.Android has now been published on macOS that includes the fix for this item to match [yesterday's new version on Windows](https://github.com/xamarin/xamarin-android/issues/4727#issuecomment-637130171).

Fix included in Xamarin.Android SDK version 10.3.1.4.

Fix included on macOS in Visual Studio 2019 for Mac version 8.6.2. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

(Fix also included on Windows in Visual Studio 2019 version 16.6.1. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.)

Fix not yet available in the Preview versions. I will update this item again when Preview versions are available that includes the fix.

**Comment by kuramochia** [comment]
Release build using Xamarin Android SDK v10.3.1.4, I will see a large number of logs below.
```
monodroid-assembly typemap: module matching MVID [49B5F91A-2F8E-439E-AD20-F837EB41AFF4] not found.
```

The following command was executed.

```
> adb set prop mono.debug.log all
```

And when you view the log, it became the following log.

```
monodroid-assembly typemap: module matching MVID [49B5F91A-2F8E-439E-AD20-F837EB41AFF4] not found.
monodroid typemap: failed to map managed type to Java type: System.Byte, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cecToken=7cec85d7bea7798e (Module: ID: Module: 49b5f91a-2f8e-439e-ad20-f837eb41aff4; Type token: 33554569)
```

I think its same issue. I want you to fix this, too.

**Comment by brendanzagaeski** [comment]
@kuramochia, thanks for the idea. Right now, that would be considered the intended corrrect logging behavior. When `mono.debug.log` is set to the `all` verbosity level, additional diagnostic information is logged about the typemap lookups. To discuss potential changes to this behavior and your desired usage scenario, when you get a chance, please submit a [new issue](https://github.com/xamarin/xamarin-android/issues/new/choose) about it so the team can take a look and discuss. Thanks!

**Comment by kuramochia** [comment]
@brendanzagaeski  Thanks!, I submitted new issue (#4791).

**Comment by roninstar** [comment]
I have version Visual Studio 16.6.2 and since this upgrade I get spammed with these errors from my Xamarin Android Release build which I have not seen these errors before.  

     W/monodroid-assembly(5608): typemap: module matching MVID [96E78666-3B05-47DD-A3A2-B357695888AB] not found.

**Comment by brendanzagaeski** [comment]
@roninstar, thanks for the question. I've reopened kuramochia's new issue https://github.com/xamarin/xamarin-android/issues/4791 to track adjustments for those other typemap messages. You can continue to follow that issue for the latest info.

**Comment by brendanzagaeski** [comment]
_Release status update_

The fix for this issue that was [previously published in the Release versions](https://github.com/xamarin/xamarin-android/issues/4727#issuecomment-637843172) has now been published in the latest Preview versions as well.

Fix included in Xamarin.Android SDK version 10.4.0.0.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
