### ISSUE TITLE
XA3001: Could not AOT the assembly: System.Runtime.Loader.dll

### ISSUE THREAD

**Issue by EDMIStephen** [xamarin/xamarin-android#4731]
### Steps to Reproduce

1. Enable AOT Compilation on release build
![image](https://user-images.githubusercontent.com/56377481/82959221-4fac5580-a00b-11ea-89ad-db16c0affd21.png)
  
`<PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'SIT|AnyCPU'">

    <OutputPath>bin\SIT\</OutputPath>
    <Optimize>true</Optimize>
    <DebugType>none</DebugType>
    <AssemblyName>AppName.Mobile.Droid.SIT</AssemblyName>
    <DefineConstants>
    </DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
    <Debugger>Xamarin</Debugger>
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <AndroidSupportedAbis>armeabi-v7a</AndroidSupportedAbis>
    <AndroidEnableMultiDex>true</AndroidEnableMultiDex>
    <AotAssemblies>true</AotAssemblies>
    <EnableLLVM>true</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <BundleAssemblies>false</BundleAssemblies>
    <MandroidI18n />
    <AndroidDexTool>d8</AndroidDexTool>
    <AndroidLinkTool>r8</AndroidLinkTool>
    <AndroidStoreUncompressedFileExtensions>
    </AndroidStoreUncompressedFileExtensions>
    <AndroidEnableSGenConcurrent>true</AndroidEnableSGenConcurrent>
    <AndroidLinkMode>SdkOnly</AndroidLinkMode>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>`

2. Attempt to Run on Android Device from Windows

### Expected Behavior
Builds and deploys

### Actual Behavior
Error		XA3001: Could not AOT the assembly: System.Runtime.Loader.dll		 	0	

### Version Information

Microsoft Visual Studio Enterprise 2019 (2)
Version 16.6.0
VisualStudio.16.Release/16.6.0+30114.105
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Enterprise

Azure App Service Tools v3.0.0   16.6.936.3669
Azure App Service Tools v3.0.0

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2020.1.3   Build 201.0.20200515.122017
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1055 (d16-6@2873694)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.0 (d16-6/3fe860a)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.1.31 (b3eedfe)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File
[logs.zip](https://github.com/xamarin/xamarin-android/files/4685625/logs.zip)

**Comment by brendanzagaeski** [comment]
I believe the underlying problem in this case is <https://github.com/xamarin/xamarin-android/issues/3016>. That is, the old System.Runtime.Loader NuGet package (last updated in 2016) has an uncommon structure that led to a special-case workaround in <https://github.com/xamarin/xamarin-android/commit/fcb8364e35820edf8ec158b17e1a1814180f70ae>. But that special-case workaround wasn't 100% correct because it causes the reference assembly from the NuGet package to be included in the final app package. Reference assemblies should only be used during compilation and _not_ packaged into the final app packages.

Since reference assemblies are not expected to be packaged into apps, I'm not sure the AOT compiler is intended to be able to compile them, but I'll let @radekdoulik weigh in on whether handling reference assemblies sounds like a scenario the Mono team should consider adding to the AOT compiler.

In the mean time, I'll surface the idea I found in <https://github.com/xamarin/xamarin-android/issues/3016> as a candidate workaround. I did a quick local test with this and believe it is a valid workaround for this AOT issue as well.

### Candidate workaround

1. Run a command similar to the following in a Windows PowerShell command prompt to copy the _MonoAndroid10\\\_.\__ placeholder to the _ref_ directory of the System.Runtime.Loader NuGet package:

   ```powershell
   Copy-Item -Recurse "$env:USERPROFILE\.nuget\packages\system.runtime.loader\4.3.0\lib\MonoAndroid10" "$env:USERPROFILE\.nuget\packages\system.runtime.loader\4.3.0\ref\"
   ```

2. Delete _obj\project.assets.json_ from the Android app output directories (or just delete the whole _obj_ and _bin_ directories) and rebuild the app.

Explanation: The _System.Runtime.Loader.dll_ reference assembly does not serve a purpose in Xamarin.Android apps and so can be excluded entirely from the build process. Excluding it allows the _System.Runtime.Loader.dll_ facade assembly to be included correctly in the app package instead.

**Comment by EDMIStephen** [comment]
So I followed your workaround but more and more issues keep coming up. Our build machine is a mac so here are the steps it is running:

cp -r ~/.nuget/packages/system.runtime.loader/4.3.0/lib/MonoAndroid10/ ~/.nuget/packages/system.runtime.loader/4.3.0/ref

cp -r ~/.nuget/packages/system.runtime.compilerservices.unsafe/4.7.1/lib/netstandard2.0/ ~/.nuget/packages/system.runtime.compilerservices.unsafe/4.7.1/ref/netstandard2.0

cp -r ~/.nuget/packages/system.buffers/4.5.1/lib/netstandard2.0/ ~/.nuget/packages/system.buffers/4.5.1/ref/netstandard2.0


The system.runtime.compilerservices.unsafe is as per : https://github.com/xamarin/xamarin-macios/issues/3199

Is it correct to keep going down this path. It feels wrong and like there is a more serious issue. 
Now we are getting 
`XA3001: Could not AOT the assembly: Mono.Android.Export.dll
XA3001: Could not AOT the assembly: System.Numerics.dll
XA3001: Could not AOT the assembly: System.Runtime.CompilerServices.Unsafe.dll 
XA3001: Could not AOT the assembly: Microsoft.CSharp.dll`

How do I know after all this the app will even run?
Also how would I solve this when running the build in VS on Windows? Do I use pre build events for the Droid project?

Here are the details for our build machine.
`=== Visual Studio Community 2019 for Mac ===

 

Version 8.6.2 (build 6)
Installation UUID: d09895d9-ab8d-4372-b621-f6e0f67a3f5d
    GTK+ 2.24.23 (Raleigh theme)
    Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

 

    Package version: 610000104

 

=== Mono Framework MDK ===

 

Runtime:
    Mono 6.10.0.104 (2019-12/5d03a6fe116) (64-bit)
    Package version: 610000104

 

=== Roslyn (Language Service) ===

 

3.6.0-3.20210.9+4eafdcb1bcbd8d3573f2ba6065e56d9b9ce4f8a3

 

=== NuGet ===

 

Version: 5.6.0.6591

 

=== .NET Core SDK ===

 

SDK: /usr/local/share/dotnet/sdk/3.1.300/Sdks
SDK Versions:
    3.1.300
    3.1.201
    3.1.200
    3.0.100
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/6.10.0/lib/mono/msbuild/Current/bin/Sdks

 

=== .NET Core Runtime ===

 

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
    3.1.4
    3.1.3
    3.1.2
    3.0.0
    2.1.18
    2.1.17
    2.1.16
    2.1.13

 

=== Xamarin.Profiler ===

 

Version: 1.6.12.29
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

 

=== Updater ===

 

Version: 11

 

=== Apple Developer Tools ===

 

Xcode 11.4.1 (16137)
Build 11E503a

 

=== Xamarin.Mac ===

 

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

 

=== Xamarin.iOS ===

 

Version: 13.18.2.1 (Visual Studio Community)
Hash: 29c4ea731
Branch: d16-6
Build date: 2020-05-26 17:03:05-0400

 

=== Xamarin Designer ===

 

Version: 16.6.0.329
Hash: d4f8bcd13
Branch: remotes/origin/d16-6
Build date: 2020-04-24 02:16:02 UTC

 

=== Xamarin.Android ===

 

Version: 10.3.1.4 (Visual Studio Community)
Commit: xamarin-android/d16-6/3a10de9
Android SDK: /Users/macdev/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        None installed

 

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 29.0.6
SDK Build Tools Version: 29.0.2

 

Build Information: 
Mono: 165f4b0
Java.Interop: xamarin/java.interop/d16-6@2cab35c
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.31.1@49232bc
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

 

=== Microsoft Mobile OpenJDK ===

 

Java SDK: /Users/macdev/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

 

=== Android SDK Manager ===

 

Version: 16.6.0.50
Hash: 5901879
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:22 UTC

 

=== Android Device Manager ===

 

Version: 16.6.0.95
Hash: 45d17b5
Branch: remotes/origin/d16-6
Build date: 2020-04-30 04:01:42 UTC

 

=== Build Information ===

 

Release ID: 806020006
Git revision: c742dc3fcbf76855738eef57ce41d65f91acbf27
Build date: 2020-05-28 15:22:51-04
Build branch: release-8.6
Xamarin extensions: c742dc3fcbf76855738eef57ce41d65f91acbf27

 

=== Operating System ===

 

Mac OS X 10.15.4
Darwin 19.4.0 Darwin Kernel Version 19.4.0
    Wed Mar  4 22:28:40 PST 2020
    root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

**Comment by EDMIStephen** [comment]
That seems to work on at least my local env.

**Comment by brendanzagaeski** [comment]
Glad that did the trick! Thanks to the earlier temporary reply that mentioned <https://github.com/xamarin/xamarin-macios/issues/3199>, I tried the `<ExcludeAssets>` approach for this System.Runtime.Loader scenario, and it worked as desired, so that is probably a preferable workaround for this case too since it avoids having to tinker with the cached copy of the NuGet package.

### Improved workaround

1. Open the _.csproj_ file for the affected Android app project in a text editor.

2. Under the `<PropertyGroup>` element that contains other `<PackageReference>` elements, add an explicit `<PackageReference>` element for  System.Runtime.Loader, and set the `ExcludeAssets` metadata to `all`:

   ```xml
   <PackageReference Include="System.Runtime.Loader" Version="4.3.0">
     <ExcludeAssets>all</ExcludeAssets>
   </PackageReference>
   ```

Explanation: This has the same desired end result as copying the _MonoAndroid10\\\_.\__ placeholder into the _ref_ directory. It tells the build not to use the _System.Runtime.Loader.dll_ reference assembly, which is fine for Xamarin.Android projects.

**Comment by dgerding** [comment]
THANKS!

**Comment by kerberosargos** [comment]
@brendanzagaeski Thank you very much for your help

**Comment by EmilAlipiev** [comment]
This is really strange issue because I am able reproduce this in Azure Devops Pipelines if I choose build machine as "windows-latest" but it works fine using "windows-2019". What is windows-latest build machine on Azure Pipelines actually?

**Comment by Agredo** [comment]
I am getting this with Xamarin Forms for Android. VIsual Studio 2019 Builds it perfectly for Release. Visual Studio 2022 can not build it with this error. Its the same project! 
This happens since some VS2022 updates. 
![image](https://user-images.githubusercontent.com/16531090/164888650-395bb0c5-96f9-4af8-8508-45714d6b096f.png)
