### ISSUE TITLE
ResX Localization Broken

### ISSUE THREAD

**Issue by divil5000** [xamarin/xamarin-android#4805]
You seem to have broken ResX localization in a recent version of Xamarin.Android. I found issue #4664 and downloaded the latest version of VS (I'm on 16.6.2) but the issue persists. This has broken our app and is now holding up deployment to tens of thousands of users.

I reproduced the issue with a blank app straight from one of your templates, which I will attach.

It has a ResX file with a single string resource, which has been localized into German. Pressing the floating button in the demo app will pop up a toast that should contain the default English text then the German text, but instead the default English text appears twice because for some reason it is not finding the German resources.

NOTE: I stripped the bin and obj folders out of the zip file because it was 54mb with them.
[app1.zip](https://github.com/xamarin/xamarin-android/files/4765623/app1.zip)

### Steps to Reproduce

1. Run the sample app
2. Press the floating button
3. Observe in the toast that the English text is displayed twice

### Expected Behavior

Should display Some English Text, German!

### Actual Behavior

Displays Some English Text, Some English Text

### Version Information

Microsoft Visual Studio Professional 2019
Version 16.6.2
VisualStudio.16.Release/16.6.2+30204.135
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   16.6.948.25768
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2020603+b3ac44798c16fff5b95dbcfe62dea84aa9a1bd72
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.6.948.25768
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.948.25768
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.4.6000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   16.6.948.25768
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.4.6000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.4.6000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.4.6000.0
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   16.0
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.4.6000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.50+g25aae5a24a.R
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   16.6.17 (9692114)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62006.03190
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.20417.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-4.20251.5+910223b64f108fcf039012e0849befb46ace6e66
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20217.4+1c969cac25e2d38d71872efe6c8226029e42bb59
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Kubernetes   1.0
Visual Studio Tools for Kubernetes

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.318 (remotes/origin/d16-6@66afc5421)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.40 (1f1466f)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 165f4b0
    Java.Interop: xamarin/java.interop/d16-6@2cab35c
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-6@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.2.1 (29c4ea7)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Log File

[logcat.zip](https://github.com/xamarin/xamarin-android/files/4765630/logcat.zip)

**Comment by brendanzagaeski** [comment]
Thanks for submitting this item, and thanks for test case! This indeed reveals a scenario where the fix from #4664 has not restored the original behavior that Xamarin.Android had in version 10.2. The difference compared to the other test cases in #4664 is that in this new case, the _.resx_ files are located within the Android application project itself rather than in a library.

The same temporary workaround from #4664 works for this case too, so I'll add that as a first step on this item.

### Workaround

Use a text editor to open the _.csproj_ file for the affected app project, and replace the end of the file with the following lines:

```xml
  <Target Name="_ResolveSatellitePaths"
    DependsOnTargets="_ResolveAssemblies">
    <ResolveAssemblyReference
        AllowedAssemblyExtensions="$(AllowedReferenceAssemblyFileExtensions)"
        AssemblyFiles="@(ResolvedUserAssemblies)"
        AutoUnify="$(AutoUnifyAssemblyReferences)"
        FindDependencies="True"
        FindRelatedFiles="False"
        FindSatellites="True"
        SearchPaths="$(AssemblySearchPaths)"
        TargetFrameworkMoniker="$(TargetFrameworkMoniker)"
        TargetFrameworkMonikerDisplayName="$(TargetFrameworkMonikerDisplayName)"
        TargetFrameworkDirectories="$(TargetFrameworkDirectory)">
      <Output TaskParameter="SatelliteFiles" ItemName="_AndroidResolvedSatellitePaths"/>
    </ResolveAssemblyReference>
  </Target>
</Project>
```

Then clean, rebuild, and redeploy the project.

Explanation: This reverts the `_ResolveSatellitePaths` MSBuild target to the previous implementation as used in Xamarin.Android 10.2.

**Comment by brendanzagaeski** [comment]
### Preliminary investigation notes for the Xamarin team

As in <https://github.com/xamarin/xamarin-android/issues/4664>, command line builds work correctly because the Build and Install steps all happen together. But in deployments from Visual Studio, where the Build step happens separately before the Install step, the problem this time is that `@(IntermediateSatelliteAssembliesWithTargetPath)` is empty.

During the Build step `ComputeIntermediateSatelliteAssemblies` adds the satellite assembly to `@(IntermediateSatelliteAssembliesWithTargetPath)`:

```
Target "ComputeIntermediateSatelliteAssemblies: (TargetId:116)" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets" from project "C:\Temp\App1\App1.csproj" (target "CreateSatelliteAssemblies" depends on it):
Added Item(s): 
    IntermediateSatelliteAssembliesWithTargetPath=
        obj\Release\90\de\App1.resources.dll
                Culture=de
                TargetPath=de\App1.resources.dll
Done building target "ComputeIntermediateSatelliteAssemblies" in project "App1.csproj".: (TargetId:116)
```

But during the Install step, `ComputeIntermediateSatelliteAssemblies` doesn't run at all.

As an experiment, I tried adjusting `$(SignAndroidPackageDependsOn)` by replacing the bottom of the _.csproj_ file with:

```
  <PropertyGroup>
    <SignAndroidPackageDependsOn Condition=" '$(BuildingInsideVisualStudio)' == 'True' ">
      $([MSBuild]::Unescape($(SignAndroidPackageDependsOn.Replace('ResolveReferences;', 'ResolveReferences;$(CreateSatelliteAssembliesDependsOn);'))))
    </SignAndroidPackageDependsOn>
  </PropertyGroup>
</Project>
```

Unfortunately, that did not resolve the issue because the input `@(EmbeddedResource->'%(OutputResource)')` metadata needed for the `$(CreateSatelliteAssembliesDependsOn)` targets doesn't get set.

**Comment by divil5000** [comment]
Many thanks Brendan, the workaround appears to indeed work around the bug.

This is not the first time resx localization has been broken in a "stable" VS release. It's disturbing that apparently not many people are affected, because that implies not many people are actually using Xamarin to build and publish serious apps for Android.

Please could I formally request that regression testing is added to your release process so that if resx localization is ever broken again in the future, you do not ship that code?

**Comment by jonathanpeppers** [comment]
@divil5000 I wanted to follow up on the comment:

> This has broken our app and is now holding up deployment to tens of thousands of users.

We think the issue only occurs while developing inside Visual Studio. Are you seeing this problem even when you app is shipped to Google Play? Are you shipping your app from a CI system or archiving inside Visual Studio?

Please review #4813 if you think the test is sufficient, thanks! We've added tests around `.resx` files and IDE builds that we did not have before 16.6 shipped.

**Comment by divil5000** [comment]
It was indeed Visual Studio; for Android deployments we just tend to do a full rebuild in VS and archive the output. Luckily the issue was caught before we shipped to Google Play; it was caught during public beta testing where we host the APK on our own website.

I don't think I'm qualified to review your tests, but I am happy to take your word for it that this sort of thing can't be broken in the future and I appreciate your help.

**Comment by jonathanpeppers** [comment]
@divil5000 we think the archive process in Visual Studio would also work in 16.6 as-is. You can check just by inspecting the `.apk` file with a zip utility and see if the satellite assemblies are inside it. Let us know otherwise, thanks!

**Comment by divil5000** [comment]
No, it certainly did not work. Our normal process is to do a rebuild then archive, save the resulting APK and upload it.

Looking inside our latest published beta (built using the above process before the workaround) I cannot see any subfolders within the assemblies folder, which I guess might explain why the localization isn't working?

**Comment by brendanzagaeski** [comment]
> we think the archive process in Visual Studio would also work in 16.6 as-is.

> No, it certainly did not work.

Ohhhhh, I just noticed why **Build > Archive** often won't work. If the project has a custom keystore set for use in the Release configuration, then **Build > Archive** runs:

- `Build`
- `SignAndroidPackage`

Instead of:

- `Build`
- `PackageForAndroid`

When the second target is `SignAndroidPackage` instead of `PackageForAndroid`, the problem happens. I'll plan to correct the release note about the fix for #4664 to account for this.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this again when a Release version is available that includes the fix.

Fix included in Xamarin.Android 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7 Preview 4. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.7 Preview 4. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.0.0.3.

Fix included on Windows in Visual Studio 2019 version 16.7. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.7. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
