### ISSUE TITLE
RemoveUseLatestSdkUsageHandler - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MagicAndre1981** [xamarin/xamarin-android#4922]
In VS2019 16.4.11 I have the issue that the properties of Android part of Xamarin.Forms app are empty:

![xamarin_android_properties_empty](https://user-images.githubusercontent.com/8274816/87519299-b18b5200-c681-11ea-9244-4bda6e750889.png)

In the .Ide.log I see this:

```
Xamarin.VisualStudio.Android.RemoveUseLatestSdkUsageHandler|Error|0|Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.VisualStudio.Android.RemoveUseLatestSdkUsageHandler.ExecuteAsync(RemoveUseLatestSdkUsageCommand command, CancellationToken cancellation) in E:\A\_work\412\s\src\Core\VisualStudio.Android\CommandHandlers\RemoveUseLatestSdkUsageHandler.cs:line 36
```

I have no entry `<AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>` in the csproj for Android part of the Xamarin.Forms app.

VS2019 16.4.11 - servicing baseline
WIn10 18362
Xamarin 16.4.000.313(d16-4@793df40)
Xamarin.Android SDK 10.1.4.0 (d16-4@e44d1ae)

**Comment by MagicAndre1981** [comment]
If I add the  entry `<AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>` in the csproj, I can open the csproj, but it gets removed (which is what the function is supposed to do).

If I close the project and open it again, I have the same issue again that prevents me from compiling the app.

## Workround

add `<AndroidUseLatestPlatformSdk>True</AndroidUseLatestPlatformSdk>` in the android csproj each time before opening the sln.

Now I can compile it, but this is ugly. 


In VS2017 15.9.x I don't have the issue.

**Comment by brendanzagaeski** [comment]
Thanks for the report. Based on the line where the exception is thrown in _RemoveUseLatestSdkUsageHandler.cs_, it appears the error in the _*.Ide.log_ file is not related to the `AndroidUseLatestPlatformSdk` MSBuild property itself but instead something a little earlier in the process. My guess would be that the exception in `RemoveUseLatestSdkUsageHandler` is another secondary symptom caused by whatever primary problem is also causing trouble loading the information in the project property pages.

If you might be able to share them, I think the _.sln_ and _.csproj_ files from your specific solution might contain additional useful clues about what's happening. If you could attach those files to this issue, that would be perfect. If the files contain information you need to keep private, you can remove the private information before attaching them or create a new Visual Studio Developer Community feedback item via **Help > Send Feedback > Report a Problem** in Visual Studio and attach the files there instead (attachments on new Developer Community items are only visible to the Microsoft team).

Additionally, if you are getting a build error, the diagnostic MSBuild output might provide helpful additional clues, so if you could attach that too, that would be excellent. If you are not getting a build error, then if you could describe what happens when you attempt to build the project that prevents it from succeeding, that would be perfect.

Here are the steps to collect the diagnostic build output:

1. Set **Tools > Options > Project and Solutions \[section\] > Build and Run \[subsection\] > MSBuild project build output verbosity** to **Diagnostic**.
2. Repeat the steps to reproduce the issue.
3. Once you get the circular dependency build error, open the **View > Output** window, and set **Show output from** to **Build**.
4. Make sure the **Output** window is selected, and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.
5. Attach back the text file in a new comment on this item. Note that by default that file will contain some details about your environment and project. If the build output contains information you need to keep private, you can remove the private information before attaching it or create a new Visual Studio Developer Community feedback item via **Help > Send Feedback > Report a Problem** in Visual Studio and attach the build output there instead (attachments on new Developer Community items are only visible to the Microsoft team). If you are already planning to create a Developer Community feedback item to attach the _.sln_ and _.csproj_ files privately, use the same feedback item to attach the build output too.

After you complete these steps, you can set **Tools > Options > Project and Solutions [section] > Build and Run [subsection] > MSBuild project build output verbosity** back to **Minimal** to avoid adding extra time to your future builds.

Thanks in advance for the additional info!

**Comment by MagicAndre1981** [comment]
@brendanzagaeski 

I can't share the sln or csproj, but today I opened it with VS2019 16.6.x on a different device and here it works. The items show up and I can compile the app everytime. The xamarin log shows no error. 

So the 16.4 branch has a bug, that was fixed and not backported.

**Comment by brendanzagaeski** [comment]
Ah, perfect. Thanks for trying the scenario with the newer version and updating this issue with the results. I'll close this item as resolved in Visual Studio 2019 version 16.6.

**Comment by MagicAndre1981** [comment]
@brendanzagaeski

but the 16.4 is servicing baseline which is supposed to get fixes. Are xamarin issues excluded from backports?

**Comment by brendanzagaeski** [comment]
At least for Xamarin, updates to earlier versions would generally only happen for particular security issues or in some special cases, widespread issues that block a large number of users. I believe this is similar to how other parts of Visual Studio are updated for the servicing baseline. The updates to those older versions wouldn't include all bug fixes, but instead specific fixes needed "[to remain secure and in support](https://docs.microsoft.com/visualstudio/releases/2019/servicing#support-options-for-enterprise-and-professional-customers)."

**Comment by MagicAndre1981** [comment]
ok, thanks for the answer.
