### ISSUE TITLE
Add response file support to BindingsGenerator task

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#4956]
With the explosion of referenced assemblies due to AndroidX, the BindingsGenerator task is bumping up against the 32K limit for command lines:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android
\Xamarin.Android.Bindings.targets(325,5): warning MSB6002: The command-line for the
"BindingsGenerator" task is too long. Command-lines longer than 32000 characters are likely to
fail. Try reducing the length of the command-line by breaking down the call to "BindingsGenerator" 
into multiple calls with fewer parameters per call. [D:\X\GPS-FB-ax_u_202002\generated
\com.google.firebase.firebase-inappmessaging\com.google.firebase.firebase-inapp
messaging.csproj]
```
We added support for using a response file for `generator.exe` here: https://github.com/xamarin/java.interop/pull/665, however we still need to update the MSBuild task to build and pass the response file.

Details for usage are in the linked PR.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android SDK version 11.0.99.34.

Fix included on Windows in Visual Studio 2019 version 16.8 Preview 2. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.8 Preview 2. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.1.0.17.

Fix included on Windows in Visual Studio 2019 version 16.8. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.8. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
