### ISSUE TITLE
Cannot create AAB Release bundle with app with native compiled libraries

### ISSUE THREAD

**Issue by luminixinc** [xamarin/xamarin-android#4998]
Hi there,

We have hit an issue trying to bundle a *Release* build of our Xamarin.Forms/Xamarin.Android app as AAB.

The bundling step fails with the following build output:

```
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -Xmx1G -jar "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\bundletool.jar" build-bundle --modules obj\Release\90\android\bin\base.zip --output obj\Release\90\android\bin\com.companyname.nativehelloapp.aab --config C:\Users\BuildUser\AppData\Local\Temp\tmpDBCF.tmp 
Files under lib/ must have .so extension, found 'lib/x86/gdbserver'.
com.android.tools.build.bundletool.model.exceptions.BundleFileTypesException$InvalidFileExtensionInDirectoryException: Files under lib/ must have .so extension, found 'lib/x86/gdbserver'.
```

Here is a [reduced testcase](https://github.com/luminixinc/XamarinAndroidNativeDebugTest) that showcases the build issue in detail, and speculates about a potential fix.

**Comment by jonathanpeppers** [comment]
@luminixinc it doesn't seem like `bundletool` allows a file in `lib` without an `.so` extension:

https://github.com/google/bundletool/blob/ae0fc0162fd80d92ef8f4ef4527c066f0106942f/src/main/java/com/android/tools/build/bundletool/validation/BundleFilesValidator.java#L97-L103

So, I tried something like this: https://github.com/xamarin/xamarin-android/compare/master...jonathanpeppers:bundletool-libs-without-so

But it just yields a different error:

```
[BT File 'root/lib/arm64-v8a/gdbserver' uses reserved file or directory name 'lib'.
```

It seems like `bundletool` does not have a way for this to work. Can you put the file in a different place, or name it `gdbserver.so`?

If you see another way to solve this problem, let me know, thanks.

**Comment by luminixinc** [comment]
@jonathanpeppers our project is not directly including `gdbserver`, it appears to be included by Xamarin.Android's [Microsoft.Cpp.Android.targets](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets#L73)

Have you tried our proposed workaround, which edits the `Microsoft.Cpp.Android.targets` file?  This is linked at the end of the README.md in the reduced testcase repository.

Thanks!

**Comment by jonathanpeppers** [comment]
Does this smaller diff still solve the problem?
```diff
diff --git a/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets b/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xa
marin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets
index 6cd7e7587..6835e6b34 100644
--- a/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets
+++ b/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Common/ImportAfter/Microsoft.Cpp.Android.targets
@@ -70,7 +70,7 @@ Copyright (C) 2014 Xamarin. All rights reserved.

         <ItemGroup Condition="'@(NativeLibraryPaths)' != ''">
             <AndroidNativeLibrary Include="@(NativeLibraryPaths)"
-                                  Condition="'%(Extension)' == '.so' Or '%(FileName)' == 'gdbserver'">
+                                  Condition="'%(Extension)' == '.so' Or ('$(Configuration)' == 'Debug' And '%(FileName)' == 'gdbserver')">
                 <Abi>$(NativeLibraryAbi)</Abi>
             </AndroidNativeLibrary>
             <Content Include="@(NativeLibraryPaths)"
```
I can make this change if it still solves the problem for you. Unfortunately, these C++ MSBuild targets aren't well tested/maintained at the moment.

A pull request would be welcome here, too. Thanks!

**Comment by luminixinc** [comment]
Yes this more concise diff works for us, thank you!

We do find it a little concerning when you write that "these C++ MSBuild targets aren't well tested/maintained".  We hope that native interop from .NET to the Android NDK  (C/C++ layer) is something that will continue to be well maintained in the build system as well as at runtime, including the support of native debugging.

Interestingly, this issue only came about because we are switching to a new AAB publishing format.  The issue (gdbserver bundled in Release) appears to have been latent in the older APK (including multi-APK) publishing format.  (But the Google tooling does not error out for the APK publishing).

Anyway thank you for a quick reply!  Again, your diff looks good (for both AAB and APK publishing), so hopefully we can see that fix (or an equivalent) soon in a Xamarin.Android release.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android SDK version 11.1.0.3.

Fix included on Windows in Visual Studio 2019 version 16.8 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.8 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.1.0.17.

Fix included on Windows in Visual Studio 2019 version 16.8. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.8. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
