### ISSUE TITLE
error XA0119: Using the shared runtime and Android App Bundles  at the same time is not currently supported.

### ISSUE THREAD

**Issue by cschwarz** [xamarin/xamarin-android#5024]
### Steps to Reproduce

1. Create an empty Xamarin Forms Android project
2. msbuild.exe XamarinAabIssue.Android.csproj "/p:Configuration=Release;AndroidPackageFormat=aab" --> compiles successful
3. Add an empty Xamarin Android Library project and reference it in the Android project
4. msbuild.exe XamarinAabIssue.Android.csproj "/p:Configuration=Release;AndroidPackageFormat=aab" -->

error XA0119: Using the shared runtime and Android App Bundles at the same time is not currently supported. Use the shared runtime for Debug configurations and Android App Bundles for Release configurations.

### Expected Behavior

This should work like in versions before VS 16.7

### Actual Behavior

error XA0119: Using the shared runtime and Android App Bundles at the same time is not currently supported. Use the shared runtime for Debug configurations and Android App Bundles for Release configurations.

### Version Information

Microsoft Visual Studio Community 2019 (2)
Version 16.7.1
VisualStudio.16.Release/16.7.1+30406.217
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA178
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.7.532.28833
ASP.NET and Web Tools 2019

ASP.NET Core Razor Language Services   16.1.0.2035807+72d099b977d3a85e65fa3b0614ca8cfc803fef02
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2019   16.7.532.28833
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.7.532.28833
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.7.532.28833
Azure Functions and Web Jobs Tools

C# Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30701.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.79+ge3567815aa.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.62008.03130
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.20702.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.7.0-6.20375.2+34202cc2f3e869fd70a26d8237f4552cf9e192cf
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.10.0.0 for F# 4.7   16.7.0-beta.20361.3+3ef6f0b514198c0bfa6c2c09fefe41a740b024d5
Microsoft Visual F# Tools 10.10.0.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

WiX Toolset Visual Studio Extension   1.0.0.4
WiX Toolset Visual Studio Extension version 1.0.0.4
Copyright (c) .NET Foundation and contributors. All rights reserved.

Xamarin   16.7.000.440 (d16-7@358f3c6)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.7.0.495 (remotes/origin/d16-7@79c0c522c)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.7.85 (1bcbbdf)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   11.0.0.3 (d16-7/aca845b)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 83105ba
    Java.Interop: xamarin/java.interop/d16-7@1f3388a
    ProGuard: Guardsquare/proguard/proguard6.2.2@ebe9000
    SQLite: xamarin/sqlite/3.32.1@1a3276b
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-7@017078f

Xamarin.iOS and Xamarin.Mac SDK   13.20.2.2 (817b6f72a)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by brendanzagaeski** [comment]
Thanks for submitting this issue. As a first quick step, I'll add a couple workaround options for this.

### Workaround options

- Add `/p:AndroidUseSharedRuntime=false` to the `msbuild` command invocation:

  ```
  msbuild.exe XamarinAabIssue.Android.csproj "/p:Configuration=Release;AndroidPackageFormat=aab;AndroidUseSharedRuntime=false"
  ```

- Or, open the _.csproj_ project file for the Xamarin.Android library project [in Visual Studio](https://docs.microsoft.com/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#edit-project-files-in-visual-studio) or another text editor, find an existing closing `</PropertyGroup>` tag in the file, and add the following additional `<PropertyGroup>` element after it:

   ```xml
   <PropertyGroup>
     <AndroidUseSharedRuntime>false</AndroidUseSharedRuntime>
   </PropertyGroup>
   ```

Either of these workarounds would be OK to leave in place pretty much forever, but for the sake of simplicity, you'd like want to remove the workaround once a fix for this issue is available.

Explanation: Xamarin.Android library projects are currently seeing a default value of `true` for the `AndroidUseSharedRuntime` MSBuild property, and that is triggering the _is not currently supported_ error for the project. Setting `/p:AndroidUseSharedRuntime=false` on the command line overrides that property value in all of the projects. In the Release configuration, the property needs to be `false` anyway, so there's no harm in overriding it to `false` across all of the projects. That said, it'll also work to set it to `false` just within the _.csproj_ project file for the library project.

**Comment by brendanzagaeski** [comment]
@jonathanpeppers, @dellis1972, this an interesting little issue. I think you folks will be the best to say which approach to take to fix it.

As I understand it, what happens is:

1. Setting `/p:AndroidPackageFormat=aab` on the command line means that _all_ projects get that value, including the library project. (In contrast, if `AndroidPackageFormat` is set to `aab` in just the _.csproj_ file for the app project, this problem doesn't happen.)
2. Library projects see `AndroidUseSharedRuntime`=`true` by default somehow.
3. Library projects currently do run the `_CheckNonIdealConfigurations` target, although technically I think none of the checks there currently apply to library projects.

So there are at least three approaches that might work:

- Change the default value of `AndroidUseSharedRuntime` to `false` for library projects.
- Avoid running `_CheckNonIdealConfigurations` (or a subset of the checks in it) for library projects.
- Do nothing for now because, barring unexpected complications, this check will be removed completely when the shared runtime is removed in the upcoming d16-9 branch. 

What's strange is, from looking at the current _.targets_ files, I don't see why `AndroidUseSharedRuntime` is currently `true` by default in library projects. The only line I see that affects the value of that property is a line that sets it to `false`:

https://github.com/xamarin/xamarin-android/blob/aca845ba65b75721d3b38edafb8e001ed0bb5799/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L195

**Comment by cschwarz** [comment]
Thank you for the workarounds, they are working fine.

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Preview version of Xamarin.Android has now been published that includes the fix for this item. The fix is not yet included in a Release version. I will update this item again when a Release version is available that includes the fix.

Fix included in Xamarin.Android SDK version 11.1.0.3.

Fix included on Windows in Visual Studio 2019 version 16.8 Preview 3. To try the Preview version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) in [Visual Studio Preview](https://visualstudio.microsoft.com/vs/preview/).

Fix included on macOS in Visual Studio 2019 for Mac version 8.8 Preview 3. To try the Preview version that includes the fix, check for the latest updates on the **Preview** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).

**Comment by brendanzagaeski** [comment]
_Release status update_

A new Release version of Xamarin.Android has now been published that includes the fix for this item.

Fix included in Xamarin.Android SDK version 11.1.0.17.

Fix included on Windows in Visual Studio 2019 version 16.8. To get the new version that includes the fix, [check for the latest updates](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019) or install the most recent release from <https://visualstudio.microsoft.com/downloads/>.

Fix included on macOS in Visual Studio 2019 for Mac version 8.8. To get the new version that includes the fix, check for the latest updates on the **Stable** [updater channel](https://docs.microsoft.com/visualstudio/mac/update).
