### ISSUE TITLE
Android Emulator crash on launch (base.OnCreate(savedInstanceState))

### ISSUE THREAD

**Issue by Rahulatheist** [xamarin/xamarin-android#5029]
Exception on line -> base.OnCreate(savedInstanceState); in MainActivity class OnCreate()
Exception details:
Java.Lang.ClassNotFoundException
Message=Didn't find class "crc643f46942d9dd1fff9.PowerSaveModeBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.boeing.MobileQSV2-x4j2-ErAhg_vCmw6z_iAWw==/base.apk"],nativeLibraryDirectories=[/data/app/com.boeing.MobileQSV2-x4j2-ErAhg_vCmw6z_iAWw==/lib/x86, /data/app/com.boeing.MobileQSV2-x4j2-ErAhg_vCmw6z_iAWw==/base.apk!/lib/x86, /system/lib, /vendor/lib]]

This is happening when I am deploying my application in Android Emulator (Pixel 2 Pie 9.0). The splash page comes and then this error appears. I am able to deploy it properly 1 out of 5 try.

### Basic Information

- Version with issue: Android Emulator (Pixel 2 Pie 9.0) on Microsoft Visual Studio Professional 2019 Version 16.7.1

**Comment by grendello** [comment]
@Rahulatheist we will need more information in order to diagnose the issue. Please provide the following:

 * Full build binlog from msbuild
   * remove all `bin` and `obj` directories in your solution
   * build from command line with `msbuild /bl`
   * attach the resulting `msbuild.binlog` file here
 * Logcat from the crash on device/emulator:
   * Deploy the application after **removing** its previous version from device/emulator
   * Open VS developer prompt and issue the following commands:
```shell
> adb shell setprop debug.mono.log default,assembly,timing=bare
> adb logcat -G 16M
> adb logcat -c
```
  * Launch the application and after it crashes go back to the developer prompt and issue the following commant:
```shell
> adb logcat -d > crash.txt
```
  * Attach `crash.txt` here

Thanks!

**Comment by dellis1972** [comment]
What appears to be happening is some classes in the classes.dex file are not being found.  The PowerSaverBroadcastReceiver is being compiled as the source file appears in the build log. 

Are you using the enhanced fast deployment system? i.e `<AndroidFastDeploymentType>Assemblies:Dexes</AndroidFastDeploymentType>` ?

 
In order to look at this further we are going to need some more detailed diagnostics.

From a Visual Studio 2019 Developer command prompt in your project directory can you delete both the `bin` and `obj` directories then do the following

```
msbuild <your android csproj> /t:Install /bl 
```

This will do a full build and install the app on the device. Then run the app on the device, if it does not crash run the above command again. If you need to make small changes to the app then do so. What we need is the full log for an install where the app crashes. This is the easiest way to get the data we need. The logs from the IDE are not full diagnostic logs and they split up a Build and an Install. 

The above command will produce a file called `msbuild.binlog`. This is the file we need to diagnose this issue, you should be able to attach it to this Issue. If not you can compress it to a zip and attach that.
