### ISSUE TITLE
TimeZoneNotFoundException on calling DateTimeOffset.Now

### ISSUE THREAD

**Issue by Cheesebaron** [xamarin/xamarin-android#5080]
We have a device in the wild from a user, which crashes with `TimeZoneNotFoundException` on startup, when we try to write to Serilog Logger. However, it seems to happen when DateTimeOffset.Now is called within Serilog.

User seems to be using English locale according to AppCenter

### Steps to Reproduce

1. Call `DateTimeOffset.Now` on a Xiaomi Redmi Note 9 (M2003J15SC)

### Expected Behavior

No crash

### Actual Behavior

Throws `System.TimeZoneNotFoundException`

### Version Information

Android 10
Xiaomi Redmi Note 9 (M2003J15SC)

Built with on Azure DevOps macOS 10.15 agent on 20200703 with:

Xamarin.Android 10.3.1
Mono 6.8.0.123

### Log File

AppCenter Crash report:
https://gist.github.com/Cheesebaron/06ab58af391d1b8886a512c26d6c3063

**Comment by jonpryor** [comment]
Related:

  * https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs
  * https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.cs#L71-L86

AppCenter stack trace:

```
System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
  at System.TimeZoneInfo.get_Local ()
  at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc (System.DateTime time, System.Boolean& isAmbiguousLocalDst)
  at System.DateTime.get_Now ()
  at System.DateTimeOffset.get_Now ()
  at Serilog.Core.Logger.Write (Serilog.Events.LogEventLevel level, System.Exception exception, System.String messageTemplate, System.Object[] propertyValues)
  at Serilog.Core.Logger.Write (Serilog.Events.LogEventLevel level, System.String messageTemplate, System.Object[] propertyValues)
  at Serilog.Core.Logger.Information (System.String messageTemplate)
  at TrackMan.DrivingRangeApp.Droid.Setup`1[TApplication].CreateLogProvider ()
  at MvvmCross.Core.MvxSetup.InitializeLoggingServices ()
  at MvvmCross.Core.MvxSetup.InitializePrimary ()
  at MvvmCross.Core.MvxSetupSingleton.StartSetupInitialization ()
  at MvvmCross.Core.MvxSetupSingleton.InitializeAndMonitor (MvvmCross.Core.IMvxSetupMonitor setupMonitor)
  at MvvmCross.Droid.Support.V7.AppCompat.MvxSplashScreenAppCompatActivity.OnCreate (Android.OS.Bundle bundle)
  at TrackMan.DrivingRangeApp.Droid.Shared.SplashScreen.OnCreate (Android.OS.Bundle bundle)
  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.19(intptr,intptr,intptr)
```

[`TimeZoneInfo.Android.cs`](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs) has code to parse the Android TimeZone database.

`TimeZoneNotFoundException` should only be thrown if [`AndroidTimeZones.Local`](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs#L556-L561) returns `null`, which can return `null` for a variety of reasons, including:

  * [`AndroidTimeZones.GetDefaultTimeZoneName()`](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs#L569-L594) returns null (because it eventually passes `null` as the `id` parameter to `TimeZoneInfo`, which throws, which is caught, causing `null` to be returned from [`AndroidTimeZones.GetTimeZone(string, string)`](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs#L569-L594)
  * `AndroidTimeZones.db` is `null`, meaning no known TimeZone DB could be found
  * The default time zone is not null, and a TimeZone DB could be found, but when trying to parse the TimeZone buffer data, an exception was thrown
  * …something else?

Without hardware access, it's hard to say *why* `TimeZoneInfo.Local` is null.  (Couldn't determine TimeZone name?  No TimeZone DB found?)

That said, this does raise a question:

Can we have a Java-based fallback path?  Is there a way to use e.g. [`java.util.TimeZone`](https://developer.android.com/reference/java/util/TimeZone) to construct the required data needed to populate a `TimeZoneInfo` instance?

**Comment by grendello** [comment]
[TimeZoneInfo.Android](https://github.com/mono/mono/blob/2020-02/mcs/class/corlib/System/TimeZoneInfo.Android.cs) might fail to find a timezone on devices running newer Android versions because it doesn't search the location that has the updated database. In newer Android versions (10 for sure, maybe 9 as well) the tzdb data is shipped in a separate component that's updatable via the Play Store. The data package is then mounted on device:

```
/dev/block/dm-8 on /apex/com.android.tzdata@292500000 type ext4 (ro,dirsync,seclabel,nodev,noatime)
/dev/block/dm-8 on /apex/com.android.tzdata type ext4 (ro,dirsync,seclabel,nodev,noatime)
```

The two locations both contain the tzdata files:

```shell
crosshatch:/ $ ls -l /apex/com.android.tzdata/etc/tz                                                                                                                                                                                                                                                  
total 532
-rw-r--r-- 1 system system     17 1970-01-01 01:00 tz_version
-rw-r--r-- 1 system system 504038 1970-01-01 01:00 tzdata
-rw-r--r-- 1 system system  32434 1970-01-01 01:00 tzlookup.xml

crosshatch:/ $ ls -l '/apex/com.android.tzdata@292500000'/etc/tz                                                                                                                                                                                                                                      
total 532
-rw-r--r-- 1 system system     17 1970-01-01 01:00 tz_version
-rw-r--r-- 1 system system 504038 1970-01-01 01:00 tzdata
-rw-r--r-- 1 system system  32434 1970-01-01 01:00 tzlookup.xml
```

The files appear to be identical:

```shell
crosshatch:/ $ md5sum /apex/com.android.tzdata/etc/tz/tzdata                                                                                                                                                                                                                                      
1b88cc17a195d24c07e796d487f45a4e  /apex/com.android.tzdata/etc/tz/tzdata

crosshatch:/ $ md5sum '/apex/com.android.tzdata@292500000/etc/tz/tzdata'                                                                                                                                                                                                                          
1b88cc17a195d24c07e796d487f45a4e  /apex/com.android.tzdata@292500000/etc/tz/tzdata
```

And they probably are just mounts of the same apex:

```shell
crosshatch:/ $ cat /apex/com.android.tzdata/apex_manifest.json                                                                                                                                                                                                                                        
{
  "name": "com.android.tzdata",
  "version": 292500000
}
```

And the version of the database found in `/system/usr/share/zoneinfo` appears to be 11 years old (this is on an up-to-date Pixel 3 XL running Android 10):

```shell
crosshatch:/ $ ls -l /system/usr/share/zoneinfo/                                                                                                                                                                                                                                                      
total 500
-rw-r--r-- 1 root root     17 2009-01-01 01:00 tz_version
-rw-r--r-- 1 root root 504953 2009-01-01 01:00 tzdata
```

It seems Mono needs to be fixed to add `/apex/com.android.tzdata/etc/tz/` as the first location it checks for the database to parse. @jonpryor I don't think there's need to involve Java at this point :)

**Comment by grendello** [comment]
Mono PR opened: https://github.com/mono/mono/pull/20349

**Comment by grendello** [comment]
Xamarin.Android now uses Mono with the required patches. If the issue still appears, please reopen this report.
