### ISSUE TITLE
Error building a Xamarin Android Bindings project since upgrading to VS 16.7.3

### ISSUE THREAD

**Issue by shoes03** [xamarin/xamarin-android#5133]
Upgraded Visual Studio to 16.7.3 for Windows.

Have a binding project for an aar file needed for the solution.

Since upgrading from 16.6.5 to 16.7.3, we are no longer able to build the bindings project.

Error:
                
The specified task executable "generator.exe" could not be run. System.ComponentModel.Win32Exception (0x80004005): 
The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute() 

Run

**Comment by jpobst** [comment]
We fixed this issue here: https://github.com/xamarin/xamarin-android/issues/4956.  The fix is available in the 16.8 previews.

You can also try moving your project to a shorter path as a workaround, like putting it in `C:\code` instead of `C:\User\username\Documents\MyProject\etc`.  Sometimes that is enough to fix it, but not always.
