### ISSUE TITLE
Cannot a build an application with Android Library on VS2019, VS2019pre but works with Rider

### ISSUE THREAD

**Issue by EmilAlipiev** [xamarin/xamarin-android#5141]
My xamarin.forms project has an android library project referencing on main xamarin.android project. That Android Library project has some resources under the drawable folders as pngs. When I try to build the project on VS2019 16.7.3, VS2019pre 16.8.0 pre3 , I am getting an error message that resources cannot be found. VS2019 changes Resource.Designer.cs automatically and  makes a lot of changes, it seems to remove resource references. 
It just makes no sense why project isn't building. I have no single change and project was building before a VS update a few days ago, it probably updated xamarin.android as well but Rider is still building same project fine. 

I tried another project without xamarin android library and it still building

### Steps to Reproduce

1. No idea
2. 
3.

**Comment by EmilAlipiev** [comment]
This seems to be related https://github.com/xamarin/xamarin-android/pull/5107
Building each projects one by one as the order .net standard-> Xamarin.Android.Library-> Xamarin.Android, solves the problem.

**Comment by jpobst** [comment]
@jonathanpeppers I think you already fixed this, but I'll let you close it with a link to the appropriate issue/PR.

**Comment by jonathanpeppers** [comment]
A customer filed the same issue here, you can follow/upvote to get notified when the fix is available:

https://developercommunity.visualstudio.com/content/problem/1144910/many-compilation-errors-cs0117-in-xamarinandroid-p.html

The fix should be available publicly in 16.8 Preview 4.

The workaround you mentioned would be fine, you can also set this to 1, but this might not be ideal:

![image](https://user-images.githubusercontent.com/840039/94737873-2fcbcc00-0334-11eb-9689-061f33368efe.png)
