### ISSUE TITLE
Java.lang.NoSuchFieldError: no “I” field “value” in class “Ljava/lang/Integer;” or its superclasses - Android 10

### ISSUE THREAD

**Issue by singhal2** [xamarin/xamarin-android#5199]
I understand that the following might not be enough to debug the problem. I am trying to get ideas so as to find a workaround to this problem. Therefore, please do not hesitate to ask for more information. Any help is appreciated. 

I have a .so android library which I am integrating into a Xamarin Forms project. The library helps the app connect to an IoT device. As the library methods are of the following signature, I decided to write a java wrapper to simplify the parameters and create an aar file. Afterwards, I natively bind the aar and use it as a dll in my project. I DO NOT have the library source code available, therefore I am unable to debug it further. It is important to note that the problem in Xamarin only occurs when the Compile Target is > 10. Otherwise, it works fine. My guess is that the latest Updates to non-SDK interfaces broke the application.

**Method signature:**
`public static native int ReadParams(String token, StringBuilder serial, StringBuilder ssid, StringBuilder password, StringBuilder sensor, Integer keepAlive);`

**Call from Java wrapper**
```
StringBuilder strSerial = new StringBuilder();
StringBuilder strssid = new StringBuilder();
StringBuilder strpassword = new StringBuilder();
StringBuilder strsensor = new StringBuilder();
Integer keepAlive = new Integer(0);
//Crash on below line
int response = EPM002Lib.ReadParams(token, strSerial, strssid, strpassword, strsensor, keepAlive);
```
**Stacktrace:**

> --- End of managed Java.Lang.IncompatibleClassChangeError stack trace ---
> java.lang.NoSuchFieldError: no "I" field "value" in class "Ljava/lang/Integer;" or its superclasses
> at com.esong.lib.EPM002Lib.ReadParams(Native Method)
> at com.sensorwa.config.configdemo.SquareSdkhelper.ReadParams(SquareSdkhelper.java:32)
> at crc643f46942d9dd1fff9.ButtonRenderer_ButtonClickListener.n_onClick(Native Method)
> at crc643f46942d9dd1fff9.ButtonRenderer_ButtonClickListener.onClick(ButtonRenderer_ButtonClickListener.java:30)
> at android.view.View.performClick(View.java:7201)
> at android.view.View.performClickInternal(View.java:7170)
> at android.view.View.access$3500(View.java:806)
> at android.view.View$PerformClick.run(View.java:27582)
> at android.os.Handler.handleCallback(Handler.java:883)
> at android.os.Handler.dispatchMessage(Handler.java:100)
> at android.os.Looper.loop(Looper.java:214)
> at android.app.ActivityThread.main(ActivityThread.java:7710)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### Steps to Reproduce
The error occurs when the above method is called as shown above. I am unsure as to what exactly is the issue here and what's causing it. However, the same aar library works well in a native Android application. Which makes me believe that the issue is in Xamarin Forms.

- Version with issue: 4.8.0.1534
- Last known good version: Android 9 and below
- Platform Target Frameworks: 
  - Android: 10
- Affected Devices: Android

### Reproduction Link
I cannot provide a sample to reproduce the problem as the error occurs when the connection to the IoT device is made.

Thank you very much.

**Comment by jonpryor** [comment]
> the problem in Xamarin only occurs when the Compile Target is > 10.

What do you mean by this, *exactly*? Setting `$(TargetFrameworkVersion)` to v11.0?

Or does it mean setting the `//uses-sdk/@android:targertSdkVersion` to 30 within `AndroidManifest.xml`?

Or something else?

More concerning is the stack trace:

```
java.lang.NoSuchFieldError: no "I" field "value" in class "Ljava/lang/Integer;" or its superclasses
at com.esong.lib.EPM002Lib.ReadParams(Native Method)
```

`com.esong.lib.EPM002Lib.ReadParams` isn't Xamarin.Android code; it's from your native library, and the error is probably thrown because the native library is doing the equivalent of:

```cpp
auto Integer_class = env->FindClass("java/lang/Integer");
auto Integer_value = env->GetFieldID(Integer_class, "value", "I");
// Integer_value is NULL
```

What I *think* is happening is that "when the Compile Target is > 10" means "`//uses-sdk/@android:targertSdkVersion` >= 29", which brings us to [Restrictions on non-SDK interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces): starting with Android 9, Google started preventing the use of Reflection against certain APIs.  From the [Expected behavior when restricted non-SDK interfaces are accessed](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#results-of-keeping-non-sdk) documentation:

> JNI via env->GetFieldID():
> `NULL` returned, `NoSuchFieldError` thrown

which is what you're seeing.

*In particular*, the [`hiddenapi-flags.csv` for Android 10](https://dl.google.com/developers/android/qt/non-sdk/hiddenapi-flags.csv) contains the line:

```
Ljava/lang/Integer;->value:I,greylist-max-p
```

which is *exactly* the member mentioned in the `java.lang.NoSuchFieldError`.

---

I think the actual solution is that you need to obtain an update to your ".so android library."

**Comment by singhal2** [comment]
Hello,

Thank you for the detailed explanation. I understand the problem much better now. 

I was able to obtain the native library code and as you mentioned the library is indeed doing the following.

```
	auto clazz = env->FindClass("java/lang/Integer");
	if (clazz == nullptr)
		return;

	auto id = env->GetFieldID(clazz, "value", "I");
	if (id == nullptr)
		return;

	env->SetIntField(integer, id, val);
```

However, I am unsure as to how do I change the code so as to not use reflection? Do you have some documentation or code example that you could provide, please?

Thanks for all the help

Abhi

**Comment by SonNXP** [comment]
Hello Singhal2
Do you have solution for this issue?

**Comment by singhal2** [comment]
I resolved it by finally changing the source code of the library I was using and recompiled it again. I am not changing the Integer value anymore.
