### ISSUE TITLE
Getting Error While Building

### ISSUE THREAD

**Issue by lilRufi** [xamarin/xamarin-android#5235]
I was trying to build an app. But I always get this error:

```
C:\Program Files\dotnet\sdk\3.1.403\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for MonoAndroid,Version=v10.0 
were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download 
.NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [C:\Users\raufs\osu\osu.Android\osu.Android.csproj]
```

**Comment by brendanzagaeski** [comment]
Thanks for the report! It looks like the build is attempting to use the .NET Core build system instead of the expected .NET Framework build system.

Did this error occur when building within Visual Studio or on the command line?

- If the error occurred when building within Visual Studio, then if you could collect and attach the diagnostic MSBuild output and the _.csproj_ file from your project, that would be perfect:

  1. Set **Tools > Options > Project and Solutions \[section\] > Build and Run \[subsection\] > MSBuild project build output verbosity** to **Diagnostic**.
  2. Run **Build > Clean Solution** and then use **Debug > Start Debugging** or **Debug > Start Without Debugging** to attempt to build and deploy your project to your Android device.
  3. After the build fails, open the **View > Output** window in Visual Studio and set **Show output from** to **Build**.
  4. Make sure the **Output** window is selected and then choose **File > Save Output As** to save the contents to a text file. Or copy and paste the build output into a text file.
  5. Attach back the text file in a new comment on this item. You can optionally zip the file before attaching it to make the upload size smaller. If the attachment contains private information, you can create a new Visual Studio Developer Community feedback item via **Help > Report a Problem** in Visual Studio and attach the build output or sample project there instead.
  6. If possible, if you could also attach the _.csproj_ file for the project, that would be excellent too. Feel free to remove any specific source file names, package names, or project names from the _.csproj_ before attaching it. The main thing I'm curious about is the `<TargetFrameworkVersion>` element and the other related configuration elements.

- If the error occurred when building on the command line, what was command line used to build the project?

   Note that `dotnet build` is not yet compatible with Xamarin.Android. (That compatibility will be upcoming in .NET 6. See the _What's Next for Xamarin and Xamarin.Forms_ section on the [_Introducing .NET Multi-platform App UI_](https://devblogs.microsoft.com/dotnet/introducing-net-multi-platform-app-ui/) blog post for a few more details.)

Thanks in advance!

**Comment by jonathanpeppers** [comment]
@lilRufi we haven't heard back in a while. Let us know if you can send more info, and we'll take a look. Thanks!
