### ISSUE TITLE
Java.Nio.ByteBuffer.Wrap() doesn't wrap?

### ISSUE THREAD

**Issue by v-hogood** [xamarin/xamarin-android#5377]
I can do this in Kotlin:
``` kotlin
val uprightImage = Bitmap.createBitmap(
    bitmapBuffer, 0, 0, bitmapBuffer.width, bitmapBuffer.height, matrix, true)
var uprightBytes = ByteArray(uprightImage.height * uprightImage.rowBytes)
var uprightBuffer = ByteBuffer.wrap(uprightBytes)
uprightImage.copyPixelsToBuffer(uprightBuffer)
```
But have to do this in Xamarin:
``` c#
var uprightImage = Bitmap.CreateBitmap(
    bitmapBuffer, 0, 0, bitmapBuffer.Width, bitmapBuffer.Height, matrix, true);
var uprightBytes = new byte[uprightImage.Height * uprightImage.RowBytes];
var uprightBuffer = ByteBuffer.Wrap(uprightBytes);
uprightImage.CopyPixelsToBuffer(uprightBuffer);
// TODO: Why is Get() necessary if uprightBytes is wrapped?
// https://forums.xamarin.com/discussion/5950/how-to-convert-from-bitmap-to-byte-without-bitmap-compress
uprightBuffer.Rewind();
uprightBuffer.Get(uprightBytes);
```

**Comment by jpobst** [comment]
I'm afraid I'm not familiar with this API and what it is trying to accomplish.

Can you give a little more context of what you're try to do, what you expect to happen, and what is happening instead?

**Comment by v-hogood** [comment]
I'm trying to copy pixels from Android.Bitmap to byte[] using Bitmap.CopyPixelsToBuffer().
More context here: https://forums.xamarin.com/discussion/5950/how-to-convert-from-bitmap-to-byte-without-bitmap-compress

CopyPixelsToBuffer() writes to ByteBuffer not byte[], so I ByteBuffer.Wrap() the byte[] and CopyPixelsToBuffer() to that.
I expect both ByteBuffer and the wrapped byte[] to contain the pixels. They do in Kotlin.
But in Xamarin I have to do an additional copy from ByteBuffer to byte[].  So it's as if byte[] is not actually wrapped by ByteBuffer.Wrap().

**Comment by jpobst** [comment]
I believe the issue is that `byte[]` is a primitive C# *value* type and not a `Java.Lang.Object` *reference* type.  

That is, when you do `ByteBuffer.Wrap (uprightBytes)`, we cannot give Java a reference to the actual C# `byte[]`, Java will instead make a *copy* of your bytes.

So at that point you have:
- `uprightBytes` - the C# `byte[]`
- `unnamed` - the Java copy of `uprightBytes` `byte[]`
- `uprightBuffer` - the Java `ByteBuffer`, which wraps the *Java* `byte[]`, not the *C#* `byte[]`

So any changes made in `uprightBuffer` are modifying the Java copy of the bytes, not the C# copy of the bytes.  Thus you have to do the `Get` in order to copy the `byte[]` from Java back to C#.

You could probably take out the first `C# -> Java` copy by allocating the `byte[]` directly in Java:
```
var uprightBuffer = ByteBuffer.Allocate (uprightImage.Height * uprightImage.RowBytes);
uprightImage.CopyPixelsToBuffer (uprightBuffer);

var uprightBytes = new byte [uprightImage.Height * uprightImage.RowBytes];

uprightBuffer.Rewind ();
uprightBuffer.Get (uprightBytes);
```

This way you only have the `Java -> C#` copying, which should be faster.

If you do not actually need the bytes in C#, the ideal scenario would be to never have the C# `byte[]` and keep it all in Java objects, but that may not be an option depending on what you are trying to do with the bytes.

It's a hard to explain technical detail of the way the Java <-> C# interop works with primitive types.  Hopefully this made a little bit of sense.  😄

**Comment by v-hogood** [comment]
Yes that's clear thanks!
It also explains why the reverse works--CopyPixelsFromBuffer(ByteBuffer.Wrap(C# byte[])) works, because as you say Java makes a copy of the C# bytes.
And finally Kotlin byte[] must be an actual Java byte[] for it to work?

**Comment by jpobst** [comment]
Yep, Kotlin is just a Java compiler with some different syntax.  It compiles down to Java bytecode and runs on the Java virtual machine, so from this aspect it *is* Java.

Xamarin is different in that it has both the Java VM and the Mono VM running, and has to pass objects back and forth between the 2 runtimes.

**Comment by v-hogood** [comment]
Instead of Copy() and Get() like you have above:
```c#
var uprightBuffer = ByteBuffer.Allocate (uprightImage.Height * uprightImage.RowBytes);
uprightImage.CopyPixelsToBuffer (uprightBuffer);

var uprightBytes = new byte [uprightImage.Height * uprightImage.RowBytes];

uprightBuffer.Rewind ();
uprightBuffer.Get (uprightBytes);
```
Would this be just one (unsafe) Copy()?  Or does Lock() do a Copy()?
```c#
var uprightPtr = uprightImage.LockPixels();

var uprightBytes = new byte [uprightImage.ByteCount];

Marshal.Copy(uprightPtr, uprightBytes, 0, uprightBytes.Length);

uprightImage.UnlockPixels();
```

**Comment by jpobst** [comment]
Looks like `Lock ()` simply gets an unmanaged pointer to memory, and then you're doing a single `Marshal.Copy` from the pointer.  So just one copy.

https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Android.Graphics/Bitmap.cs#L41

**Comment by v-hogood** [comment]
Great thanks!  Might as well close this I guess.
