### ISSUE TITLE
AndroidClientHandler doesn't store cookies on 302 (redirect)

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/xamarin-android#5587]
### Steps to Reproduce

1. Access any endpoint that replies with 302 and with one or more cookies

### Expected Behavior

Cookies from response should be stored. Note that AFAIK this is somehow a moot point when it comes to 302 and cookies handling, however major browsers store cookies and so does `HttpClientHandler`.

### Actual Behavior

Cookies are ignored. Cookies are stored with `HttpClientHandler` though, so that makes a breaking change switching between the two.

### Version Information

Latest

**Comment by dominik-weber** [comment]
might be related to #3954

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
