### ISSUE TITLE
Obsolete OpenTK and NUnit.Lite for .NET 6

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#5647]
.NET 6 will not include OpenTK or NUnit.Lite assemblies.  We should introduce build warnings today so users still using them will have some warning.

**Comment by jonpryor** [comment]
Completed with:

  * OpenTK deprecation: f909adb146c0ee87dafad2417e301a14afb79a33
  * Xamarin.Android.NUnitLite: 064babf6380b12decb8c94bf9c5d99f9429c5769

In Legacy apps, using either assembly will result in an XA4313 warning.

In .NET 6+ apps, using either assembly will result in a XA4313 error.

For .NET 6+ apps, please use the replacement NuGet packages:

  * OpenTK: https://www.nuget.org/packages/Xamarin.Legacy.OpenTK/
  * Xamarin.Android.NUnitLite: https://www.nuget.org/packages/Xamarin.Legacy.NUnitLite/0.0.1-alpha

**Comment by AndreyFromGomel** [comment]
@jonpryor Hi, tried to use Xamarin.Legacy.OpenTK package instead of obsolete OpenTK assembly, but it fails at runtime:
```08-19 12:47:50.318  8212  8244 E AndroidRuntime: FATAL EXCEPTION: GLThread 557
08-19 12:47:50.318  8212  8244 E AndroidRuntime: Process: Scene.Scene, PID: 8212
08-19 12:47:50.318  8212  8244 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.DllNotFoundException: libGLESv2.dll
08-19 12:47:50.318  8212  8244 E AndroidRuntime:    at OpenTK.Graphics.ES20.GL.GetInteger(GetPName pname, Int32* params) in OpenTK-1.0.dll:token 0x6001455+0x0
```
OpenTK-1.0.dll references several assemblies but OpenTK-1.0.dll is only assembly in NuGet package

<img width="435" alt="image" src="https://user-images.githubusercontent.com/46677631/130097866-3f4bf0a4-f6c1-43da-9af9-67a774195b43.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/46677631/130100033-41f11675-e436-4349-9de1-2c50fa17d91e.png">

Maybe I'm missing something? Is there any guide how to migrate app with OpenTK to .Net 6?
