### ISSUE TITLE
[Bug] CultureInfo object not loading native digits

### ISSUE THREAD

**Issue by raihaniqbal** [xamarin/xamarin-android#5844]
### Description
When instantiating a culture that has non-native digits for e.g. ar-SA, the NativeDigits array is always populated with English digits. I'm aware that the .NET Framework does not have built-in support to format DateTime strings with their native digits however the CultureInfo object should contain the native digits so we can manually replace the digits.

### Steps to Reproduce

1. Create a blank Shell application
2. In MainPage.xaml add a label
3. In the MainPage.xaml.cs set the text of the label to the current DateTime using the current culture:
`LocalizedDate.Text = $"{DateTime.Now.ToString("dddd٫ d MMM٫ yyyy", Thread.CurrentThread.CurrentUICulture)}";`

Sample application: https://github.com/raihaniqbal/MultilingualXFSample

### Expected Behavior
When instantiating the same culture in a Console/WinForms application, this is what the CultureInfo object looks like:
![Screenshot from .NET forms project](https://i.stack.imgur.com/RSw3v.png)

### Actual Behavior
This is what it looks like in my Xamarin project:
![Xamarin project culture info object](https://i.stack.imgur.com/oPw8B.png)

### Basic Information

- Test Device: Nexus 6P, Android 9.0
- Test Device culture: Arabic-Saudi Arabia
- Visual Studio IDE version: Community 2019, 16.9.4
- Xamarin.Forms version: 5.0.0.2012

**Comment by jpobst** [comment]
My guess is that this isn't supported in Mono, which is used by Xamarin.Android.  One way to determine that would be to download the desktop version of Mono and see if you see the same issue there:
https://www.mono-project.com/download/stable/

Unfortunately it isn't possible to transfer issues to other organizations, so you would need to copy/paste your issue to https://github.com/mono/mono/issues.

Another thing to consider trying is seeing what happens on Xamarin in .NET6 previews, as this is where most development is going on: https://github.com/dotnet/net6-mobile-samples

Since .NET6 Mono shares the same BCL libraries with .NET itself, it may already work there.  I know that team has been working recently on integrating the internationalization library ICU into the .NET6 version of Mono.  If it doesn't work on that version, it would probably be a good time to raise an issue there, as they are actively working on this area.

The issues link for the .NET6 version is https://github.com/dotnet/runtime/issues.

**Comment by raihaniqbal** [comment]
> 
> 
> My guess is that this isn't supported in Mono, which is used by Xamarin.Android. One way to determine that would be to download the desktop version of Mono and see if you see the same issue there:
> https://www.mono-project.com/download/stable/
> 
> Unfortunately it isn't possible to transfer issues to other organizations, so you would need to copy/paste your issue to https://github.com/mono/mono/issues.
> 
> Another thing to consider trying is seeing what happens on Xamarin in .NET6 previews, as this is where most development is going on: https://github.com/dotnet/net6-mobile-samples
> 
> Since .NET6 Mono shares the same BCL libraries with .NET itself, it may already work there. I know that team has been working recently on integrating the internationalization library ICU into the .NET6 version of Mono. If it doesn't work on that version, it would probably be a good time to raise an issue there, as they are actively working on this area.
> 
> The issues link for the .NET6 version is https://github.com/dotnet/runtime/issues.

You're right this could be a potential Mono bug.
![Screenshot_3](https://user-images.githubusercontent.com/5734698/115104907-1a9c4f00-9f9f-11eb-8ec2-09d8aef3564c.png)

I'll create a new issue over at Mono and see what they have to say.

**Comment by AmrAlSayed0** [comment]
This is actually something that was never supported in ANY version of .NET. Here is the code
```csharp
using System;
using System.Globalization;			
public class Program
{
	public static void Main()
	{
		CultureInfo cu = new CultureInfo("ar-SA");
		for (int i = 0; i < cu.NumberFormat.NativeDigits.Length; ++i)
		{
			Console.WriteLine( string.Format(cu,"This digit should be {0} but it is {1}.", cu.NumberFormat.NativeDigits[i],i) );
		}
	}
}
```
and in [.NET Fiddle](https://dotnetfiddle.net/NyI28z). This includes the latest .NET 6 Preview

**Comment by jpobst** [comment]
Issue "moved" to https://github.com/mono/mono/issues/21017.

Closing this copy.
