### ISSUE TITLE
[net6-android] A package with both `netstandard2.0` and `net6.0-android` should not favor `netstandard2.0`

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#5857]
### Steps to Reproduce

- Download the following solution: [net6androidnuget.zip](https://github.com/xamarin/xamarin-android/files/6347389/net6androidnuget.zip)
- In the `HelloAndroid` folder, run `dotnet build`

### Expected Behavior

The build passes as `Class1` is defined only in `net6.0-android30.0` in the `ClassLibrary15` package.

### Actual Behavior

The build fails where `Class1` is not defined, because `netstandard2.0` is favored over `net6.0-android30.0` even if the app is using `net6.0-android`.

### Version Information

`6.0.100-preview.3.21202.5`

### Additional info

This issue looks similar to https://github.com/xamarin/xamarin-android/issues/5819, but in the context of package references, not projects references.

**Comment by jonathanpeppers** [comment]
I think that this issue is fixed by: https://github.com/xamarin/xamarin-android/commit/b36df8fbeb15bcc2bcbe239d7ce49f8ec93ad263

I can build the attached project using a local build.

We can leave this issue open a bit to be sure, but I think the builds here would have the fix: https://github.com/dotnet/net6-mobile-samples/pull/139

**Comment by jeromelaban** [comment]
Fixed in pre4! Thanks a lot!
