### ISSUE TITLE
[One .NET] Missing AndroidSdkSupportedTargetPlatformVersion values

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#6107]
The file `Microsoft.Android.Sdk.SupportedPlatforms.targets` should include `<AndroidSdkSupportedTargetPlatformVersion>` versions for every API level we support (`21` - `30`).  However in Preview 6, it only includes `30`:

```xml
<Project>
  <PropertyGroup>
    <TargetPlatformSupported>true</TargetPlatformSupported>
    <TargetPlatformVersion Condition=" '$(TargetPlatformVersion)' == '' ">30.0</TargetPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <AndroidSdkSupportedTargetPlatformVersion Include="30.0" />
    <SdkSupportedTargetPlatformVersion Include="@(AndroidSdkSupportedTargetPlatformVersion)" />
  </ItemGroup>
</Project>
```

This means a user cannot currently use eg: `net6.0-android28.0` as a `<TargetFramework>`:

```
error NETSDK1140: 28.0 is not a valid TargetPlatformVersion for android. Valid versions include:
error NETSDK1140: 30.0
```

@jonathanpeppers says this is a regression and that it used to work.

**Comment by jonathanpeppers** [comment]
The issue appears to be that at the time this runs:

https://github.com/xamarin/xamarin-android/blob/6f9bc6b20927eb64800e4b42cf43f8e52b0b1a73/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.targets#L220-L224

Only a single `AndroidApiInfo.xml` exists:

![image](https://user-images.githubusercontent.com/840039/126506061-de600431-b7b1-4cc9-a969-c5e628046394.png)

**Comment by jpobst** [comment]
Note that there is currently some discussion that maybe we don't want `net6.0-android28.0` to exist after all that we should resolve before we fix this:

https://github.com/dotnet/sdk/issues/19075#issuecomment-883628444

**Comment by jonpryor** [comment]
I'm reminded of our `compileSdkVersion` project: https://github.com/xamarin/xamarin-android/projects/3

…which now needs to be updated for our .NET 6 world order.

Here's how I think things should play out:

 1. The `$(TargetFramework)` value, e.g. `net6.0-android31`, should be considered to be the *compile* SDK version, akin to Android's [`compileSdkVersion`](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.rpybud7i5).
 2. `$(TargetFramework)` *also* sets the [`//uses-sdk/@android:targetSdkVersion`](https://developer.android.com/guide/topics/manifest/uses-sdk-element#target).
 3. `$(SupportedOSPlatformVersion)` sets [`//uses-sdk/@android:minSdkVersion`](https://developer.android.com/guide/topics/manifest/uses-sdk-element#min).'

@jonathanpeppers will update our [default template](https://github.com/xamarin/xamarin-android/tree/27967cab142b3f06ecbe4557bddcde89eea98237/src/Microsoft.Android.Templates/android) to [remove `<uses-sdk/>`](https://github.com/xamarin/xamarin-android/blob/27967cab142b3f06ecbe4557bddcde89eea98237/src/Microsoft.Android.Templates/android/AndroidManifest.xml#L6) and update the build process so that the generated `AndroidManifest.xml` contains `<uses-sdk/>` values based on the target framework and `$(SupportedOSPlatformVersion)` values.

Question: Should we *add* an `$(AndroidMaxSupportedOSPlatformVersion)` property which sets [`//uses-sdk/@android:maxSdkVersion`](https://developer.android.com/guide/topics/manifest/uses-sdk-element#max)?

If the app's `AndroidManifest.xml` contains a `<uses-sdk/>` element, it is used as the canonical source of truth, and *overrides* values inferred from the TFM or `$(SupportedOSPlatformVersion)` values.

**Comment by jonathanpeppers** [comment]
[maxSdkVersion](https://developer.android.com/guide/topics/manifest/uses-sdk-element#max) says:

![image](https://user-images.githubusercontent.com/840039/126542939-9a5b7b4c-68e1-4043-8b15-c926ce15bf43.png)

So I don't think we need to create a way to set this value from an MSBuild property.

**Comment by jonpryor** [comment]
Copying from https://github.com/dotnet/sdk/issues/19075#issuecomment-884382104:

> @jpobst [wrote](https://github.com/dotnet/sdk/issues/19075#issuecomment-883628444):
> 
> > Our plan going forward was to always only ship one `Mono.Android.dll`, ie: when API-32 comes out we would only ship `Mono.Android.dll - v32` and we would no longer ship the API-31 version. Is that still feasible?  Or will we need to ship X copies of `Mono.Android.dll` where X is the number of TFM's we support?
> 
> We will need to ship *X+1* copies:
> 
>   * *X* "reference assembly" copies, one per TFM we support, and
>   * +1 *runtime* assembly, for the latest-and-greatest TFM we support.
> 
> For .NET 6 this November, *X* will be 1: we'll have 1 reference assembly and 1 runtime assembly for `net6.0-android31`.
> 
> Around April 2022, *X* will be *2*: 1 reference assembly for `net6.0-android31`, a *preview* reference assembly for `net6.0-android32` (or whatever we call it), and 1 runtime assembly which supports *both* `net6.0-android31` and `net6.0-android32`.
> 
> Come .NET 7 in November 2022, we'll "reset" *X* to 1, shipping 1 reference assembly and 1 runtime assembly for `net7.0-android32`.  Any apps continuing to target `net6.0-android31` will build against the (year old and not rebuilt?) reference assembly for `net6.0-android31` (built in 2021), and either use the `net6.0-android32` runtime assembly *or* use the `net7.0-android32` runtime assembly. (I don't know which will happen, but both seem plausible.  What is the "back-compat" story here?)

With that understanding in mind:

 1. In .NET 6+, `@(AndroidSdkSupportedTargetPlatformVersion)` should only have 1-2 values (current stable + optional preview).
 
     Meaning the current behavior described in this issue is correct and desirable.

 2. Apps which need to run on older Android versions need to set `$(SupportedOSPlatformVersion)`, which we will "map" to `//uses-sdk/@android:minSdkVersion`; see also:
    * https://github.com/xamarin/xamarin-android/issues/6107#issuecomment-884391615
    * https://github.com/xamarin/xamarin-android/pull/6111

Consequently, there are no "missing" `@(AndroidSdkSupportedTargetPlatformVersion)` values, and there is nothing to do here.
