### ISSUE TITLE
AAPT 2260 when building through github actions

### ISSUE THREAD

**Issue by taori** [xamarin/xamarin-android#6123]
### Steps to Reproduce

1. checkout repo for https://github.com/taori/PCRemote2/blob/master/.github/workflows/main.yml
2. try to build (exclude all steps past msbuild) through github actions

### Expected Behavior
APK should be produced

### Actual Behavior
Build failing

### Additional information
Building this on Azure Pipelines works, on github actions it will just drop a couple AAPT2260 errors

**Comment by dellis1972** [comment]
Try 

```
msbuild src/Amusoft.PCR.Mobile.Droid/Amusoft.PCR.Mobile.Droid.csproj /restore /t:PackageForAndroid /bl /p:Configuration=Release
```

**Comment by taori** [comment]
> 
> 
> Try
> 
> ```
> msbuild src/Amusoft.PCR.Mobile.Droid/Amusoft.PCR.Mobile.Droid.csproj /restore /t:PackageForAndroid /bl /p:Configuration=Release
> ```

..... it works. Why? should `/restore /t:PackageForAndroid` and `/restore /t:"Restore;PackageForAndroid"`

not result in a nuget restore on the project followed by a apk build?

**Comment by dellis1972** [comment]
It might be down to how MSbuild works. I suspect its because when you do `/t"TargetA;TargetB"` they both run in the same "context". where as the `/restore` is run before any targets are run. There is probably some state which is not setup when running the `Restore` target manually just before your main target. 

I'll close this as it fixed the issue, plus its not something we can fix for XA. Its built into msbuild.
