### ISSUE TITLE
Android app crashes only with Debugger attached and XAML Hot Reload enabled when certain page is opened

### ISSUE THREAD

**Issue by datvm** [xamarin/xamarin-android#6230]
### Steps to Reproduce

1. Run my project from Visual Studio with Debugging mode (the app doesn't crash if I run without Debugging - Ctrl + F5)
2. Interact with the app so it switch to a certain page (`FolderPage` in my case)

### Expected Behavior

The Content page should be shown.

### Actual Behavior

App crash **after** the page's `InitializeComponent()` method:

![image](https://user-images.githubusercontent.com/6388546/130758093-9c75cf49-4dc7-4f26-922f-c639bfdcd67d.png)

```
System.TypeLoadException: 'Could not load type of field 'System.Xml.Serialization.CodeExporter:codeNamespace' (2) due to: Could not resolve type with token 0100005e from typeref (expected class 'System.CodeDom.CodeNamespace' in assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') assembly:System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 type:System.CodeDom.CodeNamespace member:(null)'
```

### Version Information

[vs-info.txt](https://github.com/xamarin/xamarin-android/files/7045431/vs-info.txt)

### Log File

[logcat.txt](https://github.com/xamarin/xamarin-android/files/7045434/logcat.txt)

**Comment by datvm** [comment]
I realized the problem is gone if I disable XAML Hot Reload. Good thing I don't need it anyway but for those who need it, this should be fixed

![image](https://user-images.githubusercontent.com/6388546/130762110-c7c4218a-07d1-40a4-942b-5f1020b40cbd.png)

**Comment by grendello** [comment]
The app doesn't appear to crash (no error messages in the logcat, no segfault etc), the issue seems to be entirely on the client (VS or Hot Reload) side. @joj would you mind routing it to whomever is responsible for this area? Thanks!

**Comment by grendello** [comment]
nvm, just found out @lambdageek is The Man :)

**Comment by varyamereon** [comment]
Same issue using VS 2022 Preview 3.1. Trying to run the app in the emulator but it crashes with this. If I launch the app in the emulator without debugging it runs fine.

**Comment by lambdageek** [comment]
@grendello I'm the person for C# Hot Reload (aka EnC).  For XAML Hot Reload you want @drasticactions

**Comment by grendello** [comment]
@lambdageek thanks, I'm not versed in different Hot Reload species, reassigning :)

**Comment by drasticactions** [comment]
- With the issue with XAML Hot Reload, please file it on [VS Feedback](https://developercommunity.visualstudio.com/spaces/8/index.html). We're not going to track it on GitHub.
- There are two issues here. The first is a XAML Hot Reload bug that was introduced in the last preview: In order to make sure XAML Hot Reload works on all devices, we load additional dependencies from our extension. In this case, we're loading too many, including ones that conflict with Xamarin.Forms. This issue should be addressed with the next Visual Studio 2022 preview. 2019 should be unaffected.
- The second is a Xamarin.Forms bug, the code it's failing on is in the [XamlParser](https://github.com/xamarin/Xamarin.Forms/blob/caab66bcf9614aca0c0805d560a34e176d196e17/Xamarin.Forms.Xaml/XamlParser.cs#L354-L359), where it's loading all assemblies and checking for a Custom Attribute. While it is failing on assemblies loaded by XAML Hot Reload, you could have it fail yourself if you had dependencies loaded that it didn't like. This was fixed in MAUI, and should be backported to Xamarin.Forms.
