### ISSUE TITLE
[Profiling][net6] Sleeping thread produce repeated stack frames

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#6243]
### Steps to Reproduce

1. Create an application to profile (with `DOTNET_DiagnosticPorts` and others)
2. Create a ~100ms running operation on a button event
3. profile the application and press the button every second

### Expected Behavior

Periods between button presses show empty frames in speedscope when the application does nothing (presumably while the thread is sleeping)

### Actual Behavior

The last captured frame is repeated until the thread it resumed.

### Version Information

.NET 6 Preview 7

### Log File

Example trace:

[uno-app-trace.speedscope.json.zip](https://github.com/xamarin/xamarin-android/files/7069083/uno-app-trace.speedscope.json.zip)

You can observe large portions of traces that are repeated incorrectly while the thread is sleeping:

![image](https://user-images.githubusercontent.com/5839577/131180188-fb6aace3-5bba-4749-bcf7-2b3c2789ca70.png)

**Comment by lateralusX** [comment]
@jeromelaban can you supply the nettrace file as well?

**Comment by lateralusX** [comment]
I need to investigate if we can do any good to handle this scenario. We could of course emit sample event with 0 callstack depth, but that is then not inline with how CoreCLR does it and not sure how tools will react to this, so it needs to be investigated.

**Comment by lateralusX** [comment]
@jeromelaban Experimented a little with scenario above, and started to emit sample events, event if they have no callstack (happens when you have attached native thread currently not having any managed frames on callstack). It seems to do trick and speedscope will understand the previous callstack should not be prolonged, and I mark sample to be in unmanaged code and you will see that thread spends that time in unmanaged code, but without callstack. This is how it could look in perfview:

![image](https://user-images.githubusercontent.com/11529140/131520025-8978e1b9-664f-4741-a41f-5030f6ad9b3f.png)

In this case I have just tweaked our sample app to sleep for 10 seconds after main returns, but before terminating runtime (so sampling and EventPipe session is still running). You can see that all the sample events are put directly under thread as unmanaged code. This would be similar to have an embedding thread that will call into managed code, return back to native, do some native work, call into managed again etc. I believe it would make sense to represent it this way, but its more than what CoreCLR does (they drop samples with empty callstacks), but they don't have the embedding scenarios we have so probably less of a problem there (but I guess they could still get issue with delegates push to a native thread pool).

**Comment by josalem** [comment]
@lateralusX is on the right track I think.

It's worth noting that the speedscope output goes through the [SampleProfilerThreadTimeComputer](https://github.com/microsoft/perfview/blob/main/src/TraceEvent/Computers/SampleProfilerThreadTimeComputer.cs) which does a fair amount of guesswork. We could potentially solve some of this out-of-band by adjusting the logic there to try and identify these situations.

My hope is that future versions of the sample profiler in the runtime (coreclr and mono) will be capable of actually producing thread times without as much guesswork.

**Comment by jeromelaban** [comment]
@lateralusX let me know if there's any way I can help you test this out :)

**Comment by lateralusX** [comment]
I will do a PR where we can continue the discussion. The bottom line is that this scenario currently is undefined and generating the speedscope output based on guesswork in cases like this, visualized the behaviour. Question is, should the managed sample profiler only emit a sample per thread based on frequency (best effort depending on platform) if a thread has at least one managed frames on callstack or should it always emit a sample per thread based on frequency even if thread currently doesn't have any managed frames on callstack and mark that sample as unmanaged code. Currently we do the first alternative, leading to additional guesswork in speedscope output. If we do the second alternative, as visualized in perfview screenshot above, we could get more samples without callstack in unmanaged code (depending on embedding scenarios), so the ration between managed/unmanaged could be a little of, in the above example thread spend 99.8% of the total time in unmanaged code without any callstack, but in practice it was just sleeping somewhere in the embedding code.

**Comment by lateralusX** [comment]
@jeromelaban just merged fix into release/6.0 that will write out sample profile events when a attached thread is running native code without any managed frames, it should adjust the thread time for above use case. Possible for you to take it for a test drive? It mainly needs to be build from source at the moment (will be included in RC2).

**Comment by jeromelaban** [comment]
@lateralusX I'll definitely try this out! Thanks for the update.

**Comment by jpobst** [comment]
Sounds like this was fixed in https://github.com/dotnet/runtime/pull/58720.
