### ISSUE TITLE
[Profiling][Net6] Profiler max_frames depths is too low

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#6244]
### Steps to Reproduce

1. Create an application which uses deep stack traces with > 100 frames
2. Profile the application using `DOTNET_DiagnosticPorts` and others

### Expected Behavior

Stack frames are not capped at the last 100 captured frames

### Actual Behavior

Stack frames are unrealistically represented as follows, with patterns that show the actual stack frames depth:

![image](https://user-images.githubusercontent.com/5839577/131180332-3f9141a5-2e32-4df9-b93e-ac21b02268f0.png)

### Version Information
.NET 6 Preview 7

### Log File

I can provide one if needed

**Comment by lateralusX** [comment]
The 100 frame max depth is unfortunately a hard limit in EventPipe library shared with CoreCLR, so both runtimes have the same limitation. It is currently not configurable (unless you build from source) and increase the limit will consume more buffer memory, so in order to increase it we probably need to optimize some internals in the library.
Since it has been like that since netcore 3, I guess this request have been raised in the past, but the limit is still around, best is probably to raise an issue in dotnet/runtime to be brought to bigger diagnostics team attention.

The hard limit is located here in EventPipe library, https://github.com/dotnet/runtime/blob/cffaa78235ea93d5e3eeb56956579df503e11250/src/coreclr/vm/stackcontents.h#L15.

**Comment by jpobst** [comment]
Sounds like this is an issue in `dotnet/runtime`.  Unfortunately we cannot move issues across orgs.  If this is still an issue, please file it in https://github.com/dotnet/runtime.
