### ISSUE TITLE
Localization not working in Xamarin Android

### ISSUE THREAD

**Issue by BilKaz** [xamarin/xamarin-android#6346]
I had recently added localization to my Android app which is working properly when the package format is apk. However, after changing the package format to aab and releasing to Google Play store, the localization stops working. Directly deploying to a phone with release configuration and aab package format also results in localization not working after trying to change language.

The app behaves as if there are not resource folders with multi-language translations. To be clear I don't think the fault is in my code since it is working when package format is apk. I have followed the steps in https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/localization

Visual Studio Version 16.11.3

**Comment by dellis1972** [comment]
I think this is related to how `aab` files are installed. See https://developer.android.com/guide/app-bundle/configure-base#handling_language_changes. 

By default it will only install the current language what the user has selected. If that changes after installation, google is going to download the additional resources. This will not work when testing locally because there are no packages to download. 

I suspect you will need to change the setting before you deploy the aab to the device. So that it installs the correct language resources.

**Comment by jonathanpeppers** [comment]
If you don't want this behavior, you can disable the language dimension in your app bundles:

https://developer.android.com/studio/build/building-cmdline#bundleconfig

You can pass in a custom `BundleConfig.json` file by editing your `.csproj`:

```xml
<AndroidBundleConfigurationFile>BundleConfig.json</AndroidBundleConfigurationFile>
```

**Comment by BilKaz** [comment]
Got it. Thanks for your assistance. You can consider this closed
