### ISSUE TITLE
Found some native Libraries in Android Application are not secured in Xamarin.

### ISSUE THREAD

**Issue by devvaluelabs** [xamarin/xamarin-android#6359]
Hi Team,

During Testing, we found that some native libraries in Xamarin Android are not secured by applying some additional security mechanisms. We have found the issues as attached in the screenshot. Could you please let me know how can we proceed inorder to resolve this issue.

PFA screenshot for your understanding. Thanks in advance.

<img width="342" alt="Native libraries issue" src="https://user-images.githubusercontent.com/90273338/132456361-e4911987-4980-4b9f-bb66-f2070b80e1df.png">

**Comment by jsuarezruiz** [comment]
I moved this issue to the Android repository. Please, let me know if can help with anything.

**Comment by grendello** [comment]
Since this issue is nearly a year old, please rescan the libraries and note that `libxamarin-app.so` does **not** contain any executable code, thus no PIC nor stack canary markers will be found there.

Regarding the `libmono*` libraries, if they still don't use RERLO (they should now), this issue needs to be reported with https://github.com/mono/mono/
