### ISSUE TITLE
Xamarin Android JNI ERROR accessed deleted Global 0x606a

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#6456]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xamarin-Android-JNI-ERROR-accessed-delet/1422796)._

---
I am having a uncatchable error like below.
Where should I start to debug this kind of error?

I guess this is a memory leak issue or referencing deleted object by GC.
However, error message does not give me any clue why this is happening or where should I start to dig in...

You can check out [vimeo][1]

```
JNI ERROR (app bug): accessed deleted Global 0x606a
[java_vm_ext.cc] JNI DETECTED ERROR IN APPLICATION: use of deleted global reference 0x606a
[java_vm_ext.cc] &quot;Thread-28&quot; prio=10 tid=34 Runnable
[java_vm_ext.cc]   | group=&quot;main&quot; sCount=0 dsCount=0 flags=0 obj=0x13080000 self=0x7ac5a58c00
[java_vm_ext.cc]   | sysTid=8181 nice=-10 cgrp=default sched=0/0 handle=0x7aaabfd4f0
[java_vm_ext.cc]   | state=R schedstat=( 237903034 19270156 585 ) utm=20 stm=3 core=3 HZ=100
[java_vm_ext.cc]   | stack=0x7aaa9fe000-0x7aaaa00000 stackSize=2MB
[java_vm_ext.cc]   | held mutexes= &quot;mutator lock&quot;(shared held)
[java_vm_ext.cc]   native: #00 pc 00000000003cb654  /system/lib64/libart.so 

// ...

[libc] Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8181 (GLThread 25), pid 7983 (ngoslab.lithium)
```
Here is full [error log][2]

[1]: https://vimeo.com/548710444
  [2]: https://drive.google.com/file/d/1UCMnSU0z1zfG3nshuyOuPULX5Qp5wueG/view?usp=sharing

---
#### Feedback Bot on 5/12/2021, 11:56 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 5/18/2021, 01:36 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 9/5/2021, 08:21 PM: 

I detected that this issue hasn’t received a lot of activity, votes, or comments in the past 90 days. Based on this, the issues severity and affected area, it’s my experience that this issue is unlikely to get fixed. To improve the situation, consider following best practices for quality problem reports, and giving us more details on how this issue is impacting you.

---
### Original Solutions
(no solutions)

**Comment by jonpryor** [comment]
I really need to write up a proper HOWTO on this, but in the meantime…

 1. Enable [GREF logging](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/environment):

        adb shell setprop debug.mono.log gref

 2. Optional: start capturing `adb logcat`:

        adb logcat > log.txt

 3. Start your app

        msbuild /t:StartAndroidActivity App.csproj
        # -or-
        adb shell am start @PACKAGE_NAME@/@ACTIVITY_NAME@
        # -or- just use the GUI

 4. Once app crashes, grab GREF log:

        adb shell run-as @PACKAGE_NAME@ cat files/.__override__/grefs.txt > grefs.txt

    *Note:* This requires that the app be "debuggable", that within `AndroidManifest.xml` the `//application/@android:debuggable` attribute have the value `true`.

Once you have `grefs.txt` -- or `log.txt`, but `grefs.txt` is preferred -- then you want to open `grefs.txt` or `log.txt` into an editor that can handle large files, and search *backwards from the end* for the offending GREF value.  In this bug report, that would be the value `606a`, but that value could change on every run, so you'll want to review the collected `log.txt` for verification.

`grefs.txt` will contain the stack traces for when the GREF value was "touched": created, copied, destroyed; see also: https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#global-reference-messages

You could also try using `logcat-parse` to parse `grefs.txt`; see also: http://github.com/xamarin/Java.Interop/commit/1be4c6f66be789939d97e9355f363d35a8bddcb8

---

*In general*, the cause of a `JNI DETECTED ERROR IN APPLICATION` error is that a JNI Global Reference was used after it was deleted.  This can be deliberately caused by "misusing" things:

```csharp
var o = new Java.Lang.Object ();
var h = o.Handle;
o.Dispose();

// This should trigger a "JNI DETECTED ERROR IN APPLICATION" message
JNIEnv.NewGlobalRef (h);
```

but short of "deliberately bad" code, this *shouldn't* happen accidentally.  (Famous Last Words?)  (Though if `o` is shared between threads, and one thread calls `.Dispose()` while another thread is using that instance, you could accidentally recreate this scenario.)
