### ISSUE TITLE
TypeLoadException when registering TextChanged event on TextView

### ISSUE THREAD

**Issue by tipa** [xamarin/xamarin-android#7097]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

VS 2022 17.2.4, Xamarin.Android 12.3.3.3

### Description

```
var filterBox = FindViewById<TextInputEditText>(Resource.Id.filterBox);
filterBox.TextChanged += (s, e) =>{ }; // <- crashes when building in Release mode
```

This problem has been previously reported here: https://github.com/xamarin/xamarin-android/issues/3263

Example app: [AndroidApp1.zip](https://github.com/xamarin/xamarin-android/files/8907845/AndroidApp1.zip)

### Steps to Reproduce

- Create new Xamarin project, I also added the latest Google Material SDK, not sure if that is of relevance
- Add Textview in xml layout and register TextChanged event on it in code
- Build in Release mode, app crashes

### Did you find any workaround?

Yes, adding a LinkDescription.xml with the following content resolves the issue. This workaround was posted [here](https://github.com/xamarin/xamarin-android/issues/3263#issuecomment-515083294):

```
<?xml version="1.0" encoding="utf-8" ?>
<linker>
  <assembly fullname="Mono.Android">
    <type fullname="Android.Text.ITextWatcherInvoker" preserve="all" />
  </assembly>
</linker>
```

### Relevant log output

```
    android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load type '{0}' from assembly '{1}'., Android.Text.ITextWatcherInvoker, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
        at System.RuntimeTypeHandle.GetTypeByName(String , Boolean , Boolean , StackCrawlMark& , Boolean )
        at System.RuntimeType.GetType(String , Boolean , Boolean , StackCrawlMark& )
        at System.Type.GetType(String , Boolean )
        at Android.Runtime.AndroidTypeManager.RegisterNativeMembers(JniType , Type , ReadOnlySpan`1 )
    --- End of stack trace from previous location ---
        at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference , JniMethodInfo , JniArgumentValue* )
        at Android.Runtime.JNIEnv.FindClass(String )
        at Android.Runtime.JNIEnv.AllocObject(String )
        at Android.Runtime.JNIEnv.StartCreateInstance(String , String , JValue* )
        at Android.Runtime.JNIEnv.StartCreateInstance(String , String , JValue[] )
        at Android.Text.TextWatcherImplementor..ctor(Object , EventHandler`1 , EventHandler`1 , EventHandler`1 )
        at Android.Widget.TextView.add_TextChanged(EventHandler`1 )
        at AndroidApp1.MainActivity.OnCreate(Bundle savedInstanceState)
        at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr , IntPtr , IntPtr )
        at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V , IntPtr , IntPtr , IntPtr )
        at crc64a6e0c00971f6cd91.MainActivity.n_onCreate(Native Method)
        at crc64a6e0c00971f6cd91.MainActivity.onCreate(MainActivity.java:29)

```

**Comment by jonpryor** [comment]
https://discord.com/channels/732297728826277939/732297837953679412/1001166556342014042

> `PreserveInvoker()` is what causes the `*Invoker` type to be preserved.  Thus the question should instead by, why isn't `ITextWatcher` passed into `PreserveInvoker()`?

https://discord.com/channels/732297728826277939/732297837953679412/1001167714141863976

> that property is hand-bound: https://github.com/xamarin/xamarin-android/blob/938b2cbe2f64a0ec0e5984cb59321e05d9db7de7/src/Mono.Android/Android.Widget/TextView.cs#L54-L69 
> maybe we're doing something "wrong"?

> The repro is a `Google.Android.Material.TextField.TextInputEditText` 
> regular `EditText` we have a test that appears to be passing

> related? the type that needs to be preserved is an `*Implementor,` not an `*Invoker.`
> thus, `PreserveInvoker()` won't be called
> `PreserveImplementor()` should be called.

https://discord.com/channels/732297728826277939/732297837953679412/1001207416173633676

> So if I debug this code path:
https://github.com/xamarin/xamarin-android/blob/b4998c88f9b2b50ac047153e13b516a0f3181028/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs#L277-L285
> The type Android.Text.TextWatcherImplementor, has no methods that end with "Handler"
> Even if I look at the "un-linked" assembly
> It seems like we need something that would keep the ITextWatcher interface on this type

https://discord.com/channels/732297728826277939/732297837953679412/1001208651253547038

> would you believe it's always done that? https://github.com/xamarin/monodroid/commit/a619cbea33e1b7cd8ffd0352bb37ac551d324f67
> i have no idea why it does that.

https://discord.com/channels/732297728826277939/732297837953679412/1001209997226692619

> So the actual issue is we lose this interface:
> ![image](https://user-images.githubusercontent.com/155958/181081625-f46eb2da-e543-4a33-b0e8-314302e9fd79.png)
> `ITextWatcher` is gone

**Comment by jonpryor** [comment]
@jonathanpeppers: It is *very* odd that we are losing the interface.

Guess/conjecture: we need to tell the linker that when a JLO subclass is preserved -- as is the case with `TextWatcherImplementor` here -- then we *also* need to preserve *all* interfaces that the type implements?

**Comment by jonathanpeppers** [comment]
Did you see #7204? It is preserving all `IFoo` interfaces on all `FooImplementor` types.

Is that the route we should go?

**Comment by jonpryor** [comment]
@jonathanpeppers: no, i did not see #7204 until you mentioned it. :-)

That said… in addition to the [confusion](https://github.com/xamarin/xamarin-android/pull/7204#issuecomment-1195852337) expressed on #7204, this whole "the linker can remove interfaces that your type implements" behavior is *concerning* to me.

Imagine that you have linking enabled for your *entire* app, meaning *non-Xamarin code* is linked.  When I write a class such as:

```csharp
class SillyExample : Java.Lang.Object, ISomeBoundJavaInterface {
    // …
}

// …

BoundClass.BoundMethod (new SillyExample());
```

How do I *know* that `SillyExample` will actually implement `ISomeBoundJavaInterface`?

Apparently the only way to ensure that `SillyExample` implements `ISomeBoundJavaInterface` is for `ISomeBoundJavaInterface` to be preserved, so if you have a bound + preserved method such as `BoundClass.BoundMethod()` which has a parameter or return type of `ISomeBoundJavaInterface`, you're golden.

But what if you don't?  What if because of Metadata or whatever the parameter type for `BoundClass.BoundMethod()` is `Java.Lang.Object`, and the *only* mention of `ISomeBoundJavaInterface` is via `SillyExample`?  What then?

My *guess* is that the linker will remove *all* references to `ISomeBoundJavaInterface`, `SillyExample` will no longer implement the type, and the resulting Java Callable Wrapper will likewise not implement `SomeBoundJavaInterface`.

Am I overthinking this?  Underthinking it?  (In dire need of a vacation? :thinking:)

I'm looking at `ProcessType()`, and while it does have an "out" for non-framework types, it only preserves their *methods*, not their implemented interfaces: https://github.com/xamarin/xamarin-android/blob/d26e69a0ba8cc192172e200be9cb4fb1bcf7a254/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/MarkJavaObjects.cs#L52-L55
