### ISSUE TITLE
Apps built with `-c Release -p:PublishTrimmed=false` crash at runtime, AOT + No trimmer

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#7178]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

.NET 6

### Description

App crashes with MVID mismatches when loading AOT images:
```
07-18 11:39:53.613 20269 20269 D Mono    : AOT: module Microsoft.Maui.dll.so is unusable (GUID of dependent assembly Xamarin.AndroidX.AppCompat doesn't match (expected '1FC81757-8A70-4D56-93E6-8A635E2C23DE', got 'FD3821D1-CBF4-4956-B930-EA2A5379E18D')).
```

### Steps to Reproduce

1. `dotnet new android` or `dotnet new maui`
2. `dotnet build -c Release -p:PublishTrimmed=false -t:Run`

### Did you find any workaround?

Don't pass `PublishTrimmed=false`

**Comment by Cywizz** [comment]
Just a note, I have a similar issue as described above with my .Net MAUI app...same error so I assume it is related.
I do a build on a pull request via github actions with the following command:

`dotnet build WMS/WMS.csproj -c Release -f net6.0-android /p:AndroidSigningKeyStore=wms.ks /p:AndroidSigningKeyAlias=wms.al /p:AndroidSigningKeyPass="{{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" --no-restore`

I do not use PublishTrimmed=false and I still see the issue.
My workaround was to add the following line to the .csproj:

`<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">`
     `<AndroidLinkMode>None</AndroidLinkMode>`
     `<RunAOTCompilation>false</RunAOTCompilation>`
    `<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>`
`</PropertyGroup>`

The **RunAOTCompilation** and **AndroidEnableProfiledAot** fixed the above issue.
The **AndroidLinkMode** was required to load all my EF Postgre SQL dependencies, because for some reason it trims them out...will probably figure out how to fix it per assembly, because my .apk is double in size now.

**Comment by jonathanpeppers** [comment]
`AndroidLinkMode=None` is the same as setting `PublishTrimmed=false`.

**Comment by soundaranbu** [comment]
> Just a note, I have a similar issue as described above with my .Net MAUI app...same error so I assume it is related. I do a build on a pull request via github actions with the following command:
> 
> `dotnet build WMS/WMS.csproj -c Release -f net6.0-android /p:AndroidSigningKeyStore=wms.ks /p:AndroidSigningKeyAlias=wms.al /p:AndroidSigningKeyPass="{{ secrets.KEYSTORE_PASSWORD }}" /p:AndroidSigningStorePass="${{ secrets.KEYSTORE_PASSWORD }}" --no-restore`
> 
> I do not use PublishTrimmed=false and I still see the issue. My workaround was to add the following line to the .csproj:
> 
> `<PropertyGroup Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">` `<AndroidLinkMode>None</AndroidLinkMode>` `<RunAOTCompilation>false</RunAOTCompilation>` `<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>` `</PropertyGroup>`
> 
> The **RunAOTCompilation** and **AndroidEnableProfiledAot** fixed the above issue. The **AndroidLinkMode** was required to load all my EF Postgre SQL dependencies, because for some reason it trims them out...will probably figure out how to fix it per assembly, because my .apk is double in size now.

I ran into the same issue. This workaround worked for me!

**Comment by jonathanpeppers** [comment]
For .NET 7, we should emit a warning and toggle a set of MSBuild properties that "work".

I moved the milestone back to 7 for this.

**Comment by julianadormon** [comment]
Sorry for asking this here, but this is the closest post I could find to what I am facing.

.net Maui Deploy to Android in Release mode produces "module is unusable (GUID of dependent assembly Microsoft.EntityFrameworkCore.Sqlite doesn't match"

I am building a .net Maui Android app. I have no problem deploying my app to an Android emulator or real device when in Debug mode. However if I deploy in Release mode, the app crashes on load. The android device log, shows the following error,

Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:3678, condition `is_ok (error)' not met, function:decode_patch, module is unusable (GUID of dependent assembly Microsoft.EntityFrameworkCore.Sqlite doesn't match (expected 'DE191E13-E625-494C-862B-66ABDC9BC3C8', got '0C0A2DB6-8411-4D35-912B-740A5B7BC5CE')).

I had no problem running this in Release mode earlier in the development cycle. I have updated both Visual Studio and Microsoft.EntityFrameworkCore.Sqlite probably several times since I last tested in Release mode.

My project does reference a DbClassLibrary. Both projects reference the same version of Microsoft.EntityFrameworkCore.Sqlite, 6.0.9 which is the latest at the time of writing.

I have tried deleting the App from the Android device, cleaned my solution and re-published.

I have also successfully published the apk using dotnet build -c Release -f net6.0-android and installed it on the device but it produces the same error.

My Visual Studio specs are as follows:

Visual Studio Community 2022 for Mac Preview Version 17.4 Preview (17.4 build 1583) Installation UUID: 10e52aa0-ff80-4b74-8350-1c794fdcca3c

Runtime .NET 6.0.5 (64-bit) Architecture: Arm64

Roslyn (Language Service) 4.4.0-2.22419.1+ae5663806be933515723b2d5a85faf5d378f460d

NuGet Version: 6.3.0.128

.NET SDK (Arm64) SDK: /usr/local/share/dotnet/sdk/6.0.401/Sdks SDK Versions: 6.0.401 6.0.400 6.0.400-preview.22330.6 MSBuild SDKs: /Applications/Visual Studio (Preview).app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET SDK (x64) SDK Versions: 5.0.408 3.1.423 3.1.422 3.1.421

.NET Runtime (Arm64) Runtime: /usr/local/share/dotnet/dotnet Runtime Versions: 6.0.9 6.0.8 6.0.6

.NET Runtime (x64) Runtime: /usr/local/share/dotnet/x64/dotnet Runtime Versions: 5.0.17 3.1.29 3.1.28 3.1.27

Xamarin.Profiler Version: 1.8.0.19 Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater Version: 11 ...

**Comment by jonathanpeppers** [comment]
@julianadormon what you are describing here sounds like something is setting either `PublishTrimmed=false` or `AndroidLinkMode=None` for your `Release` build using AOT. The resulting app would also be fairly large if trimming is turned off.

Can you file a new issue with a `.binlog` (https://msbuildlog.com), if that doesn't seem to be the case?

**Comment by julianadormon** [comment]
@jonathanpeppers Thank you, but I don't believe that is the case as the apk package is much smaller than my debug build and I have not changed any publish settings, just using the Maui defaults. I will open an issue. Thanks again!
