### ISSUE TITLE
.Net Maui Microsoft.Data.SqlClient, works on Windows NOT Android(Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/xamarin-android#7277]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-Maui-MicrosoftDataSqlClient-work/10114095)._

---
[severity:I'm unable to use this version]
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.3.0 Preview 6.0
.Net Maui Standard Template

```
	string connStr = @$"Server=MyserverIP\SQLEXPRESS;Database=MyDB;Integrated Security=false[Redacted]Encrypt=false";
        using var db = new SqlConnection(connStr);
	try
	{
            db.Open();
        }
	catch (Exception ex)
	{
	   Console.WriteLine(ex.Message);
           // ex = Value cannot be null. (Parameter 'source)
	}
```
Far better example/Test:
[https://github.com/janseris/MAUI_SQLServer_Test]()

Using MAUI_SQLServer_Test, choose custom string and use similar to mine above.
Windows: All pass
Android: All **fail** with Value cannot be null. (Parameter 'source)

		

---
#### Feedback Bot on 8/9/2022, 01:15 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jonpryor** [comment]
Instead of printing `Exception.Message`, please use `Excecption.ToString()`.  That would help in pinpointing *where* the null argument exception is coming from.

Additionally, it looks like Microsoft.Data.SqlClient may not fully support Android yet:

  * https://github.com/dotnet/SqlClient/issues/1656
  * https://github.com/dotnet/SqlClient/issues/1662

This is thus presumably a bug in the Microsoft.Data.SqlClient package and *not* a package in .NET SDK for Android.

**Comment by janseris** [comment]
@jonpryor are you sure this is SqlClient problem and not MAUI/Xamarin problem? MAUI has this type of SSL/TLS issues in various technologies.
