### ISSUE TITLE
[net6] ILLink is run 4 times when building an app with AOT

### ISSUE THREAD

**Issue by jeromelaban** [xamarin/xamarin-android#7300]
### Android application type

Android for .NET (net6.0-android, etc.)

### Affected platform version

17.4 Preview 1

### Description

When building deploying an app using AOT, the ILLink task is run once per target CPU architecture, causing (seemingly) unnecessary CPU usage.

### Steps to Reproduce

Build a net6 app, observe the presence of the ILLink task in MSBuild binlogs.

### Did you find any workaround?

None

**Comment by jonathanpeppers** [comment]
This is done because the BCL from the Mono runtime packs is actually different per architecture. The `android-arm64` packs are literally different from the `android-x86` ones.

We have a `<ProcessAssemblies/>` MSBuild task that takes the 4 sets of linker output, compares MVIDs, and drops any duplicate. Normally you end up with one or two different assemblies like `System.Private.CoreLib.dll` that is placed in a sub-folder in the app.

I think the only solution to this would be something in dotnet/runtime?

**Comment by jeromelaban** [comment]
Got it, that makes sense to have it run the linker multiple times then. Out of curiosity, what's different in the assemblies per architecture?

**Comment by jonathanpeppers** [comment]
Apparently .NET Core had hardware instrinsics that are different for 32-bit, 64-bit, arm -- and these weren't in Mono.

Until we added mobile to .NET 6, there really wasn't a concept of multiple RIDs inside 1 application either.

I think there is not much we can do here, currently. We could consider filing something in dotnet/runtime, but it might be a big rework for them to make this happen?
