### ISSUE TITLE
Static functions in Android Library (Kotlin) not accessible from Xamrin

### ISSUE THREAD

**Issue by kuldeepgupta7** [xamarin/xamarin-android#7450]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS2022

### Description

I was trying to bind a android library (kotlin) in Xamarin. Android library bind and project build successfully but I was not able to access all functions of android library in Xamarin some static function is not accessible from Xamarin, I haven't got any proper solution for this issue please provide me a proper way to access static function in Xamarin.

### Steps to Reproduce

1. Create new project in Android App (Xamarin)
2. Setup project.
3. Add .dll file in references folder.
4. Add all required dependencies in references folder.
5. Build solution.

**Comment by jpobst** [comment]
In general, if the binding process does not have enough information to properly bind a type or method it will omit the type/method rather than generate C# that doesn't compile.  When it does this, it writes debug messages to the build log to let you know what it has skipped and why.

However, these messages only show up on a Diagnostic build log, so you will need to enable that and rebuild:
https://github.com/xamarin/java.interop/wiki/Helpful-Tools#diagnostic-msbuild-output

Additional information for resolving the issues listed in the build log can be found here:
https://github.com/xamarin/java.interop/wiki/Missing-Types-or-Members

**Comment by jpobst** [comment]
`kotlin.jvm.functions.Function1` is found in the Kotlin Stdlib. Have you added a reference to the `Xamarin.Kotlin.StdLib` NuGet package?
