### ISSUE TITLE
FileVersionInfo.GetVersionInfo() for Xamarin.Android

### ISSUE THREAD

**Issue by bonniemathew** [xamarin/xamarin-android#7519]
Hi All, 

I have seen that the `FileVersionInfo.GetVersionInfo()` is not working on Xamarin.Android(). 
Its working fine in debug mode but throws 'FileNotFoundException' in the Release mode. 

I have also seen that if you set the     `<EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>` in the .csproj it will work. But this cannot be done in the 'Release' mode. The same API is working fine on Xamarin.iOS. Is there any alternative API for that? Or is there anyway to set the `<EmbedAssembliesIntoApk>` in Release mode?

**Comment by grendello** [comment]
@bonniemathew could you attach a simple repro app which demonstrates what exactly isn't working? If, as I assume, you're trying to get version info of a .dll file, it won't work. The reason is that the assemblies are always found in the apk - they are never unpacked to the filesystem by Android. Additionally, by default we not only compress the managed assemblies with LZ4, we also put them in a binary "blob" which makes them even less visible (but faster to open).

If you want to disable both the compression and the packing into blob, you can set the following properties in your csproj:

```xml
<PropertyGroup>
  <AndroidUseAssemblyStore>False</AndroidUseAssemblyStore>
  <AndroidEnableAssemblyCompression>False</AndroidEnableAssemblyCompression>
</PropertyGroup>
```

Managed assemblies will then be found in the .apk, in the `assemblies/` directory.  To open them, however, you would have to first open the apk, then use some ZIP library to unpack them to a temporary location in the filesystem and only then you'd be able to use .NET file I/O APIs to read the file information.
