### ISSUE TITLE
Bind = "False" doesn't work

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#7954]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

VS Mac Version 17.5.4 (build 8)

### Description

Sample code I will update in "Reproduce" section.

Refered to this docs: https://github.com/xamarin/xamarin-android/blob/b4438e7ce8cc9ffdaa65b7d318b0b47b1f3cd9bb/Documentation/guides/OneDotNetEmbeddedResources.md
```
<!-- Just include, do not bind -->
<AndroidLibrary Include="bar.aar" Bind="false" />
<AndroidLibrary Include="baz.jar" Bind="false" />
```

So I edit the setting in csproj file:
```
  <ItemGroup>
    <AndroidLibrary Include="./baselibrary-debug.aar" Bind="false"/>
  </ItemGroup>
```

### Steps to Reproduce

[ToolLibraryBinding.zip](https://github.com/xamarin/xamarin-android/files/11212824/ToolLibraryBinding.zip)
1.VS for mac open the solution.
2.Rebuild the project.
3.View the class by vs class view or using ILSpy to inspect the dll.

I can see the baselibrary still be binded as c# contents.

build log here:
[log.txt](https://github.com/xamarin/xamarin-android/files/11212847/log.txt)

### Did you find any workaround?

no

**Comment by jpobst** [comment]
I believe this was resolved in Discord, transcript beginning here:
https://discord.com/channels/732297728826277939/732297837953679412/1095729657246142685

TL:DR

The `.jar` was getting added twice, once from:
```xml
<AndroidLibrary Include="./baselibrary-debug.aar" Bind="false"/>
```

And once from the default file inclusions:

https://github.com/xamarin/xamarin-android/blob/b4438e7ce8cc9ffdaa65b7d318b0b47b1f3cd9bb/Documentation/guides/OneDotNet.md#default-file-inclusion

Changing the `Include` to `Update` causes the default import to be modified to `Bind="false"` instead of creating a second entry.
