### ISSUE TITLE
Unable to include the aar libs into the dll after done build for binding project

### ISSUE THREAD

**Issue by jingliancui** [xamarin/xamarin-android#7959]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

17.5.4 (build 8)

### Description

As the new binding template for iOS, it's able to using this confit to include the .framework or .a file into the dll:
```
<IsBindingProject>true</IsBindingProject>
<NoBindingEmbedding>False</NoBindingEmbedding>
```
But android binding will not do this even I add these config in csproj file.
As you can see, the bin folder contain the aar file and the dll file after build the binding project.

### Steps to Reproduce

[ToolLibraryBinding.zip](https://github.com/xamarin/xamarin-android/files/11233084/ToolLibraryBinding.zip)
1.using vs mac to open the .sln file.
2.build the project.
3.observe the bin folder, it contain the dll and aar file.

### Did you find any workaround?

no

**Comment by jpobst** [comment]
In .NET Android, there is no longer a way to embed the `.aar`/`.jar` inside the `.dll`.  This pattern causes excessive build times because each `.dll` must be inspected and the embedded file must be extracted for each build.

https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/OneDotNetEmbeddedResources.md
