### ISSUE TITLE
TimeZoneNotFoundException in DateTime.Now

### ISSUE THREAD

**Issue by holecekp** [xamarin/xamarin-android#8090]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.6.2, Xamarin.Forms 5.0.0.2578

### Description

Calling DateTime.Now can crash a Xamarin.Forms app on Android because of a TimeZoneNotFoundException. I am using the latest version of Xamarin.Forms. DateTime.Now works without problems most of the time. However I have received the following crash report in AppCenter:
```
System.TimeZoneNotFoundException: Exception of type 'System.TimeZoneNotFoundException' was thrown.
  at System.TimeZoneInfo.get_Local () [0x00012] in <b07e53661a73444fbe9f6949f40d1e58>:0
  at System.TimeZoneInfo.GetDateTimeNowUtcOffsetFromUtc (System.DateTime time, System.Boolean& isAmbiguousLocalDst) [0x00000] in <b07e53661a73444fbe9f6949f40d1e58>:0
  at System.DateTime.get_Now () [0x00008] in <b07e53661a73444fbe9f6949f40d1e58>:0
```

This crash is very similar to an older issue #5080, which has already been fixed (the same crash but in DateTimeOffset.Now  instead of DateTime.Now).

### Steps to Reproduce

I am not able to reproduce it because there are no problems with DateTime.Now in my zone. However, it can crash in other parts of the world. In the particular AppCenter report, the crash is reported for an Android 8 device in Mexico.

### Did you find any workaround?

No

**Comment by grendello** [comment]
Hi @holecekp, do you have any information on what is the actual timezone set on the device?

**Comment by holecekp** [comment]
Unfortunately, I do not have contact to the owner of the device. I have just received an anonymous crash report from AppCenter.Crashes. The only clue is that AppCenter shows Mexico as the country in the report. The raw report also shows the app start and app crash date and time but I do not know if it is helpful:
Start Date: 2023-05-31T01:44:35.649Z
Date: 2023-05-31T01:45:03.27Z

**Comment by grendello** [comment]
@holecekp thanks, unfortunately neither the country nor the dates help us. Mexico uses a pretty standard set of time zones and one of the reasons one of them would not be found, is a problem with the tzdata database on device. This is not something we can fix, alas.  It's also possible that the name of timezone was incorrectly formatted (hence my earlier question), but we don't have that either :(. The dates you gave are in UTC (as evidenced by the `Z` suffix, which in ISO 8601 designates UTC) so that gives us no clue either :(

I'm afraid we can't do much about the issue without more information, there's no starting point.  I'm going to close the report, but please reopen it should there be more info available.

**Comment by holecekp** [comment]
Thank you for investigating this issue. I will solve it for now by enclosing DateTime.Now calls in try..catch block so that any further problems with DateTime.Now would not cause a crash.
