### ISSUE TITLE
API-34: Support targeting JDK 17

### ISSUE THREAD

**Issue by MihaMarkic** [xamarin/xamarin-android#8304]
### Android application type

Classic Xamarin.Android (MonoAndroid12.0, etc.)

### Affected platform version

VS 2022 17.x

### Description

I'm trying to create a binding library for an .aar library that targets JDK 17
```json
kotlin {
      jvmToolchain(17)
  }
```
I'm getting this error: _javac.exe error JAVAC0000:     class file has wrong version 61.0, should be 55.0_

And there seems no way to use (Open)JDK 17 as VS build really really wants to use 11 even if 17 is installed as well.
Is there any way to use JDK 17? Hopefully official support is planned soon.

### Steps to Reproduce

1. Create a binding library for [emarsys:core-api:3.6.0](https://github.com/emartech/android-emarsys-sdk/tree/master/core-api) but I guess any similar library targeting JDK 17 will do.
2. When compiling client for library created in step above, javac.exe compiler will produce errors mentioned in description.

### Did you find any workaround?

Use an older version of the library that targets JDK 11.

**Comment by jpobst** [comment]
Thanks for bringing this to our attention.  The first version of Android that supports JDK 17 will be Android 14, which is still in beta.  

- [Android supported Java versions](https://developer.android.com/build/jdks#compileSdk)

We made a list of the things we need to do in order to get support for JDK 17 into .NET 8 / API-34 this morning.

Note that if you are still using Classic Xamarin.Android, API-34 will not be supported there, so it likely will not be receiving JDK 17 support.

- [Classic support policy](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin)

**Comment by jpobst** [comment]
We're going to use this issue as our reference for adding JDK 17 support for API-34.  😁

**Comment by jpobst** [comment]
This should be completed for the upcoming releases:
- Classic 13.2.2
- .NET 7 7.0.402 (?)
- .NET 8 RC2
