### ISSUE TITLE
Document some examples in binding project template

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/xamarin-android#8411]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

.NET 8

### Description

I'm thinking the `.csproj` should give a couple examples of `Bind="false"`, etc. in comments. Similar to how we have a few comments in `Metadata.xml`.

We should also have an aka.ms link to a documentation page about bindings.

This came up here: https://github.com/dotnet/maui/issues/17826#issuecomment-1748130014

### Steps to Reproduce

1. `dotnet new androidbinding-lib`
2. Become confused by binding projects

**Comment by ymebrugts** [comment]
I agree that a Bind="false" example should be added because it's not clear based on the documentation that the equivalent of "EmbeddedReferenceJar" for MAUI is AndroidLibrary with Bind="false". 

A table should be added on the migration page that shows the equivalent Build Action for MAUI binding:
https://learn.microsoft.com/en-us/dotnet/maui/migration/android-binding-projects

**Comment by jonathanpeppers** [comment]
Thanks, I updated that docs page here: https://github.com/dotnet/docs-maui/pull/1916

**Comment by jonathanpeppers** [comment]
Can you file an issue with a `.binlog`? https://aka.ms/binlog

It reminds me of an issue in .NET 7 that should be fixed in .NET 8.
