### ISSUE TITLE
Audit MSBuild error messages for VS and XA specific instructions

### ISSUE THREAD

**Issue by jpobst** [xamarin/xamarin-android#8413]
As we transition from `Xamarin.Android` to .NET and add additional support for tooling like `dotnet` CLI and VSCode we should audit our warning/error messages to ensure they aren't VS-exclusive.

In many cases we can probably make the message generic enough.  In other cases where there is a benefit to giving tooling-specific instructions we can provide an `aka.ms` link to more detailed instructions.

Some examples that should be fixed:

* https://github.com/xamarin/xamarin-android/blob/0945978452a357f0dd8eb89d9c1bca523bbe0e5c/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx#L864

**Comment by BretJohnson** [comment]
See this Twitter/X thread for an example of a user who could really benefit from a better message here: https://twitter.com/seansparkman/status/1713998489745543536?s=20

Here's the scenario:
- User (Sean) installs .NET8 MAUI on his Mac, trying to use it
- He builds from the CLI
- He sees the error `Could not find android.jar for API level 34. This means the Android SDK platform for API level 34 is not installed. Either install it in the Android SDK Manager (Tools > Open Android SDK Manager...), or change the Xamarin.Android project to target an API version that is installed.`.
- He's confused about what to do. He currently has VS Mac installed, but knows it's going away. VS Code doesn't have an Android SDK Manager. He seems to think that installing the right Android workload from the CLI will fix this somehow (a reasonable assumption, though a wrong one here). He struggles for a good while.
- The fact that the branding is wrong (e.g. saying Xamarin.Android project instead of .NET Android project) makes it worse.

Probably our updated error text, at least when running on Mac, should include a link to the doc that talks about how to install Android dependencies, with VS Code. This doc: [Install Visual Studio 2022 to develop cross-platform apps using .NET MAUI - .NET MAUI | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/maui/get-started/installation?tabs=visual-studio-code)

**Comment by jpobst** [comment]
This seems to have been covered by https://github.com/xamarin/xamarin-android/pull/8494 and other work in this area.
