### ISSUE TITLE
Need AndroidHttpClientHandlerType Support in MAUI .NET Android

### ISSUE THREAD

**Issue by TonyLugg** [xamarin/xamarin-android#8470]
### Android application type

.NET Android (net7.0-android, etc.)

### Affected platform version

Android SDK 33

### Description

One of my apps sends requests with custom headers to a customer API, and the requests are denied because of additional headers that are causing issues.  I got around this issue with Xamarin Android by configuring HttpClient implementation as Default, which sets the csproj property, AndroidHttpClientHandlerType, to empty string.  Doing this eliminated the additional headers Android seems to add.  MAUI .NET Android must also use Android HttpClient implementation because the additional headers are added.  My customer is unable to change their API middleware.   I tried adding the AndroidHttpClientHandlerType property to the csproj file in MAUI but it had no effect.

Attached are two solutions, a working Xamarin Forms version and the non-working MAUI version.
[HttpHeaderTestMaui.zip](https://github.com/xamarin/xamarin-android/files/13192145/HttpHeaderTestMaui.zip)
[HttpHeaderTestXF.zip](https://github.com/xamarin/xamarin-android/files/13192146/HttpHeaderTestXF.zip)

In the image below, the left is the working Xamarin headers, and the right is the non-working MAUI headers:

![image](https://github.com/xamarin/xamarin-android/assets/3819142/4f734150-5dd2-4233-bee3-f8b84a96135d)

### Steps to Reproduce

Running either of the two sample apps and pressing "GET TEST" will return from our test API the headers that were passed to the API.

### Did you find any workaround?

Not yet.

**Comment by TonyLugg** [comment]
.NET 9 milestone?  So, nothing soon I suppose.  I would have thought there would be some way to do the equivalent of what we could do with Xamarin Android.

**Comment by TonyLugg** [comment]
@dotMorten provided me with a workaround to this issue.  

![image](https://github.com/xamarin/xamarin-android/assets/3819142/69c71878-c0d8-4a21-97a7-bd527d38999e)

Perhaps the HttpClient implementation could be added to the project properties (Android section), as it is in Xamarin.

**Comment by simonrozsival** [comment]
@TonyLugg Hey! You can also just set `<UseNativeHttpClient>false</UseNativeHttpClient>` in your .csproj file. That will ensure that HttpClient uses `SocketsHttpHandler` internally instead of the native platform-specific HTTP client which adds those default headers. Use can add a condition to limit this change just to Android the same way you did with that `#if`:

```xml
<UseNativeHttpHandler Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">false</UseNativeHttpHandler>
```

**Comment by grendello** [comment]
The Android client handler is a wrapper around the "native" Java HTTP client and, unfortunately, it has to work around its quirks, bugs and interesting behaviors, some of which are more heavy-handed than others.

The `Connection: Keep-Alive` header is added by the Java client, it could probably be overridden by setting it on our side, but not in the `AndroidMessageHandler` class IMO. It would need to be done by the application itself, since the framework should not enforce a particular behavior in this case.

The `Accept-Encoding: identity` header is the only way I could find to turn off compression in the Java client, otherwise setting `AutomaticDecompression = DecompressionMethods.None` on the managed client would have no effect.
