### ISSUE TITLE
`Android.Opengl.GLES20` is missing constant for `GL_CULL_FACE`.

### ISSUE THREAD

**Issue by AngryKittyMeow** [xamarin/xamarin-android#8612]
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.)

### Affected platform version

Anything using Android.opengl

### Description

In order to cull faces in opengl, the developer needs to call glEnable(GL_CULL_FACE);.  There is no such enumeration in Android.Opengl.  There is a work-around.  If the developer manually passes in 0x0B44 into glEnable then the developer can enable face culling. Without knowing this little cheat, it is not possible to enable face culling using Android.opengl as far as I can tell.
I'm sorry if this isn't a great issue report. I'm not a professional software developer, just a hobbyist. 

### Steps to Reproduce

Just try to look for an enum to pass into glEnable( ) that will activate face culling in an opengl project.

### Did you find any workaround?

Yes, manually pass in 0x0B44 into glEnable() in order to activate face culling.

**Comment by jpobst** [comment]
It looks like this constant gets removed because when it goes through our capitalization correction it becomes `GLES20.GlCullFace` which then conflicts with the method named `GLES20.GlCullFace`:

```
warning BG8401: Skipping 'Android.Opengl.GLES20.GlCullFace' due to a duplicate method name. (Java type: 'android.opengl.GLES20')
```

References:
- https://developer.android.com/reference/android/opengl/GLES20#GL_CULL_FACE
- https://developer.android.com/reference/android/opengl/GLES20#glCullFace(int)

We will need to rename it to something else to prevent the conflict.

Note: also affects `Android.Opengl.GLES10.GlCullFace`.
