### ISSUE TITLE
Application crashing

### ISSUE THREAD

**Issue by adamcookredding** [xamarin/xamarin-android#8639]
### Android application type

Classic Xamarin.Android (MonoAndroid13.0, etc.)

### Affected platform version

android 11

### Description

I have developed an app that runs on android 9 i wish to update it so it works with android 11. Initially the whole APK wasnt signed as it was only version 1 however its now signed with version 2

### Steps to Reproduce

install the apk and try to opening it and it crashes

### Did you find any workaround?

no

**Comment by jpobst** [comment]
With support for Classic Xamarin.Android ended [May 1st, 2024](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin), this issue is likely no longer relevant.

If this still persists in .NET 8+, please open a new issue with updated information based on `net8.0-android` or greater.  Please include a link to this issue for context.
