### ISSUE TITLE
how to use c++ dll in .net android (or MAUI android)?

### ISSUE THREAD

**Issue by ljzj2** [xamarin/xamarin-android#8922]
I want to use `md5withrsa` and I search google and I know I can use openssl.
1. I have create c++ dynamic library(.dll) 
2. I write the function to sign the strings using private key by openssl.
3. I can call it in .net Console Application in Windows.
4. now How can I call it in .net android? or how to make it to `.so` file?
5. I have searched the docs `using c++ in multiplatform` but it seems that it is only a wrapper.

**Comment by jonpryor** [comment]
*Why* do you want to use MD5 *anything*?  [MD5 is broken](https://en.wikipedia.org/wiki/MD5#Security):

> On 31 December 2008, the [CMU Software Engineering Institute](https://en.wikipedia.org/wiki/CMU_Software_Engineering_Institute) concluded that MD5 was essentially "cryptographically broken and unsuitable for further use".

2008 is *16 years ago*.  It should only be used if you absolutely need compatibility with something that consumes MD5, and it would far better to *replace all of that with something more recent*.  (For example, we *used to use* md5 to create Java package names for Java Callable Wrappers, not because we needed security, but because MD5 was *convenient*.  We've since moved to CRC64 hashes, which *aren't* cryptographically secure, and we never needed that anyway…)

Assuming you still want/need to use MD5, we then hit the next major hurdle:

> 2. I write the function to sign the strings using private key by openssl.

The hurdle being that OpenSSL *is not part of the stable Android API*.  You can't write C++ code for Android which uses OpenSSL *unless* you plan on (possibly building and) redistributing OpenSSL yourself.

.NET for Android does not directly use OpenSSL.  Instead, [.NET uses JNI to lookup Java APIs for TLS-related functionality](https://github.com/dotnet/runtime/blob/6c3245ed44e3f205a244d990e50c9510f6e1e9a6/src/native/libs/System.Security.Cryptography.Native.Android/pal_jni.c).

> 1. I have create c++ dynamic library(.dll)
> 2. I write the function to sign the strings using private key by openssl.
> 3. I can call it in .net Console Application in Windows.
> 4. now How can I call it in .net android? or how to make it to .so file?

You would need to:

 1. Obtain a copy of OpenSSL compiled for your target Android ABI. Let's call this `libssl.so` for demonstration purposes.

    It should be noted that this step itself may be very difficult, and in turn require that any apps redistributing your `libssl.so` stay on top of any and all security CVEs for OpenSSL.  There are metaphorical ***dragons*** in this step.

 2. Use the [Android NDK](https://developer.android.com/ndk) to compile your C++ code into a `libexample-name.so`, and have `libexample-name.so` link against your `libssl.so`.

 3. Ensure that `libexample-name.so` has an `extern "C"` function, e.g.

    ```cpp
    extern "C" void DoTheSigningThing(void* parameter);
    ```

 4. You would add *both* `libexample-name.so` *and* `libssl.so` to your .NET for Android app into an appropriately named directory, e.g. `lib\arm64-v8a\libexample-name.so`.

 5. You would add a `[DllImport]` somewhere in your C# .NET for Android app to invoke (3), and elsewhere invoke it:

    ```csharp
    [DllImport("example-name")]
    static extern void DoTheSigningThing(IntPtr p);
    ```

---

Again, redistributing OpenSSL is dealing with metaphorical dragons.

You would likely be better served rewriting your existing C++ code to use C# and types in the [System.Security namespaces](https://learn.microsoft.com/en-us/dotnet/api/system.security?view=net-8.0).

**Comment by ljzj2** [comment]
thank you for so detailed answer.I've learned a  lot.
now many people still use md5 and I do not know why.

>  is not part of the stable Android API.

but I find that.
`PKCS8EncodedKeySpec` and ` KeyFactory.GetInstance` and `Signature.GetInstance("MD5withRSA")`  will fit me.

and I always answer others question not that patient. you answer me so many for each sentence. I should learn from you.
